### ISSUE TITLE
[Backend phân tán] Gửi bổ sung hồ sơ đầu doanh nghiệp, trạng thái hồ sơ báo lỗi

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1000]
1. Cán bộ yêu cầu bổ sung hồ sơ, 
2. Hồ sơ bên đầu doanh nghiệp đã chuyển trạng thái Chờ bổ sung
3. Doanh nghiệp nhấn gửi bổ sung hồ sơ.
   Lỗi: Hồ sơ chuyển trạng thái lỗi (trạng thái hồ sơ phía cán bộ vẫn là Chờ bổ sung)

**Comment by khoahp** [comment]
@tragiangdt test lại nhé

**Comment by tragiangdt** [comment]
Đã chuyển đúng trạng thái khi NLTT bổ sung hồ sơ
