### ISSUE TITLE
Bỏ bắt buộc tải ảnh công dân

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1003]
Phần đăng ký tài khoản công dân bỏ bắt buộc phần tải chứng minh thử
![screenshot from 2016-09-09 16-50-35](https://cloud.githubusercontent.com/assets/17336814/18383010/b3540780-76ad-11e6-856b-07ddb663c8e0.png)
=> Tuy không có chú thích bắt buộc, nhưng vẫn báo lỗi bắt buộc đính kèm
=> Kết quả mong muốn: Không bắt buộc đính kèm

**Comment by huymq** [comment]
Phần này bỏ bắt buộc luôn trong core nhé bác @khoahp

**Comment by binhth** [comment]
@huymq 
Giải pháp bỏ check size=0 trong khi validate.
đã fixed.
@hoanb : test lại nhá.

**Comment by hoanb** [comment]
Done

**Comment by hoanb** [comment]
Done
