### ISSUE TITLE
Thêm chứng năng gửi thông báo qua Email cho người làm thủ tục và cán bộ

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1004]
Khi xử lý hồ sơ NLTT, cán bộ cần có thông báo qua mail ở từng trạng thái hồ sơ để biết xử lý kịp thời hồ sơ đó
Ví dụ khi cán bộ xử lý hồ sơ yêu cầu bổ sung hồ sơ thì phải có một thông báo qua email để NLTT biết

**Comment by huymq** [comment]
Chức năng này anh @tanhtanhvn xem có bổ sung vào chỗ thông tin cấu hình của bước xử lý được không ạ?

**Comment by khoahp** [comment]
@huymq https://github.com/VietOpenCPS/doc/wiki/Ph%C3%A2n-t%C3%ADch-qu%E1%BA%A3n-l%C3%BD-th%C3%B4ng-b%C3%A1o phần này đã có thiết kế của anh @tanhtanhvn , nhóm core sẽ bổ xung vào phiên bản 2.0 nhé!

**Comment by khoahp** [comment]
@tragiangdt  close issue này, gộp chung issue #405
