### ISSUE TITLE
Chưa hiển thị thành phần giấy tờ kết quả khi cán bộ tra cứu hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1005]
1. Đăng nhập bằng tk cán bộ canboxuly2.cps@gmail.com
2. Vào menu tra cứu hồ sơ http://qa.opencps.vn/group/guest/tra-cuu-ho-so
3. Lỗi: Chưa hiển thị thành phần giấy tờ kết quả trên tab Nội dung hồ sơ
   KQMM: Hiển thị thành phần giấy tờ kết quả trên tab nội dung hồ sơ và sắp xếp thứ tự theo cấu hình tphs trong mẫu hồ sơ
   ![2016-09-09_181045](https://cloud.githubusercontent.com/assets/17695836/18385120/d9a8643e-76b8-11e6-8f62-a8dfa8364dc2.png)

**Comment by binhth** [comment]
@huymq 
đã hiển thị thêm thành phần hồ sơ trả về trong màn hình nội dung hồ sơ.
đã fixed.
@tragiangdt : test lại nhá.

**Comment by tragiangdt** [comment]
test done trên qa
