### ISSUE TITLE
Nhiều label của button bị hiển thị sai ngôn ngữ hoặc sai value

### ISSUE THREAD

**Issue by nampq309** [VietOpenCPS/opencps#1013]
Nhiều label của button bị hiển thị sai ngôn ngữ hoặc sai value
ex: http://prntscr.com/chqu34

**Comment by binhth** [comment]
@nampq309

**Comment by khoahp** [comment]
@nampq309 phần này có nhiều chỗ chưa hiển thị đúng, phần này được cho vào issue #1106, do vậy mình close bug này nhé
