### ISSUE TITLE
Thêm thứ tự thành phần hồ sơ (New feature)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1021]
Danh sách các Thành phần hồ sơ chưa có số thứ tự
Kết quả mong muốn: Đánh thêm số thứ tự hiển thị thành phần hồ sơ

**Comment by huymq** [comment]
@dunglt91 liên hệ với @hoanb để xem trong màn hình nào nhé

**Comment by dunglt91** [comment]
@hoanb test lai nhe

**Comment by hoanb** [comment]
Done
