### ISSUE TITLE
Tại màn hình popup "Tải giấy tờ" cho phần tải file biểu mẫu về máy tính (New feature)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1022]
Tại màn hình popup "Tải giấy tờ" cho thêm phần Label "Tải file biểu mẫu về máy tính" kèm theo link tải file biểu mẫu. 
Mong muốn: Người làm thủ tục có thể tải biểu mẫu về máy tính tại màn hình Popup

**Comment by huymq** [comment]
@binhth check lại chỗ anh @vuhongson xem chỗ đặt link nên để trong màn hình popup hay bên cạnh nút tải lên nhé

**Comment by hoanb** [comment]
Done
