### ISSUE TITLE
Bỏ qua bước khi lại thông tin hồ sơ (New feature)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1023]
B1. NLTT đăng nhập
B2. Chọn " Chuẩn bị hồ sơ nộp trực tuyến"
B3. Chọn dịch vụ công 
B4. Thông tin hồ sơ: Kích chọn "Ghi lại"
B5. Chọn tab Thành phần hồ sơ để tải giấy tờ
Kết quả mong muốn: Bỏ qua bước 4. từ bước 3 chuyển luôn qua bước 5

**Comment by khoahp** [comment]
@hoanb phần này đã trao đổi trước đó, tab giấy tờ chỉ sinh ra khi tạo mới xong hồ sơ.

@huymq trao đổi lại vs anh @tanhtanhvn xem có xử lý không

**Comment by hoanb** [comment]
Done
