### ISSUE TITLE
Lọc hồ sơ, dịch vụ công theo đến level 2 (New Feature)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1024]
B1. NLTT đăng nhập
B2. Chọn lọc danh sách hồ sơ theo lĩnh vực level 2
Kết quả test: Chưa lọc được danh sách hồ sơ theo level 2
B3. Chọn "Chuẩn bị hồ sơ nộp trực tuyến"
B4. Lọc danh sách dịch vụ công theo lĩnh vực level 2
Kết quả: Chưa lọc được danh sách dịch vụ công theo level 2

Kết quả mong muốn: Lọc được danh sách hồ sơ và dịch vụ công theo level 2

**Comment by binhth** [comment]
@hoanb

**Comment by hoanb** [comment]
Done
