### ISSUE TITLE
Thêm menu phân nhóm trạng thái hồ sơ bên phía cán bộ (New feature)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1026]
Chưa có menu phân nhóm trạng thái hồ sơ phía cán bộ.
Kết quả mong muốn: Thêm menu phân nhóm (có số lượng hồ sơ) hồ sơ cho phần danh sách hồ sơ phía cán bộ

**Comment by binhth** [comment]
@hoanb

**Comment by huymq** [comment]
@tragiangdt @binhth . Bổ sung thêm để tối ưu cho người sử dụng
Chia màn hình Hồ sơ chờ xử lý có layout 20_80
1. Lọc theo TTHC đưa sang bên trái
2. Lọc theo bước xử lý chuyển sang bên trái (có thống thống kê số hồ sơ theo bước), list tất cả các bước xử lý
