### ISSUE TITLE
Có thông báo khi ấn Ghi lại, gửi hồ sơ (New feature)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1027]
B1. Người làm thủ tục tải thành phần hồ sơ kích chọn "Ghi lại"
B2. Kích chọn "Gửi"
Kết quả: Không có thông báo
Kết quả mong muốn: Có thông báo lưu hồ sơ thành công, Gửi hồ sơ thành công

**Comment by binhth** [comment]
@hoanb
