### ISSUE TITLE
Thêm phần chú tích thông báo số hồ sơ dùng để tra cứu hồ sơ (New feature)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1028]
NLTT chưa hiểu số hồ sơ để làm gì.
Kết quả mong muốn : Thêm chú thích thông báo " Số hồ sơ dùng để tra cứu hồ sơ"

**Comment by huymq** [comment]
@binhth check lại chỗ anh @vuhongson xem cụ thể đặt cái dòng chú thích kia ở đâu

**Comment by binhth** [comment]
@hoanb

**Comment by hoanb** [comment]
Done
