### ISSUE TITLE
Chức năng chỉ xem bị lỗi không xem được chi tiết hồ sơ

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#1034]
1.Cấu hình 1 DVC có bước xử lý gán một role chức năng chỉ xem
2.Đăng nhập vào TK gán role đó thì không xem được chi tiết hồ sơ

**Comment by tragiangdt** [comment]
Issue này nghĩa là tại cấu hình bước xử lý Kiểm tra hồ sơ,
có chọn lãnh đạo phòng chỉ xem bước xử lý này (cấu hình như hình bên dưới)
Lỗi: trên giao diện hồ sơ chờ xử lý của Lãnh đạo phòng, những hồ sơ có bước xử lý Kiểm tra hồ sơ đều không có chỗ nào để click vào xem chi tiết hồ sơ ạ
KQMM: Những vai trò được cấu hình xem hồ sơ tại bước xử lý nào đó thì có thể xem được chi tiết hồ sơ

![2016-09-19_100016](https://cloud.githubusercontent.com/assets/17695836/18621620/4f847258-7e50-11e6-925e-45dbe278bab0.png)

**Comment by tragiangdt** [comment]
@khoahp

**Comment by khoahp** [comment]
@tragiangdt okie em.

@Hongnt31 viêt issue phải thê hiện được như thế này thì mới sử lý được, em chỉ viết hiện tượng thôi, chưa hiểu bản chất, cần rút kinh nghiệp

**Comment by tragiangdt** [comment]
@khoahp  Lỗi này vẫn còn anh

**Comment by trungnt-ksnb** [comment]
@khoahp done

**Comment by Hongnt31** [comment]
test done
