### ISSUE TITLE
Duplicate file khi công dân chọn file từ tab thư mục

### ISSUE THREAD

**Issue by nampq309** [VietOpenCPS/opencps#1035]
Build trên source code hiện tại của branch "develop"
Khi công dân muốn chọn 1 file mà họ đã upload từ tab thư mục thì hệ thống đang duplicate file.
http://prnt.sc/cjg86j

**Comment by khoahp** [comment]
@nampq309 phần dublicate theo thiết kế của dự án, khi chọn file của hồ sơ đây là một file mới được tạo ra từ file mẫu.
