### ISSUE TITLE
Chưa ẩn nút Hướng dẫn nộp hồ sơ khi xem chi tiết thủ tục hành chính mức 2

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1039]
1. Vào tra cứu thủ tục hành chính: http://qa.opencps.vn/web/guest/thu-tuc-hanh-chinh
2. Vào xem chi tiết 1 thủ tục hành chính
   Lỗi: Luôn hiển thị nút  online-url-button 
   KQMM: Chỉ hiển thị nút này khi nào có cấu hình DVC, nếu chưa được cấu hình DVC thì ẩn nút này đi
   ![s](https://cloud.githubusercontent.com/assets/17695836/18626324/83f82cc2-7e7e-11e6-855c-f3f14e088dd9.png)

**Comment by dunglt91** [comment]
@tragiangdt test lại nhé

**Comment by tragiangdt** [comment]
@dunglt91 Lỗi này vẫn còn trên server dev nhé

**Comment by tragiangdt** [comment]
test done trên server dev

**Comment by dunglt91** [comment]
@tragiangdt xem xét close issue nhé

**Comment by tragiangdt** [comment]
test done trên qa
