### ISSUE TITLE
Issue liên quan đến các bước đăng ký tài khoản của công dân/doanh nghiệp

### ISSUE THREAD

**Issue by nampq309** [VietOpenCPS/opencps#1046]
Trên cấu hình portlet đăng ký mình thấy cấu hình các step đăng ký là 3.
Khi đăng ký TK cho công dân. Mình nhận được 1 email confirm có gửi kèm link ntn:

`http://localhost:8080/opencps-portlet/verify/email?token=e908f2f6-08f4-472c-8750-332c7be2a221&ticketKey=0b97294d-0e23-4215-80d7-d05e73ddb4b8&type=CITIZEN&p_l_id=22226.`

Sau đó mình click vào link trên thì màn hình browser hiển thị ra thông báo:

"confirm-email-address-error Click here to turn back portal"

Nhưng ngay sau đó (sau khoảng 1p từ lúc nhận được email confirm) mình vẫn nhận được email thứ 2 có gửi kèm password. Mình sử dụng password này để vào hệ thống login cho account vừa đăng ký nhưng không đăng nhập được.
Nội dung email thứ 2:

`Dear Công dân s05,

Welcome! You recently created an account at http://qa.opencps.vn. Your password is qDgZDVZd. Enjoy!

Sincerely,
Test Test
test@liferay.com
http://qa.opencps.vn`

Sau đó mình phải vào màn hình quản lý tk công dân, tổ chức enable account công dân trên thì mình nhận được email thứ 3:

`Dear Công dân s05,

Welcome! yeor account has activate

Sincerely,
Test Test`

Vấn đề nằm ở chỗ user là công dân/doanh nghiệp sẽ dễ bị lầm tưởng là account của mình đã được kích hoạt rồi nên sẽ vào hệ thống đăng nhập luôn mà ko đợi admin kích hoạt. Nên chăng sửa lại content email thứ 2 để báo cho công dân/DN biết là cần chờ kích hoạt để tránh nhầm lẫn. Hoặc đây đang nhầm với kịch bản đăng ký 2 step?
Ngoài ra bước click vào link confirm thì hệ thống lại hiển thị lỗi, nhưng vẫn sinh mail gửi password?

**Comment by nampq309** [comment]
Mình xin bổ sung là hiện tại cấu hình 2 bước thì hệ thống ko gửi email password nhưng trạng thái tài khoản công dân/DN vẫn chuyển sang trạng thái "Hoàn thành"

**Comment by khoahp** [comment]
@huymq xem phần đăng ký này nhé

**Comment by huymq** [comment]
Gửi bạn @nampq309 

> Vấn đề nằm ở chỗ user là công dân/doanh nghiệp sẽ dễ bị lầm tưởng là account của mình đã được kích hoạt rồi nên sẽ vào hệ thống đăng nhập luôn mà ko đợi admin kích hoạt. Nên chăng sửa lại content email thứ 2 để báo cho công dân/DN biết là cần chờ kích hoạt để tránh nhầm lẫn. Hoặc đây đang nhầm với kịch bản đăng ký 2 step?

Nội dung email gửi về đang sử dụng cấu hình của Liferay. Nên bản deploy sẽ tùy chỉnh lại nội dung phù hợp để gửi về cho người đăng ký

> Ngoài ra bước click vào link confirm thì hệ thống lại hiển thị lỗi, nhưng vẫn sinh mail gửi password?

Lỗi này bạn kiểm tra giúp lại xem còn bị nữa không?

> Mình xin bổ sung là hiện tại cấu hình 2 bước thì hệ thống ko gửi email password nhưng trạng thái tài khoản công dân/DN vẫn chuyển sang trạng thái "Hoàn thành"
> Với truờng hợp cấu hình 2 bước.
- Khi đăng ký tài khỏan xong sẽ có mail gửi link kích hoạt về địa chỉ email của người đăng ký, khi click vào link kích hoạt thì sẽ có mail gửi thông tin đăng nhập về mail
- Sử dụng thông tin đăng nhập sẽ đăng nhập được luôn, thay vì phải thêm bước người quản trị xác nhận như trường hợp 2 bước.

**Comment by duchung381991** [comment]
Hiện tại lỗi đăng kí vẫn chưa fix đc hả mọi người, em cấu hình có mail gửi password đăng nhập về nhưng không sử dụng được pass đó

**Comment by khoahp** [comment]
@tragiangdt xác nhận phần đăng lý này nhé, nếu ổn close

**Comment by khoahp** [comment]
@nampq309 phần này mình close lại do đã làm lại theo issue #1159
