### ISSUE TITLE
Kế toán chưa tìm kiếm được phiếu thanh toán theo mã số tiếp nhận + tên chủ hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1054]
1. Vào tài khoản kế toán: http://qa.opencps.vn/group/guest/quan-ly-thu-phi
2. Nhập mã số tiếp nhận hoặc tên chủ hồ sơ
3. Lỗi: chưa tìm kiếm được phiếu thanh toán theo mã số tiếp nhận + tên chủ hồ sơ

![2016-09-22_142225](https://cloud.githubusercontent.com/assets/17695836/18739752/070cfc3e-80d0-11e6-83e4-b18423c69266.png)

**Comment by khoahp** [comment]
@huymq xl cái này nhé

**Comment by huymq** [comment]
@dunglt91 hướng dẫn @hltn fix nhé

**Comment by dunglt91** [comment]
@tragiangdt test lai nhe

**Comment by Hongnt31** [comment]
@khoahp 
Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20132201/63b3d5f4-a694-11e6-9e8a-88a7c26dfa70.png)

![image](https://cloud.githubusercontent.com/assets/20554327/20132209/697f2916-a694-11e6-844a-008d1e8409bd.png)
