### ISSUE TITLE
Lỗi thông báo khi tải thành phần hồ sơ

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#1058]
B1. Khi nhập tên giấy tờ dài hơn độ dài DB
Ví dụ: Bản sao văn bản xác nhận của nhà chức trách hàng không cấp Giấy chứng nhận đủ điều kiện bay về khả năng thực hiện chuyến bay an toàn (Special Flight Permit or Ferry Flight Permit) trong trường hợp tàu bay có Giấy chứng nhận đủ điều kiện bay tạm thời bị mất hiệu lực
B2. Đính kèm file 
B3. Chọn "Đồng ý"
KQ: Xuất hiện thông báo lỗi "Xảy ra lỗi trong quá trình tải tệp lên hệ thống" như hình bên dưới
KQMM: 
1.Sửa lại thông báo 
2.Tăng độ dài DB
![hinh ch p t 2016-09-22 17-25-47](https://cloud.githubusercontent.com/assets/20554327/18744939/55ad57de-80ea-11e6-8088-6eeaf12534dd.png)

**Comment by huymq** [comment]
@tuhoanganh mở rộng trường displayname của table opencps_dossier_file thành mediumtext nhé

**Comment by huymq** [comment]
@Hongnt31 test lại nhé

**Comment by Hongnt31** [comment]
test done
