### ISSUE TITLE
[Backend phân tán] NLTT gửi bổ sung hồ sơ bị lỗi

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1060]
1. Gửi bổ sung lần 2 thì số tiếp nhận đầu NLTT bị nhảy
2. Sinh thành 2 phiếu xử lý hồ sơ, 1 phiếu là số tiếp nhận cũ  2016091507076(trạng thái chờ bổ sung), 1 phiếu là số tiếp nhận mới  201609150707 (trạng thái đang xử lý)
3. Phiếu mới sinh ra không có nội dung file giấy tờ tải lên

**Comment by trungnt-ksnb** [comment]
@tragiangdt  done

**Comment by Hongnt31** [comment]
Test done
