### ISSUE TITLE
[Backend phân tán] Chưa chuyển trạng thái phiếu thanh toán khi thanh toán trực tuyến

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1061]
NLTT thực hiện thanh toán trực tuyến, phiếu thanh toán chưa chuyển trạng thái hoàn thành, phương thức thanh toán: trực tuyến

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by tragiangdt** [comment]
test done
