### ISSUE TITLE
Cập nhật lại log hồ sơ và lịch sử xử lý theo thiết kế mới

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1062]
- Kịch bản lưu log hồ sơ (Bổ xung log liên quan đến thanh toán)
- Kịch bản lưu log xử lý (Chỉ ghi lại log khi chuyển bước thành công)
- Cách hiển thị lịch sử theo đối tượng xử lý

**Comment by Hongnt31** [comment]
@khoahp vẫn còn các lỗi: Chưa lưu được log thanh toán
![image](https://cloud.githubusercontent.com/assets/20554327/20131774/23566ad2-a692-11e6-8685-b9c265ba63d8.png)

**Comment by khoahp** [comment]
@Hongnt31 em test lịch sử hồ sơ trên mấy đối tượng? Những chỗ nào có lịch sử?

**Comment by Hongnt31** [comment]
@khoahp Em test trên cả NLTT và Cán bộ đều không lưu log về thanh toán

**Comment by Hongnt31** [comment]
@khoahp Đã lưu log Thanh toán
![image](https://cloud.githubusercontent.com/assets/20554327/20176529/caae40b4-a77a-11e6-9fc6-fbc66a01d7e4.png)
