### ISSUE TITLE
[Backend phân tán] Phiếu thanh toán chưa chuyển trạng thái Đã báo nộp bên cơ quan xử lý

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1064]
1. Đăng nhập tài khoản NLTT
2. Vào Yêu cầu thanh toán, thực hiện thanh toán bằng hình thức Chuyển khoản
3. NLTT upload file lên, click Báo nộp; 
   Phiếu thanh toán đầu NLTT đã chuyển trạng thái thành Đã báo nộp
4. Lỗi: Phiếu thanh toán đầu kế toán (cơ quan xử lý) chưa chuyển trạng thái Đã báo nộp + chưa nhận được file NLTT upload (trạng thái vẫn là Chờ nộp)

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by tragiangdt** [comment]
test done
