### ISSUE TITLE
[Backend phân tán]Chưa hiển thị nút xin hủy hồ sơ đầu NLTT

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1066]
1. Cấu hình quy trình đầu nhận hồ sơ có hành động xin hủy hồ sơ
2. Lỗ: Chưa hiển thị nút xin hủy hồ sơ đầu NLTT

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by Hongnt31** [comment]
vẫn còn lỗi

**Comment by tragiangdt** [comment]
đã hiển thị
