### ISSUE TITLE
[Backend phân tán]Không lưu được giá trị form động đầu NLTT

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1068]
1. Vào tài khoản NLTT
2. Khai đơn động, click Ghi lại
   Hệ thống xuất được báo cáo có giá trị vừa khai.
   Lỗi: 
   -Cột trạng thái giấy tờ chưa được check
3. Mở xem lại form động, ko lưu được giá trị vừa khai

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by Hongnt31** [comment]
Test done
