### ISSUE TITLE
[Backend phân tán]Mất nút xem nội dung khi xem lại hồ sơ đầu NLTT

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1069]
1. NLTT click vào nút Xem trên danh sách quản lý hồ sơ
2. Lỗi: 
   -Mất nút xem nội dung khi xem lại hồ sơ đầu NLTT
   -Cột trạng thái bị mất dấu check
   ![2016-09-23_165714](https://cloud.githubusercontent.com/assets/17695836/18782092/e6b59704-81ae-11e6-941c-49357bc2ee1b.png)

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by Hongnt31** [comment]
Test done
![image](https://cloud.githubusercontent.com/assets/20554327/19144047/b1ccfc30-8bd1-11e6-86ce-4513ebe526c0.png)
