### ISSUE TITLE
[Backend phân tán]Mất nút xem nội dung khi xem lại hồ sơ đầu CBXL

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1070]
1. Cán bộ xử lý click vào nút Xem trên danh sách quản lý hồ sơ
2. Lỗi: -Mất nút xem nội dung khi xem lại hồ sơ đầu cán bộ xử lý
   -Cột trạng thái bị mất dấu check 
   ![2016-09-23_170539](https://cloud.githubusercontent.com/assets/17695836/18782308/155a2948-81b0-11e6-917c-de93c62ac3b6.png)

**Comment by trungnt-ksnb** [comment]
@tragiangdt  done

**Comment by Hongnt31** [comment]
Test done 
![image](https://cloud.githubusercontent.com/assets/20554327/19144019/7f3657d0-8bd1-11e6-99ee-62090a3db349.png)
