### ISSUE TITLE
Yêu cầu: Đưa tiêu chí tìm kiếm theo TTHC + bước xử lý thành menu trái (màn hình Hồ sơ chờ xử lý)

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1071]
Chia màn hình Hồ sơ chờ xử lý có layout 20_80
1. Lọc theo TTHC đưa sang bên trái 
2. Lọc theo bước xử lý chuyển sang bên trái (có thống thống kê số hồ sơ theo bước), list tất cả các bước xử lý

**Comment by huymq** [comment]
@tragiangdt trùng với issues #1026
