### ISSUE TITLE
Kho lưu trữ không tìm kiếm được

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1073]
B1. Đăng nhập
B2. Chuẩn bị hồ sơ khai trực tuyến
B3. Tải giấy tờ
B4. Vào tab Kho lưu trữ
Kết quả: Tìm kiếm nhưng quay lại màn hình tải giấy tờ, kho lưu trữ đang có nhiều giấy tờ kết quả
Kết quả mong muốn: Kho giấy tờ chỉ lưu trữ giấy tờ đã tải lên, bỏ giấy tờ kết quả đi. Tìm kiếm được giấy tờ

**Comment by khoahp** [comment]
@huymq phần kho lưu trữ này liệu có ổn cho 1.7 không e ơi

**Comment by Hongnt31** [comment]
@hoanb @khoahp Vẫn chưa tìm kiếm được
![image](https://cloud.githubusercontent.com/assets/20554327/20131674/90237a5c-a691-11e6-8887-e328bbaec2dc.png)

**Comment by Hongnt31** [comment]
@khoahp  Done 
![image](https://cloud.githubusercontent.com/assets/20554327/24500383/5ba8a73c-156f-11e7-9fd0-c6b1f96e974c.png)
