### ISSUE TITLE
Lỗi trả về giấy tờ kết quả không đúng cấu hình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1077]
Mô tả:
1. Vào tài khoản doanh nghiệp (http://qa.opencps.vn/group/guest/quan-ly-ho-so)
2. Nộp hồ sơ thủ tục: Xác nhận đăng ký thực hiện khuyến mại theo hình thức mang tính may rủi thực hiện trên địa bàn từ 2 tỉnh, thành phố trực thuộc Trung ương trở lên hoặc theo quy định tại Điều 17 NĐ số 37/2006/NĐ-CP (Cục Xúc tiến thương mại)
3. Cán bộ văn thư yêu cầu bổ sung hs
4. Doanh nghiệp nộp bổ sung hồ sơ
Lỗi: Khi mở xem lại hồ sơ vừa gửi bổ sung, trên tab Kết quả, doanh nghiệp nhìn thấy được hết các giấy tờ kết quả (bước DN gửi bổ sung không cấu hình có giấy tờ trả về)

**Comment by tragiangdt** [comment]
@khoahp @huymq 
các anh hotfix giúp em, lỗi này ảnh hưởng đến quy trình xử lý

**Comment by Hongnt31** [comment]
@tragiangdt  @khoahp  Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20131597/101dbf3e-a691-11e6-8e56-2112a0585588.png)
