### ISSUE TITLE
Chưa lọc phiếu thanh toán theo Cơ quan thực hiện ở portlet quản lý thu phí

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1078]
1. Đăng nhập vào tài khoản kế toán của cơ quan thực hiện A
   Lỗi: Hệ thống hiển thị hết tất cả các phiếu thanh toán của các cơ quan khác 
   KQMM: Sau khi kế toán đăng nhập, hệ thống chỉ hiển thị các phiếu thanh toán thuộc cơ quan A (không hiển thị tất cả)

**Comment by huymq** [comment]
@dunglt91 vs @NVP191 làm lỗi này nhé

**Comment by huymq** [comment]
@tragiangdt test lại lỗi này trên QA nhé

**Comment by tragiangdt** [comment]
test done trên qa
