### ISSUE TITLE
Thừa lable mật khẩu mới khi đăng nhập lần đầu

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1079]
Đang có hai dòng mật khẩu mới
Kết quả mong muốn: Bỏ đi 1 lable

**Comment by huymq** [comment]
@hoanb: Những bug này gửi cả ảnh cho tường minh em nhé

**Comment by huymq** [comment]
@thanhld2901 anh Thanh check bug này nhé
