### ISSUE TITLE
Lỗi số ngày cần thiết để xử lý bước trong quy trình không hoạt động

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1080]
1. Vào tài khoản quản trị
2. Vào cập nhật bước xử lý, nhập số ngày xử lý
3. Lỗi: số ngày cần thiết để xử lý bước trong quy trình không hoạt động (trên màn hình lịch sử xử lý, Hạn xử lý luôn là 0)
   KQMM: số ngày cần thiết để xử lý bước trong quy trình hoạt động
   ![2016-09-29_095646](https://cloud.githubusercontent.com/assets/17695836/18939526/19f3f7b6-862b-11e6-8342-0455eec3b108.png)

**Comment by tragiangdt** [comment]
@khoahp 
Hạn xử lý trên danh sách hồ sơ chờ xử lý không hoạt động

**Comment by Hongnt31** [comment]
@tragiangdt @khoahp vẫn còn lỗi 
![image](https://cloud.githubusercontent.com/assets/20554327/20131089/d2ffd248-a68d-11e6-9029-05767a3cb4f4.png)

**Comment by khoahp** [comment]
@Hongnt31 em test quy trình này như thế nào?

**Comment by Hongnt31** [comment]
@khoahp cái trên e test số ngày bị trễ thì ok rùi nhá, e tưởng nó là ngày hết hạn
còn Hạn xử lý trên danh sách hồ sơ chờ xử lý không hoạt động
![image](https://cloud.githubusercontent.com/assets/20554327/20174594/30e03fae-a771-11e6-96aa-43378f926987.png)

**Comment by Hongnt31** [comment]
@khoahp vẫn cho hạn xử lý của từng bước

**Comment by khoahp** [comment]
@Hongnt31 hạn xử lý từng bước là đúng rồi mà em

**Comment by Hongnt31** [comment]
@khoahp 
Hạn xử lý từng bước= số ngày trong cấu hình- (ngày hiên tại - ngày nhận hồ sơ)
Hiện tại: Chưa hiển thị ví dụ bước tiếp nhận hồ sơ cấu hình 1 ngày thì theo công thức trên phải hiển thị còn 1 ngày khi ngay tại ngày nhận được hồ sơ

**Comment by tragiangdt** [comment]
@khoahp 
"- Cấu  hình tại bước tiếp nhận có 1 ngày xử lý, nhưng trên danh sách hồ sơ chờ xử lý lại hiển thị Còn 3 ngày
- Hạn xử lý khi xem lại lịch sử xử lý của cán bộ chưa đúng (luôn hiển thị số 0)"

**Comment by tragiangdt** [comment]
Các lỗi trên đã test ok
