### ISSUE TITLE
NLTT chưa xem được phiên bản giấy tờ kết quả trả về (new feature)

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1081]
1. Vào tk NLTT
2. Vào xem chi tiết 1 hồ sơ -> vào tab Kết quả 
3. Hiện tại NLTT chưa xem được version giấy tờ kết quả trả về. Trong TH Cán bộ xử lý yêu cầu bổ sung nhiều lần, NLTT chỉ nhận file yêu cầu bổ sung cuối cùng, không xem lại được các file trước CBXL yêu cầu bổ sung.
   KQMM: NLTT xem được phiên bản giấy tờ kết quả trả về 
   ![2016-09-29_101652](https://cloud.githubusercontent.com/assets/17695836/18939913/449dc3fe-862e-11e6-8fdd-a1333adee57c.png)

**Comment by huymq** [comment]
@thanhld2901 
Anh làm bug này hỏi anh @trungnt-ksnb nhé
