### ISSUE TITLE
Lỗi thông báo "Quản lý quy trình xử lý thủ tục tạm thời không có."

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1083]
1. Vào tài khoản quản trị
2. Vào quản lý quy trình
3. Thêm mới bước xử lý
4. Đặt tên bước xử lý, nhưng KHÔNG chọn trạng thái hồ sơ -> Ghi lại
5. Lỗi: Mở xem chi tiết bước xử lý vừa thêm, hệ thống thông báo "Quản lý quy trình xử lý thủ tục tạm thời không có."
   KQMM: Khi không chọn trạng thái hồ sơ tại màn hình cập nhật bước xử lý thì khi xem lại vẫn xem được chi tiết bước xử lý và không báo "Quản lý quy trình xử lý thủ tục tạm thời không có."
   ![2016-09-29_115640](https://cloud.githubusercontent.com/assets/17695836/18941574/844b22d6-863c-11e6-9b85-0cbd0f59cf05.png)

**Comment by dunglt91** [comment]
@tragiangdt test nhé

**Comment by Hongnt31** [comment]
@dunglt91  Hiện tại trên con dev vẫn còn lỗi này
Thêm lỗi khi thêm mới một bước xư lý cũng xuất hiện thông báo lỗi "Quản lý quy trình xử lý thủ tục tạm thời không có"

**Comment by dunglt91** [comment]
@Hongnt31 em test lại nhé

**Comment by Hongnt31** [comment]
Test done  trên opencps-dev
