### ISSUE TITLE
Chưa hiển thị số hồ sơ tại màn hình xem chi tiết hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1084]
1. Cán bộ vào xem chi tiết hồ sơ
2. Lỗi: Đang hiển thị 2 dòng mã tiếp nhận trùng nhau
3. KQMM: Thay thế dòng mã tiếp nhận đầu tiên là "Số hồ sơ: ..."
   ![2016-09-29_145013](https://cloud.githubusercontent.com/assets/17695836/18978069/c66a98b0-86e9-11e6-8718-84ff589d068f.png)

**Comment by dunglt91** [comment]
@tragiangdt test nhé

**Comment by tragiangdt** [comment]
test done trên server dev
