### ISSUE TITLE
Chưa tìm kiếm theo số số hồ sơ trên trang quản lý hồ sơ của NLTT

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1085]
1. Vào tài khoản NLTT
2. Tìm kiếm theo số hồ sơ
3. Lỗi: Luôn hiển thị không có kết quả
4. KQMM: Tìm kiếm được theo số hồ sơ trên trang quản lý hồ sơ của NLTT
   ![2016-09-30_085957](https://cloud.githubusercontent.com/assets/17695836/18978335/7b721448-86ec-11e6-843e-ea6d6d885ad5.png)

**Comment by dunglt91** [comment]
@tragiangdt trên trang opencps-dev đã tìm được theo số hồ sơ phía NLTT
![fireshot capture 6 - qu n ly h s - c ng tho_ - http___opencps-dev fds vn_group_guest_quan-ly-ho-so](https://cloud.githubusercontent.com/assets/17336343/19034759/80d77ff4-898f-11e6-8716-946ea7fde071.png)

**Comment by tragiangdt** [comment]
test done trên server dev

**Comment by dunglt91** [comment]
xem xét close issue nhé :D

**Comment by tragiangdt** [comment]
@khoahp Lỗi này chưa ddc sửa trên qa
