### ISSUE TITLE
Cán bộ chưa tra cứu được theo mã số hồ sơ 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1086]
1. Vào tk cán bộ
2. Vào Tra cứu hồ sơ
3. Tìm kiếm theo mã số hồ sơ
   Lỗi: Không tìm kiếm được
   KQMM: Cán bộ chưa tra cứu được theo mã số hồ sơ 
   ![2016-09-30_091042](https://cloud.githubusercontent.com/assets/17695836/18978491/cf4d2b1a-86ed-11e6-90f1-1c1657538110.png)

**Comment by dunglt91** [comment]
@tragiangdt hình như phải là tìm theo mã tiếp nhận mới đúng chứ Giang nhỉ

**Comment by dunglt91** [comment]
@tragiangdt  : cậu test trên dev đi nhé

**Comment by tragiangdt** [comment]
Trên dev chưa được nhé @dunglt91

**Comment by dunglt91** [comment]
@tragiangdt test nhe :dagger:

**Comment by tragiangdt** [comment]
trên opencps-dev ko tra cứu được theo mã số hồ sơ nhé

**Comment by Hongnt31** [comment]
trên opencps-dev test ok
