### ISSUE TITLE
Phiên bản giấy tờ của file đính kèm

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1088]
1. Cán bộ xóa file, thì số phiên bản giấy tờ cũng bị giảm
2. NLTT xóa file, số phiên bản giấy tờ bị giảm
3. Cán bộ xóa file đã trả về, đầu NLTT cũng ko thấy được file đó nữa

**Comment by khoahp** [comment]
@huymq chuyển lại cho e nhé

**Comment by huymq** [comment]
@thanhld2901 
Anh Thanh làm bug này hỏi anh @trungnt-ksnb nhé

**Comment by thanhld2901** [comment]
Phần này trao đổi với anh Trung, anh Trung báo đã thực hiện OK.
