### ISSUE TITLE
Chức năng gửi mail thông báo cho quản trị biết có tài khoản mới được tạo

### ISSUE THREAD

**Issue by huymq** [VietOpenCPS/opencps#1089]
@thanhld2901 
from @khoahp 

> Dear Thành,
> 
> Phần này em bổ xung thêm vào cấu hình portlet đăng ký tài khoản địa chỉ gửi email thông báo.
> 
> Thông tin cấu hình sẽ là danh sách email, nếu số nhiều thì phân tách email bằng đấu ';'.
> 
> Phần nội dung email sẽ lấy nội dung từ phần cấu hình của portal, thông tin cấu hình dạng template như các email thông báo tài khoản.

**Comment by thanhld2901** [comment]
Giải pháp thực hiện: 
Khi tài đăng ký tài khoản doanh nghiệp thực hiện gửi thông tin thông báo tới email quản trị
1. Cấu hình địa chỉ Email quản trị
        Trong chức năng cấu hình của chức năng đăng ký thêm 1 textbox cho phép nhập emal sau đó lưu lại. Có thể nhập được nhiều email theo dạng sau VD: email1@gmail.com;email2@gmail.com
2. Tại bước đăng ký tài khoản doanh nghiệp sau khi lưu và gửi thông tin xác nhận tài khoản thực hiện gửi email thông báo tới admin
       - Tạo mẫu đăng ký Email mới(Thực hiện trong hook. File portlet/portal_settings/email_notifications.jsp)
       - Thêm hàm gửi email thông báo tới quản trị trong class MessageBusUtil.java, sử dụng danh sách địa chỉ email đã cấu hình .
       - Tại hàm AccountRegPortlet.updateBusiness sau khi thực hiện cập nhật và gửi thông báo xác nhận cho tài khoản doanh nghiệp gọi hàm gửi email thông báo tới quản trị

**Comment by huymq** [comment]
@tragiangdt test lại giúp anh chức năng này nhé

**Comment by tragiangdt** [comment]
Em test trên qa vẫn còn lỗi:
1. Đăng ký tài khoản công dân, không gửi email về email quản trị (cấu hình đăng ký tài khoản công dân qua 3 bước) (Khi Doanh nghiệp đăng ý tài khoản, hệ thống đã gửi email về cho quản trị)
2. Em đề xuất là khi nào NLTT thực hiện xác nhận đăng ký thì hệ thống mới gửi email về cho quản trị. Hiện tại khi có tài khoản mới đăng ký thì hệ thống đã gửi thông báo email về cho quản trị rồi. Lúc này phải chờ đến khi NLTT thực hiện xác nhận đăng ký thì quản trị mới vào duyệt được tài khoản.

**Comment by tragiangdt** [comment]
@thanhld2901 
Em đã trao đổi với anh @huymq. Anh Thanh sửa lại theo quy trình là: 
1. Chỉ gửi email thông báo về cho quản trị khi cấu hình đăng ký tài khoản qua 3 bước
2. khi nào người đăng ký xác nhận đăng ký thì hệ thống mới gửi email thông báo cho quản trị.

**Comment by tragiangdt** [comment]
@thanhld2901 
Em cấu hình 3 email quản trị "A@gmail.com;B@gmail.com;C@gmail.com", hệ thống chỉ mới gửi email về cho email đầu và cuối (A và C) không gửi về cho mail ở giữa.

**Comment by tragiangdt** [comment]
@thanhld2901 Hệ thống đã gửi mail về cho 3 email ddc cấu hình, 1 email bị nhảy vào spam :D

**Comment by tragiangdt** [comment]
test done trên opencps-qa

**Comment by Hongnt31** [comment]
@khoahp  @tragiangdt 
Hiện tại trên qa-opencps sau khi đăng ký tài khoản thành công không gửi mail thông báo cho quản trị biết có tài khoản mới được tạo

**Comment by khoahp** [comment]
@huymq anh chuyển lại bug này cho nhân xử lý, @nhan0987 xử lý xong báo lại ngay cho @Hongnt31 issue này hoàn thành sớm nhé

**Comment by khoahp** [comment]
close do trùng issue #1159
