### ISSUE TITLE
Lỗi chức năng cấu hình dịch vụ công

### ISSUE THREAD

**Issue by duchung381991** [VietOpenCPS/opencps#1090]
Sau khi điền xong các trường rồi submit , nhận được thông báo lỗi hệ thống.

**Comment by huymq** [comment]
@NVP191 check lỗi này nhé

**Comment by khoahp** [comment]
@duchung381991 issue này em test trên con nào? 

@tragiangdt confirm lại issue này trên con QA nhé

**Comment by tragiangdt** [comment]
@khoahp  Trên qa vẫn thêm được dịch vụ công a. 
TH hệ thống thông báo lỗi hệ thống khi cấu hình dịch vụ công có thể là do nhập dữ liệu không đúng trong quá trình cấu hình anh ạ.

**Comment by khoahp** [comment]
@duchung381991 phần này trên môi trường QA không báo bug. Vậy có thể do trên môi trường test của bạn sảy ra lỗi, do vậy mình đóng bug này. 

Để khắc phục lỗi này bạn lên kênh trao đổi của cộng đồng nhé!
