### ISSUE TITLE
Quản lý thu phí - Giao diện sô lệch

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1095]
Cán bộ thu phí: ketoan.cps@gmail.com/cps12345 vào module quản lý thu phí, giao diện bị lỗi:

http://qa.opencps.vn/group/guest/quan-ly-thu-phi?p_p_id=22_WAR_opencpsportlet_INSTANCE_yBY5fWxXWLHD&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_22_WAR_opencpsportlet_INSTANCE_yBY5fWxXWLHD_mvcPath=%2Fhtml%2Fportlets%2Fpaymentmgt%2Fbackoffice%2Fbackofficepaymentdetail.jsp&_22_WAR_opencpsportlet_INSTANCE_yBY5fWxXWLHD_paymentFileId=201&_22_WAR_opencpsportlet_INSTANCE_yBY5fWxXWLHD_redirect=%2Fgroup%2Fguest

**Comment by huymq** [comment]
@dunglt91 hướng dẫn @hltn làm nhé

**Comment by binhth** [comment]
@hltn @dunglt91 : 
trong file: /html/portlets/paymentmgt/backoffice/backofficepaymentdetail.jsp 
giao diện bị lệch do:
- điều kiện check giá trị rỗng để hiển thị nội dung: "chưa có" đang bị check sai.
  chỗ này chỉ kiểm tra lại chỗ này, trong trường hợp viết lại cấu trúc html của phần này thì các dòng co dữ liệu nhiều > 2 dòng sẽ hiển thị ko theo UI thiết kế.

class sau thêm box-sizing như sau để border ko bị tràn.
.payment-ld .content .box50 > div, .payment-ld .content .box100 > div {
    box-sizing: border-box;
}

**Comment by huymq** [comment]
@binhth sửa lại bug này theo quy trình mới nhé
