### ISSUE TITLE
Giao diện tài khoản công dân và doanh nghiệp không có nút tạo hồ sơ

### ISSUE THREAD

**Issue by duchung381991** [VietOpenCPS/opencps#1101]
Khi đăng nhập bằng tài khoản công dân hoặc doanh nghiệp, giao diện quản lý hồ sơ của công dân và doanh nghiệp hiện ra nhưng không có nút Chuẩn bị hồ sơ trực tuyến, như trong bản demo trên demo.opencps.vn

**Comment by khoahp** [comment]
@tragiangdt check lại trên QA xem có gặp tình trạng này không nhé

**Comment by duchung381991** [comment]
Em dựng core 1.6 và theme Opencps-ux gặp phải lỗi trên

**Comment by tragiangdt** [comment]
@khoahp  Trên con demo hiển thị nút Chuẩn bị hồ sơ trực tuyến, trên qa thì hiển thị nút Lựa chọn thủ tục

**Comment by duchung381991** [comment]
![capture](https://cloud.githubusercontent.com/assets/14065616/19141401/5507f87c-8bbf-11e6-8492-e64b3ea79c04.PNG)
Giao diện em dụng lên không có ạ, không hề bị css nào đè lên

**Comment by khoahp** [comment]
@duchung381991 phần này xử lý được chưa nhỉ?

@tragiangdt xác nhận trên con QA còn lỗi này không? Nếu không có em close vào nhé
