### ISSUE TITLE
Đổi tên button "Đăng nhập ngay" thành "Đăng nhập" (New feature)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1102]
Phần đăng nhập tài khoản có button tên đăng nhập ngay
Kết quả mong muốn: Đổi tên cho Button "Đăng nhập ngay" thành "Đăng nhập"
![screenshot from 2016-10-05 14-32-50](https://cloud.githubusercontent.com/assets/17336814/19104812/c77e4210-8b08-11e6-8198-be1b0b50b261.png)

**Comment by khoahp** [comment]
Những issue kiểu ntn phụ thuộc vào từng đơn vị triển khai, họ sẽ tuỳ biến lại theo nhu cầu của từng đơn vị
