### ISSUE TITLE
Ẩn những phân nhóm hồ sơ có số hồ sơ =0

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#1107]
Tại màn hình quản lý hồ sơ phía NLTT
Những phân nhóm hồ sơ có số hồ sơ =0 thì ẩn đi. Khi nào có hồ sơ >0 mới hiển thị
![screenshot from 2016-10-06 14-04-25](https://cloud.githubusercontent.com/assets/17336814/19143394/d49183b6-8bcd-11e6-85e5-b0edaba66b2a.png)

**Comment by khoahp** [comment]
@binhth xử lý nhé, phần này phải làm cấu hình, 
- Show all 
  or 
- Don't show empty object
