### ISSUE TITLE
Không hiển thị những hồ sơ mà cán bộ ko phụ trách xử lý

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1108]
1. Trong role chuyên viên có cv1, cv2, cv3; 
2. Lãnh đạo phân công hồ sơ cho chuyên viên, chọn cv1
3. đăng nhập vào cv2, cv3 vẫn thấy hồ sơ của cv1 (hồ sơ này chỉ xem được ko thao tác được)
   Mong muốn: Không hiển thị những hồ sơ mà cán bộ ko phụ trách xử lý
   Lưu ý: TH cấu hình tại 1 bước có chọn role chỉ xem thì vẫn phải hiển thị hồ sơ.
   ![2016-10-06_142926](https://cloud.githubusercontent.com/assets/17695836/19143999/5a17edc4-8bd1-11e6-983f-62d04a702471.png)

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by Hongnt31** [comment]
Test done
