### ISSUE TITLE
Lỗi Hiển thị thành phần hồ sơ bị xô lệch

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1111]
1. Vào tk NLTT
2. Vào xem thành phần hồ sơ
3. Lỗi Hiển thị ô check trạng thái thành phần hồ sơ bị xô lệch
   KQMM: Icon group + ô check trạng thái hiển thị không bị xô lệch
   ![2016-10-06_170843](https://cloud.githubusercontent.com/assets/17695836/19148657/ffbdbc8e-8be7-11e6-9d9e-d5c4caa30439.png)

**Comment by huymq** [comment]
@tragiangdt test lại trên QA nhé

**Comment by tragiangdt** [comment]
test done trên qa
