### ISSUE TITLE
Lỗi không sinh phiên bản giấy tờ khi update form động

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1112]
1. Vào tk NLTT hoặc CBXL
2. Khai trực tuyến lần 1, click ghi lại -> số phiên bản giấy tờ hiển thị là 1
3. Vào sửa lại nội dung form động lần 2 (không thực hiện xóa file), click Ghi lại 
4. Lỗi: số phiên bản vẫn là 1, nội dung file hiển thị trên phiên bản là nội dung sửa lần 2; chưa xem lại được nội dung sửa lần 1

**Comment by huymq** [comment]
@tragiangdt test lại trên QA nhé

**Comment by tragiangdt** [comment]
test done trên qa
