### ISSUE TITLE
Thiếu thông tin ngày báo nộp, ngày xác nhận khi NLTT, nội dung xác nhận xem chi tiết phiếu yêu cầu thanh toán

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1116]
1. Vào menu Yêu cầu thanh toán của NLTT
2. Xem chi tiết phiếu
3. Lỗi: - Thừa thông tin trường Ngày yêu cầu
4. Thiếu thông tin ngày báo nộp, ngày xác nhận, nội dung xác nhận
   KQMM: Thiếu thông tin ngày báo nộp, ngày xác nhận hiển thị đầy đủ
   ![2016-10-11_113735](https://cloud.githubusercontent.com/assets/17695836/19258973/75efa530-8fa7-11e6-93c5-c3aed7023c30.png)

**Comment by huymq** [comment]
@tragiangdt test lại trên QA nhé

**Comment by tragiangdt** [comment]
Vẫn còn lỗi ạ

**Comment by tragiangdt** [comment]
1. Ngày báo nộp sai: khi NLTT mới nhận được phiếu yêu cầu thanh toán, khi xem chi tiết đã có thông tin trường ngày báo nộp (Ngày báo nộp có dữ liệu khi NLTT thực hiện báo nộp chuyển khoản)
2. Màn hình xem chi tiết phiếu yêu cầu thanh toán bị lệch Tên phí, lệ phí:
   ![2016-10-25_102814](https://cloud.githubusercontent.com/assets/17695836/19672070/cf6d5d86-9a9d-11e6-8c25-511f5b7cc548.png)
3. Ngày yêu cầu trên màn hình xác nhận báo nộp chưa có dữ liệu + Mấy nút Hợp lệ, Không hợp lệ, Đồng ý, ô nhập ý kiến bị dính vào nhau
   ![2016-10-25_102946](https://cloud.githubusercontent.com/assets/17695836/19672148/4f130d7e-9a9e-11e6-8823-27e6b21dfac6.png)
4. THông tin ngày xác nhận chưa có (trạng thái phiếu lúc nào đã là hoàn thành) 
   Nội dung xác nhận của cán bộ (khi đồng ý hợp lệ) chưa hiển thị
   ![2016-10-25_103350](https://cloud.githubusercontent.com/assets/17695836/19672214/c81b253a-9a9e-11e6-85c2-224fc9eb1636.png)

**Comment by Hongnt31** [comment]
@tragiangdt , @khoahp  Vẫn còn lỗi:
1. Ngày báo nộp sai: khi NLTT mới nhận được phiếu yêu cầu thanh toán, khi xem chi tiết đã có thông tin trường ngày báo nộp (Ngày báo nộp có dữ liệu khi NLTT thực hiện báo nộp chuyển khoản)
Lỗi 2,3,4 đang làm lại giao diện nên chưa test

**Comment by khoahp** [comment]
Chuyển lên 1.8, @huymq @binhth xử lý giúp

**Comment by tragiangdt** [comment]
test done trên qa
