### ISSUE TITLE
Lỗi ngày xử lý không hiển thị trên tab xử lý của phiếu xử lý

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1121]
1. Vào tài khoản lãnh đạo
2. xử lý 1 hồ sơ
3. Lỗi ngày xử lý không hiển thị trên tab xử lý của phiếu xử lý
   ![2016-10-12_112801](https://cloud.githubusercontent.com/assets/17695836/19297456/51903150-906f-11e6-8f08-3bf977b3d9df.png)

**Comment by khoahp** [comment]
@tragiangdt test loi nay nhe

**Comment by tragiangdt** [comment]
test done trên qa
