### ISSUE TITLE
Số tiếp nhận bị nhảy khi nhấn F5 load lại trang

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1125]
1. Vào tài khoản doanh nghiệp
2. Thực hiện nộp hs thủ tục Xác nhận đăng ký tổ chức hội chợ/triển lãm thương mại tại Việt Nam
3. Nhấn nút Gửi hồ sơ, hồ sơ đã sinh ra 1 số tiếp nhận
4. Nhấn F5, hệ thống lại sinh ra 1 số tiếp nhận khác cho hồ sơ này.
   KQMM: Khi nhấn F5 thì hệ thống ko thực hiện gửi lại hồ sơ vào hệ thống
   ![2016-10-13_101807](https://cloud.githubusercontent.com/assets/17695836/19335558/6541b3a8-912e-11e6-8ab6-154be8a5f6dc.png)

**Comment by khoahp** [comment]
@huymq nhé, phần này @dunglt91 sửa rồi đấy

**Comment by huymq** [comment]
@tragiangdt test lại lỗi này em nhé

**Comment by tragiangdt** [comment]
test done trên qa
