### ISSUE TITLE
Lỗi sửa thêm chức vụ cho cán bộ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1126]
1. Vào tài khoản quản trị
2. Vào Quản lý cán bộ -> vào tab Cán bộ
3. Vào Sửa cán bộ 1
4. Thêm chức vụ X hiện đang gán cho cán bộ 2 cho cán bộ 1
5. Lỗi: Chức vụ X của cán bộ 2 khi kiểm tra lại trong liferay bị mất trong khi không sửa đổi gì cả, trên giao diện Cập nhật thông tin tổ chức-Chức vụ của cán bộ 2 vẫn còn có chức vụ X)
   ![2016-10-13_102320](https://cloud.githubusercontent.com/assets/17695836/19335659/33979560-912f-11e6-92ca-94f97c43bb9d.png)
   Kiểm tra vai trò của tài khoản cán bộ 2 trong liferay, hiện mất role Đã kiểm tra
   ![2016-10-13_103501](https://cloud.githubusercontent.com/assets/17695836/19335858/c104dc86-9130-11e6-8fa2-50c25458169f.png)

**Comment by tragiangdt** [comment]
@huymq

**Comment by huymq** [comment]
@thanhld2901

**Comment by thanhld2901** [comment]
@Hongnt

**Comment by Hongnt31** [comment]
Test done
![image](https://cloud.githubusercontent.com/assets/20554327/19428406/33894b66-9474-11e6-84ad-737f4548a144.png)
![image](https://cloud.githubusercontent.com/assets/20554327/19428411/3a543dde-9474-11e6-8cbd-f2b5d877e01d.png)

**Comment by huymq** [comment]
@tragiangdt test lại lỗi này em nhé

**Comment by tragiangdt** [comment]
trên qa vẫn còn lỗi @huymq

**Comment by huymq** [comment]
@tragiangdt test lại trên QA nhé

**Comment by tragiangdt** [comment]
test done trên qa
