### ISSUE TITLE
Lỗi không load lại trang khi click nút Đồng ý trên popup xác nhận chuyển bước xử lý trên trình duyệt chrome

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1127]
1. Vào trình duyệt chrome
2. Vào tài khoản cán bộ xử lý -> Vào xử lý 1 hồ sơ 
3. Click vào các hành động xử lý, hệ thống hiển thị popup xác nhận chuyển bước xử lý
4. click Đồng ý
5. Lỗi: Hệ thống không load lại trang, vẫn giữ nguyên màn hình popup
   ![2016-10-13_104237](https://cloud.githubusercontent.com/assets/17695836/19335983/cff78436-9131-11e6-86bc-e84957c16948.png)

**Comment by tragiangdt** [comment]
@huymq

**Comment by huymq** [comment]
@tragiangdt test lại lỗi này trên QA nhé

**Comment by tragiangdt** [comment]
test done trên qa
