### ISSUE TITLE
Màn hình danh sách hồ sơ mới được xử lý không đúng thiết kế

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1130]
1. Vào tài khoản cán bộ -> menu Xử lý hồ sơ -> Hồ sơ mới được xử lý
2. Màn hình danh sách hồ sơ mới được xử lý không đúng thiết kế
   KQMM: Màn hình danh sách hồ sơ mới được xử lý hiển thị đúng thiết kế
   Link: http://qa.opencps.vn/group/guest/xu-ly-ho-so?p_p_id=16_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_16_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fprocessmgt%2Fprocessorder%2Fprocessorderjustfinishedlist.jsp&_16_WAR_opencpsportlet_tabs1=finished-processing

**Comment by huymq** [comment]
@tragiangdt 
Em post ảnh của màn hình hiện tại và màn hình mockup theo thiết kế nhé

**Comment by tragiangdt** [comment]
Em gửi mokup theo thiết kế:
https://raw.githubusercontent.com/VietOpenCPS/doc/master/SRS/processmgt/16processmgtprocessorderdonelist.png
Ảnh màn hình hiện tại:
![2016-10-18_161552](https://cloud.githubusercontent.com/assets/17695836/19471600/3227e2c0-954e-11e6-977c-8d689528d8ba.png)

**Comment by huymq** [comment]
@binhth issues này đã xong chưa nhỉ? Xong rồi thì comment báo @tragiangdt test lại nhé

**Comment by khoahp** [comment]
@huymq xem nếu chưa ổn để cho vào release 1.7 later nhé

**Comment by Hongnt31** [comment]
@tragiangdt  @khoahp @huymq 
Vẫn chưa đúng thiết kế
![image](https://cloud.githubusercontent.com/assets/20554327/20127597/10c13740-a673-11e6-94ba-1ea99f29dea0.png)

**Comment by khoahp** [comment]
@Hongnt31 những phần nào liên quan đến giao diện em test sau, hiện tại đang làm giao diện

**Comment by khoahp** [comment]
@Hongnt31 @tragiangdt @tanhtanhvn  giao diện đang rà soát làm lại theo bản thiết kế TCX, tạm thời close toàn bộ những issue liên quan đến thiết thế, sau đó rà soát tổng thê lại một lượt để tạo các issue mới nếu có.
