### ISSUE TITLE
Không đổi được mật khẩu tài khoản công dân, tổ chức

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1134]
Doanh nghiệp vào đổi mật khẩu, hệ thống báo lỗi com.liferay.portal.UserPasswordException 
![2016-10-14_164503](https://cloud.githubusercontent.com/assets/17695836/19383482/c04fee12-922e-11e6-93d1-eaae003ff648.png)

**Comment by huymq** [comment]
@tragiangdt test lại lỗi này trên QA của OpenCPS nhé

**Comment by tragiangdt** [comment]
1. Không thông báo đổi mật khẩu thành công hoặc không thành công. KQMM: Khi đổi mk thành công/không thành công thì có dòng thông báo cho NLTT
2. Không nhập đúng mật khẩu hiện tại nhưng vẫn đổi được mật khẩu
3. Chưa check thông tin "mật khẩu mới" và "nhập lại mật khẩu mới" đã trùng nhau chưa
4. Nhập "mật khẩu mới" và "nhập lại mật khẩu mới" không trùng nhau thì hệ thống vẫn đổi mk thành công (luôn lấy trường thông tin "nhập lại mật khẩu mới"

**Comment by khoahp** [comment]
@tragiangdt xem lại phần này em nhé

**Comment by Hongnt31** [comment]
@tragiangdt  @khoahp 
Vẫn còn các lỗi:
1. Không thông báo đổi mật khẩu thành công hoặc không thành công. KQMM: Khi đổi mk thành công/không thành công thì có dòng thông báo cho NLTT
2. Không nhập đúng mật khẩu hiện tại nhưng vẫn đổi được mật khẩu
3. Chưa check thông tin "mật khẩu mới" và "nhập lại mật khẩu mới" đã trùng nhau chưa
4. Nhập "mật khẩu mới" và "nhập lại mật khẩu mới" không trùng nhau thì hệ thống vẫn đổi mk thành công (luôn lấy trường thông tin "nhập lại mật khẩu mới"

**Comment by khoahp** [comment]
@huymq  phần này chuyển lên 1.8 nhé

**Comment by tragiangdt** [comment]
@khoahp hệ thống tự động điền mật khẩu vào ô "Mật khẩu hiện tại" là cps12345
Chỉ cần nhập mới và nhập lại mật khẩu là đổi được với những TH mk hiện tại là cps12345

**Comment by khoahp** [comment]
@nhan0987 xử lý gấp anh cái này nhé

**Comment by nhan0987** [comment]
Cái này do auto fill của browser tự điền. Closed.
