### ISSUE TITLE
[QT] - Cho phép bổ xung hồ sơ ở bước trong quy trình

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1137]
- Cho phép NLTT bổ xung ở bước bất kỳ trong quy trình, backend kiểm tra bổ xung hợp lệ, xử lý thông tin hồ sơ bổ xung, notification cho cán bộ xử lý

@vuhongson 

@tragiangdt

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi:
1. Chưa cấu hình được bước nào có thể bổ sung hồ sơ
2. Chưa hiển thị hành động bổ sung trên danh sách hồ sơ đầu NLTT
3. Chưa hightlight thành phần đã được bổ sung thêm dữ liệu mới

**Comment by khoahp** [comment]
closed do trùng với issues #1176
