### ISSUE TITLE
[QT] - Bổ xung trạng thái main, trạng thái sub trong cấu hình hồ sơ

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1139]
Bổ xung thêm trạng thái con của hồ sơ để hiển thị thêm thông tin trong bước xử lý của cán bộ

**Comment by khoahp** [comment]
@Hongnt31 test lỗi này nhé

**Comment by Hongnt31** [comment]
@khoahp 
1.Phần này hiện tại bên cái bộ phần quá trình xử lý không có trạng thái hồ sơ nên chưa test được,
![image](https://cloud.githubusercontent.com/assets/20554327/20417563/e4252784-ad78-11e6-9a84-59208ecbb879.png)

Còn bên phía cán bộ đã có hiển thị trạng thái con nhưng lại đang lấy mã danh mục chưa lấy tên
![image](https://cloud.githubusercontent.com/assets/20554327/20417670/a072a7c2-ad79-11e6-9b28-e8afad7cf985.png)

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi:
4. Không lưu vết trạng thái chính + trạng thái sub khi cập nhật bước trong quy trình

**Comment by khoahp** [comment]
@tragiangdt phần này xử lý trước 9/12 nhé

**Comment by tragiangdt** [comment]
test done trên qa
