### ISSUE TITLE
[QT] - Ký thành phần hồ sơ phía doanh nghiệp

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1141]
Bổ xung thêm ký thành phần hồ sơ phía doanh nghiệp

**Comment by khoahp** [comment]
@trungnt-ksnb comment vào phần ký số phần này nhé

**Comment by trungnt-ksnb** [comment]
Về mặt kỹ thuật đã thông. Tuy nhiên hiện tại các API của bên cung cấp đang giới hạn ký cho từng domain -> Cần làm việc giữ 2 bên để có cơ chế linh hoạt hơn

**Comment by khoahp** [comment]
Đã text trên hệ thống QA với dịch vụ ký số được cung cấp
