### ISSUE TITLE
[QT] - Bổ xung thêm chức năng tóm tắt hồ sơ tự đông

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1142]
@vuhongson với @tragiangdt bổ xung rõ thông tin hồ sơ nhé

**Comment by tragiangdt** [comment]
@khoahp  Em chưa rõ yêu cầu của issue này

**Comment by khoahp** [comment]
@tragiangdt anh đóng issue này do chưa rõ yêu cầu
