### ISSUE TITLE
[NF] - Chức năng notification

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1143]
- Ghi log mã notification
- Implement các chức năng gửi qua Email

Advance
- Gửi thông báo qua SMS
- Gửi thông báo qua API Restfull để notification cho các hệ thống tích hợp, hoặc cần thông tin

**Comment by huymq** [comment]
anh @thanhld2901 làm chức năng này nhé.
Tham khảo thiết kế và trao đổi với coreteam để làm rõ các công việc cần thực hiện (https://github.com/VietOpenCPS/doc/wiki/Ph%C3%A2n-t%C3%ADch-qu%E1%BA%A3n-l%C3%BD-th%C3%B4ng-b%C3%A1o)

**Comment by huymq** [comment]
@binhth hỗ trợ anh Thanh làm theo quy trình đóng góp cho coreteam mới nhé

**Comment by khoahp** [comment]
1.7.1 Hoàn thiện Inbox

**Comment by Hongnt31** [comment]
@khoahp  @nhan0987  
Khi cán bộ YCBS thì thì chức năng notification  thông báo thành 2 cái là thông báo YCBS và từ chối tiếp nhận
![image](https://cloud.githubusercontent.com/assets/20554327/20175536/d4c69150-a775-11e6-9c38-93bbdbc9b096.png)

**Comment by khoahp** [comment]
@nhan0987 em kiểm tra lại phần này nhé

**Comment by Hongnt31** [comment]
@khoahp  @nhan0987 còn phần thông báo khi NLTT thanh toán trực tuyến thì phải gửi thông báo đến kế toán thì chưa test được do chưa hoàn thiện thanh toán trực tuyến bằng VTC. Còn lại cơ bản các thông báo khác là ok

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi:
1. Thông báo đầu DN chưa việt hóa “You do not have any notifications.”
2. Nội dung thông báo nên cho thêm thông tin Mã tiếp nhận của hồ sơ
3. Với TH hồ sơ bị từ chối chưa thông báo cho DN (Hồ sơ bị từ chối tiếp nhận: mã 203)
4. Khi đánh dấu hồ sơ đã đọc thì hệ thống xóa hết danh sách thông báo. Yêu cầu: bỏ text bôi đậm giống thông báo của facebook
5. Chưa có thông báo trạng thái phiếu thanh toán hoàn thành cho NLTT (thiết kế chưa có)
6. Chưa có thông báo có kế toán với TH NLTT thanh toán trực tuyến

**Comment by nhan0987** [comment]
1,2,3,5,6  đã sửa xong.
4 yêu cầu dời sang 1.9, chưa có thời gian modifier notification portlet.

**Comment by khoahp** [comment]
@tragiangdt
Anh close issue này, các lỗi phát sinh cho vào issue mới
