### ISSUE TITLE
[UIUX] - Thêm tuỳ chọn on/off popup trên màn hình xử lý

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1150]
Bổ xung thêm cấu hình tuỳ chọn on/off popup trong cấu hình portlet xử lý hồ sơ

**Comment by tragiangdt** [comment]
@khoahp  Vẫn còn lỗi:
1. Giao diện off popup chưa tách vùng riêng
2. Giao diện khi hiển thị có mã tiếp nhận, ký số, yêu cầu thanh toán, ngày hẹn trả bị xô lệch
3. Click Đồng ý → hiển thị poup xác nhận hành động vừa thực hiện. Lỗi: trên popup chưa có hành động Hủy bỏ

**Comment by tragiangdt** [comment]
test done
