### ISSUE TITLE
[UIUX] - Menu lọc theo trạng thái phía NLTT

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#1151]

**Comment by khoahp** [comment]
Ẩn hiện trạng thái, cho vào cấu hình @huymq kiểm tra phần này chỗ @binhth nhé

**Comment by tragiangdt** [comment]
@khoahp  Vẫn còn lỗi:
1. Chọn cấu hình portlet hiển thị theo menu trạng thái:
DN Thêm hồ sơ → màn hình chọn lĩnh vực → Chọn lĩnh vực một lần nữa → màn hình hướng dẫn hồ sơ
Lỗi: thừa 1 bước chọn lĩnh vực
2. Tại màn hình sau khi đã chọn Lĩnh vực
Lỗi: - Lọc theo lĩnh vực đã disable nhưng click vào vẫn thấy danh sách lĩnh vực
- Vẫn tìm kiếm được hồ sơ ở lĩnh vực khác
- Chưa tìm kiếm theo tiêu chí Cơ quan thực hiện và từ khóa tìm kiếm

**Comment by tragiangdt** [comment]
@khoahp 
còn lỗi: 
Chọn cấu hình portlet hiển thị theo menu trạng thái:
DN Thêm hồ sơ → màn hình chọn lĩnh vực → Chọn lĩnh vực một lần nữa → màn hình hướng dẫn hồ sơ
Lỗi: thừa 1 bước chọn lĩnh vực

**Comment by khoahp** [comment]
@tragiangdt 
Anh close issue này, các lỗi phát sinh cho vào issue mới
