### ISSUE TITLE
[NF] - Thay đổi quy trình đăng ký tài khoản

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1159]
1. Yêu cầu:
   Quản trị có thể cấu hình: 
2. Cho phép đăng ký tài khoản công dân
3. Cho phép đăng ký tài khoản doanh nghiệp
4. Cấu hình dk tài khoản công dân qua 2 bước (không qua quản trị duyệt tài khoản), 3 bước (phải qua quản trị duyệt tài khoản)
5. Cấu hình dk tài khoản doanh nghiệp qua 2 bước (không qua quản trị duyệt tài khoản), 3 bước (phải qua quản trị duyệt tài khoản)
   Hệ thống gửi 2 email về cho CD, DN: Email xác nhận đăng ký và email thông báo tài khoản được duyệt + thông tin tài khoản với mật khẩu 
6. Quy trình đăng ký tài khoản:
   ![2index](https://cloud.githubusercontent.com/assets/17695836/19641917/195aa17e-9a0d-11e6-8ad2-486f9c5069db.jpg)

**Comment by tragiangdt** [comment]
@huymq

**Comment by huymq** [comment]
@thanhld2901

**Comment by tragiangdt** [comment]
Anh @thanhld2901 : vẫn còn một số lỗi
1. 1. Không chọn đăng ký tài khoản công dân/doanh nghiệp: thì khi nhập xong dữ liệu, nút Đăng ký ngay khong kích được
2. Hiện tại cấu hình dk tk DN/CB theo 2 bước -> Sửa cấu hình đăng ký thành 3 bước
NLTT vẫn giữ nguyên trang đang đăng ký -> thực hiện đăng ký tiếp -> Lỗi: hệ thống vẫn thực hiện ddk tài khoản theo 2 bước ban đầu (ko đổi bước đăng ký là 3 như cấu hình)
3. Tích chọn đăng ký tài khoản công dân, doanh nghiệp: tại màn hình đăng ký không chuyển được sang đăng ký Doanh nghiệp
-> Chỉ mới test được TH đăng ký tài khoản công dân

**Comment by thanhld2901** [comment]
@tragiangdt: Phần này được rồi Giang nhé.
Chỉ có bug số 2 thì trường hợp đó rất hãn hữu xảy ra. Hơn nữa mình cấu hình xong xuôi mói thực hiện chạy, nên anh thấy là không cần thiết.
@khoahp: Anh Khoa xem cho em phần số 2 như Giang nói thì có cần phải sửa không ạ.

**Comment by tragiangdt** [comment]
Lỗi 3: ok
1. ok

**Comment by khoahp** [comment]
@tragiangdt phần này được chưa em ơi

**Comment by Hongnt31** [comment]
@tragiangdt  @khoahp 
1. Chọn "Đăng ký"
KQ: Không thấy có màn hình đăng ký tài khoản
![image](https://cloud.githubusercontent.com/assets/20554327/20127397/f8bed294-a670-11e6-9547-4e1053691921.png)

**Comment by khoahp** [comment]
@Hongnt31 phần này em cấu hình tuỳ chọn cho đăng ký tài khoản nhé, portlet này chưa cấu hình.

@tragiangdt hỗ trợ bạn cấu hình nhé

**Comment by khoahp** [comment]
@huymq anh chuyển lại bug này cho nhân xử lý, @nhan0987 xử lý xong báo lại ngay cho @Hongnt31 issue này hoàn thành sớm nhé

**Comment by nhan0987** [comment]
@Hongnt31 : Mail thông báo cho quản trị vẫn gửi được nhé, Hồng config sai mail, phucnc@fds.vn;hongnt@fds;nhanlt@fds.vn --> phucnv@fds.vn;hongnt@fds.vn;nhanhlt@fds.vn

**Comment by khoahp** [comment]
@Hongnt31 làm việc gì cẩn thận chút em ơi, ntn làm ảnh hưởng đến công việc của bao nhiêu người khác

**Comment by khoahp** [comment]
@Hongnt31 test lại lần nữa để đóng bug nhé

**Comment by Hongnt31** [comment]
@khoahp  Test done
