### ISSUE TITLE
Trạng thái phiếu yêu cầu thanh toán ở portlet Yêu cầu thanh toán và Quản lý thu phí sai

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1161]
1. Trạng thái phiếu yêu cầu thanh toán phải là (1. Chờ nộp, 2. Đã báo nộp, 3. Hoàn thành, 4. Không hợp lệ)
2. Lỗi: khi NLTT thực hiện chuyển khoản, trạng thái phiếu chuyển thành "Đã xác nhận" trên danh sách + xem chi tiết phiếu + màn hình xác nhận của QUản lý thu phí + Yêu cầu thanh toán
   KQMM: chuyển thành trạng thái Đã báo nộp
   Màn hình xem thông tin thanh toán không bị xô lệch
   ![2016-10-25_102315](https://cloud.githubusercontent.com/assets/17695836/19672015/5b7b217e-9a9d-11e6-8008-4fc62feab094.png)
   ![2016-10-25_102336](https://cloud.githubusercontent.com/assets/17695836/19672016/5bfe89e2-9a9d-11e6-9b42-f02fbd16a527.png)
   ![2016-10-25_102413](https://cloud.githubusercontent.com/assets/17695836/19672018/5da46226-9a9d-11e6-95ef-e069f5738518.png)

**Comment by khoahp** [comment]
@tragiangdt em xác nhận cho anh phần này, nếu chưa được thì cho lên bản sau nhé

**Comment by Hongnt31** [comment]
@tragiangdt  @khoahp 
Vẫn còn lỗi
![image](https://cloud.githubusercontent.com/assets/20554327/20127346/4657188c-a670-11e6-860a-888c47b8fa52.png)

**Comment by tragiangdt** [comment]
test done trên qa
