### ISSUE TITLE
[Hotfix] NLTT không nhận được giấy tờ kết quả

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1162]
1. NLTT vào xem hồ sơ tại bước đã cấu hình trả về giấy tờ kết quả
2. Lỗi: NLTT không xem được giấy tờ kết quả trên tab Kết quả

**Comment by khoahp** [comment]
@tragiangdt a xử lý lỗi này sớm nhé, trong ngày mai

**Comment by khoahp** [comment]
@tragiangdt phần này được chưa em ơi

**Comment by Hongnt31** [comment]
@tragiangdt @khoahp  Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20127289/a1f819d0-a66f-11e6-9e17-b05f9f125c36.png)
