### ISSUE TITLE
Lỗi hiển thị người có vai trò chỉ xem trên list Phân công người xử lý bước sau

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1165]
1. Vào tài khoản quản trị
2. Vào cấu hình quy trình, thêm 1 vai trò chỉ xem khi cấu hình bước xử lý
   ![2016-10-26_115518](https://cloud.githubusercontent.com/assets/17695836/19713816/57e004ea-9b73-11e6-98e0-8f95c36a8037.png)
3. Vào cấu hình hành động
   Lỗi: Trên list phân công người xử lý có cả cán bộ thuộc vai trò chỉ xem
   ![2016-10-26_115641](https://cloud.githubusercontent.com/assets/17695836/19713827/8d87dece-9b73-11e6-9753-4a8402275bbd.png)

**Comment by khoahp** [comment]
@tragiangdt xem lại phần này nhé

**Comment by Hongnt31** [comment]
@khoahp  Test done
