### ISSUE TITLE
Chưa hiển thị Ghi chú trên Lịch sử xử lý khi tra cứu hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1166]
1. Vào tài khoản cán  bộ
2. Vào Tra cứu hồ sơ
   Lỗi:  Chưa hiển thị Ghi chú trên Lịch sử xử lý khi tra cứu hồ sơ
   KQMM: hiển thị lịch sử xử lý hồ sơ như lịch sử ở phiếu xử lý hồ sơ 
   ![2016-10-27_085025](https://cloud.githubusercontent.com/assets/17695836/19751871/d924232e-9c22-11e6-956b-10acc30a7848.png)

**Comment by Hongnt31** [comment]
@khoahp  Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20177264/780e053e-a77e-11e6-860e-fca81c7d679d.png)
