### ISSUE TITLE
[Hotfix] Thêm chức năng cấu hình chỉ xem giấy tờ kết quả tại bước xử lý

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1167]
1. Vào tài khoản quản trị
2. TRên màn hình cập nhật bước xử lý,
   YC: Thêm chức năng cấu hình chỉ xem giấy tờ kết quả tại bước xử lý
   https://raw.githubusercontent.com/VietOpenCPS/doc/master/SRS/processmgt/15processmgtprocessstepedit.png

**Comment by tragiangdt** [comment]
@huymq

**Comment by Hongnt31** [comment]
Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20177181/01be69d2-a77e-11e6-8201-34bd7778b610.png)
