### ISSUE TITLE
[NF] Thêm điều kiện hồ sơ đang bị qúa hạn xử lý n ngày

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1168]
Mô tả:
Thời hạn xử lý của thủ tục là n ngày
Qúa n ngày, cán bộ chưa xử lý xong
KQMM: Hệ thống kiểm tra điều kiện "delay [n]" (hồ sơ đang bị qúa hạn xử lý n ngày) và tự động chuyển sang bước khác theo cấu hình

**Comment by khoahp** [comment]
@tragiangdt anh close do trùng issue #1178

**Comment by tragiangdt** [comment]
sao issue này lại close vậy anh Khoa @khoahp 
2 issue này là khác nhau mà: 2 điều kiện check khác nhau: (delay [n]: hồ sơ đang bị qúa hạn xử lý n ngày và waiting [n]: hồ sơ đang chờ bổ sung qúa n ngày )
Anh Tuấn Anh mới bổ sung vào thiết kế ạ:

preCondition: chuỗi điều kiện kiểm tra để thao tác có thể thực hiện. Có thể đưa ra nhiều điều kiện được phân cách nhau bởi dấu ,. Các nút thao tác manual trên giao diện chỉ hiển thị khi điều kiện là trắng hoặc được thỏa mã.

```
payok: các yêu cầu phiếu thanh toán đã được xác nhận nộp đầy đủ bởi kế toán
tag [label]: kiểm tra hồ sơ được đánh tag với giá trị label
cancel: có yêu cầu rút hồ sơ đang trong quá trình xử lý
service [id]: kiểm tra id của thủ tục hành chính
onegate: hồ sơ được tiếp nhận tại bộ phận một cửa
online: hồ sơ được tiếp nhận trực tuyến
delay [n]: hồ sơ đang bị qúa hạn xử lý n ngày
waiting [n]: hồ sơ đang chờ bổ sung qúa n ngày
```
