### ISSUE TITLE
[NF] Lấy giá trị (số hiệu giấy tờ và ngày văn bản) từ form động điền vào dossierFileNo và dossierFileDate

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1169]
1. Cấu hình biến trên form động:
   Số hiệu giấy tờ: dossierFileNo
   Ngày văn bản: dossierFileDate
2. Khi thực hiện nhấn nút Ghi lại trên form khai trực tuyến, hệ thống tự động lưu 2 giá trị dossierFileNo và dossierFileDate vào trong bảng dossierfile
   @binhth

**Comment by tanhtanhvn** [comment]
Cách làm giống như các trường thông tin khác khi điền trong mẫu json của form nhé

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi:
Chưa lấy được số hiệu giấy tờ và ngày văn bản từ form động

**Comment by khoahp** [comment]
@trungnt-ksnb nhận lại nhé

**Comment by trungnt-ksnb** [comment]
@khoahp 
Đã xử lý, sẽ cập nhật trong bản 1.8

**Comment by khoahp** [comment]
@Hongnt31 done nhé
