### ISSUE TITLE
[NF] Thêm tiện ích sinh số tự động cho giấy tờ kết quả

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1173]
Anh Tuấn Anh đã bổ sung thiết kế thêm 1 trường dossierFileNoPattern trong thiết kế
Cấu hình sinh số cho giấy tờ kết quả tại Màn hình cập nhật thông tin một thao tác xử lý

**Comment by khoahp** [comment]
@Hongnt31 done nhé
