### ISSUE TITLE
[NF] Xuất báo cáo ra file word (chuyên viên có thể chỉnh sửa lại file này)

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1175]
Xuất báo cáo ra file word (chuyên viên có thể chỉnh sửa lại file này)

**Comment by khoahp** [comment]
@tragiangdt cụ thể nội dung báo cáo nhé

**Comment by khoahp** [comment]
@trungnt-ksnb nhận cái này nhé

**Comment by Hongnt31** [comment]
done

**Comment by khoahp** [comment]
@Hongnt31 okie em
