### ISSUE TITLE
Lỗi search chuyển sang thủ tục thì nó mất text đã nhập trên ô search

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1184]
1. Vào trau cứu hồ sơ và thủ tục, portlet19
2. Nhập text để tra cứu, 
3. Chọn tra cứu theo thủ tục hành chính
4. Lỗi: text đã nhập bị mất
KQMM: nhập thông tin search rồi, khi chuyển sang tra cứu theo thủ tục thì không bị mất nội dung đã nhập

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi anh ạ
![2017-03-30_174650](https://cloud.githubusercontent.com/assets/17695836/24500753/e18c6a2c-1570-11e7-89a4-8c1ca6106c71.png)

**Comment by khoahp** [comment]
@tragiangdt phần này do bị giới hạn bởi sử dụng tablib liferay nên khi chuyển mục chọn (thực chất là chuyển Tab) nên chưa xử lý ngay được.

Anh tạm thời để như vậy vào closed bug này, chức năng adv của mục tìm kiếm sẽ thực hiện ở phiên bản sau.
