### ISSUE TITLE
Thêm chức năng search theo mã số hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1185]
1.Vào trau cứu hồ sơ và thủ tục, portlet19
2. Nhập mã số hồ sơ để tra cứu
3. Chọn tra cứu theo hồ sơ
4. Lỗi: không tra cứu theo được mã số hồ sơ
KQMM: - tra cứu theo mã số hồ sơ được

**Comment by khoahp** [comment]
@tragiangdt phần này đã tra cứ được theo mã hồ sơ

**Comment by tragiangdt** [comment]
test done trên qa
