### ISSUE TITLE
Lỗi khi ô nhập nội dung tìm kiếm null nhưng vẫn cho ra kết quả

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1186]
1. Vào trau cứu hồ sơ và thủ tục, portlet19
2. Click vào tìm kiếm (không nhập nội dung gì)
3. Lỗi: Vẫn hiển thị kết quả tra cứu hồ sơ chưa có mã tiếp nhận
KQMM: - khi không nhập gì thì không cho hiển thị kết quả
- Không có kết quả tìm kiếm thì thoong báo cho người tra cứu biết

**Comment by khoahp** [comment]
Chuyển lại bug này cho @huymq nhé, phần này trước @binhth xử lý

**Comment by khoahp** [comment]
@tragiangdt phần này anh đã xử lý nhé

**Comment by tragiangdt** [comment]
test done trên qa
