### ISSUE TITLE
Validate bắt buộc giấy tờ kết quả tại 1 hành động

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#1211]
1. Khi Cấu hình bắt buộc một Kết qủa trả về tại một hành động (Yêu cầu bổ sung)
2. Bước sau(chờ bổ sung) của hành động phần Xử lý giấy tờ kết quả không cấu hình Giấy tờ bắt buộc đó
3. Khi Cán bộ không tải giấy tờ lên mà vẫn thực hiện hành động đó 
KQ: Không thông báo validate
4, Khi TH tại một hành động cấu hình 2 Kết qủa trả về chỉ 1 kết quả bắt buộc
5. Khi thực hiện hành động 
KQ: Lai báo lỗi validate cả giấy tờ không bắt buộc

**Comment by Hongnt31** [comment]
@khoahp 
Khi Cấu hình bắt buộc một Kết qủa trả về tại một hành động (Yêu cầu bổ sung)
Bước sau(chờ bổ sung) của hành động phần Xử lý giấy tờ kết quả không cấu hình Giấy tờ bắt buộc đó
Khi Cán bộ không tải giấy tờ lên mà vẫn thực hiện hành động đó
KQ: Đã thông báo validate 
![image](https://cloud.githubusercontent.com/assets/20554327/24536308/c12d47cc-1603-11e7-86c7-26eb0784c524.png)
nhưng chưa tô đỏ giấy tờ bắt buộc
![image](https://cloud.githubusercontent.com/assets/20554327/24536313/c9fa5642-1603-11e7-9b2b-7d0ceef8a4e8.png)

**Comment by khoahp** [comment]
@Hongnt31 phần hiển thị em tạo bug khác nhé

**Comment by Hongnt31** [comment]
Done
