### ISSUE TITLE
Thêm kiểu hiển thị cho phiếu xử lý hồ sơ

### ISSUE THREAD

**Issue by trungnt-ksnb** [VietOpenCPS/opencps#1212]
Khi chọn hồ sơ trên danh sách -> vào luôn Nội dung hồ sơ. Không để thành 4 menu mà gộp chung vào 1 giao diện luôn. Cán bộ đọc xong xử lý luôn. Nếu được thì hiển thị luôn đơn trên web cho cán bộ đọc

**Comment by Hongnt31** [comment]
@trungnt-ksnb  a note cách cấu hình thêm kiểu hiển thị mới cho phiếu xử lý hồ sơ vào đấy hoặc lên github để không bị trôi mất thông tin anh nhá

**Comment by khoahp** [comment]
@Hongnt31 phần này dùng tài khoản quản trị vào portlet quản lý hồ sơ, chọn cách hiển thị nhé

về phần lỗi thì đã done nhé
