### ISSUE TITLE
Kiểm tra phải nhập ý kiến mới cho chuyển bước

### ISSUE THREAD

**Issue by trungnt-ksnb** [VietOpenCPS/opencps#1214]
Cần kiểm tra, phải có ý kiến mới được chuyển bước

**Comment by Hongnt31** [comment]
Chưa việt hóa thông báo
![image](https://cloud.githubusercontent.com/assets/20554327/24535351/b3cc4386-15fd-11e7-9442-428237d70553.png)

**Comment by khoahp** [comment]
@Hongnt31 anh đã xử lý, em kiểm tra lại nhé

**Comment by Hongnt31** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/20554327/24535572/26d205a4-15ff-11e7-9f1c-229ff0cb2e9d.png)
