### ISSUE TITLE
Lỗi không hiển thị hết tên doanh nghiệp khi gửi email thông báo có tài khoản đăng ký với tên quá dài

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#1218]
1. Doanh nghiệp đăng ký tài khoản với tên rất dài. VD: Chi nhánh công ty TNHH MTV thiết bị nặng ONEASIA - Nhà máy sản xuất lắp ráp mô tô xe máy Pháp 
2. Doanh nghiệp xác nhận đăng ký tài khoản
3. Hệ thống gửi thông báo có tài khoản mới đăng ký về cho email quản trị theo cấu hình
Lỗi: không hiển thị được hết tên doanh nghiệp trong nội dung email
"Thông tin đăng ký:
     **Tên đăng ký: C**
     Email: xxx
     Số điện thoại: 06128xxx"

**Comment by Hongnt31** [comment]
Hiện tại k tạo đk TK Dn

**Comment by nhan0987** [comment]
với vụ tên đăng ký này
 có 2 hướng xử lý
 1 là giới hạn ký tự là 75
 vì khi tạo trên 1 hệ thống mới thì trường Name nó sẽ default là 75
 + thêm 1 cái valid nữa
[2:46:33 PM] Nguyen:
a tăng thêm đi
 issue y/c tăng đó a
[2:46:55 PM] Nhan:
nếu làm thế này thì doanh nghiệp sẽ ko đăng ký được với tên quá dài như vậy
 còn nếu ko cần valid
 thích đăng kí lưu tên dài bao nhiêu cũng được
 thì chỉ cần sửa db
 và lưu ý yêu cầu sửa trên các hệ thống khác
 chứ ko mỗi khi chuyển hệ thống lại báo 1 cái issues này thì chết

**Comment by nhan0987** [comment]
với cái name này thì có 2 trường name ở bảng citizen và business.

Các anh cho hướng giải quyết. Sửa code hay sửa db.

**Comment by khoahp** [comment]
Sửa DB nhé

**Comment by Hongnt31** [comment]
@nhan0987 , @khoahp  trên form đăng ký trường Tên Doanh nghiệp không cho nhập quá 75 ký tự.
Yêu cầu: cho phép nhập 255 ký tự
