### ISSUE TITLE
Lỗi không lưu được thành phần hồ sơ con lớn hơn 10

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#1225]
1.Ví dụ thành phần hồ sơ con có Số thứ tự sắp xếp thành phần là 2.13 thì sẽ hiển thị trên màn hình thành 2.1
2. Đối với thành phần hồ sơ con cấp 3 ví dụ 2.2.1 không lưu được

**Comment by khoahp** [comment]
@trungnt-ksnb cập nhật phần này trong tuần nhé

**Comment by Hongnt31** [comment]
Done
