### ISSUE TITLE
Compile from source error because of not-correct libs

### ISSUE THREAD

**Issue by hieulq** [VietOpenCPS/opencps#1235]
We build and compile source code that have dependency on opencps-portlet-service.jar lib. This lib can be downloaded from opencps sourceforce or dropbox. Thus, this is not convenient for us at all because of:
- Wrong version of lib that can cause compile fail. See example: https://travis-ci.org/hieulq/opencps/builds/186909505 (branch rc1.8 unit test with latest lib downloaded from sourceforce/dropbox)
- Inconvenient for developer experience.

Please rearrange the lib or always update the latest in github/sourceforce/dropbox. IMO, we should only use github, that's enough for us.

**Comment by khoahp** [comment]
@hieulq 

Phần này như @khoahp và @tuhoanganh cùng @hieulq đã làm, anh em đã build được ứng dụng với example unit-test thông qua Travis. Nên mình close issue này nhé.

Về tiến độ phát triển các unit-test và intergrate test vẫn chưa thế khới động được, do nguồn lực còn hạn chế của cộng đồng.

**Comment by hieulq** [comment]
@khoahp ok anh
