### ISSUE TITLE
Lỗi phân trang màn hình Quản lý cán bộ

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#1239]
1. Đăng nhập TK admin
2. Chọn Quản lý cán bộ
3. Chọn phân trạng
KQ: Bị lỗi
![image](https://cloud.githubusercontent.com/assets/20554327/21513132/c1686e70-cce7-11e6-98ac-829cc43e8aad.png)

**Comment by khoahp** [comment]
@Hongnt31 
Em test lại trên con QA của OpenCPS rồi báo bug nhé!
@vuhongson em đóng bug này

**Comment by hoanganhkg0003** [comment]
cho mình hỏi làm sao để tìm dc tài khoản quản trị ạ
