### ISSUE TITLE
Yêu cầu hạn xử lý tại từng bước hiển thị "Quá .... ngày .... giờ" / "Còn ... ngày... giờ"

### ISSUE THREAD

**Issue by trungnt-ksnb** [VietOpenCPS/opencps#1252]
1. Vào tài khoản cán bộ
2. Vào danh sách hồ sơ chờ xử lý Yêu cầu: - hạn xử lý tại từng bước hiển thị "Quá .... ngày .... giờ" / "Còn ... ngày... giờ"
3. Ngày tính theo ngày làm việc, tiếng tính theo số giờ làm việc trong ngày (1 ngày có 8 giờ)

![2017-01-18_092715](https://cloud.githubusercontent.com/assets/17334393/23288176/811b3c7a-fa74-11e6-8249-cdb4526a8cc7.png)

**Comment by khoahp** [comment]
@nhan0987 xử lý luôn phần này nhé

**Comment by nhan0987** [comment]
Đã xử lý xong

**Comment by Hongnt31** [comment]
@nhan0987  @khoahp 
Vẫn chưa:
- Vào danh sách hồ sơ chờ xử lý Yêu cầu: - hạn xử lý tại từng bước hiển thị "Quá .... ngày .... giờ" / "Còn ... ngày... giờ"
- Ngày tính theo ngày làm việc, tiếng tính theo số giờ làm việc trong ngày (1 ngày có 8 giờ)
![image](https://cloud.githubusercontent.com/assets/20554327/24536867/d6f75a8a-1607-11e7-9ff9-12d802939ade.png)

**Comment by nhan0987** [comment]
1.Ý là muốn hiển thị kiểu : "Quá 1 ngày 13 giờ" ?
2. Yêu cầu này ko làm được.
