### ISSUE TITLE
Hồ sơ bị quá hạn bổ sung khi y/c bổ sung nhiều lần

### ISSUE THREAD

**Issue by trungnt-ksnb** [VietOpenCPS/opencps#1254]
Tại bước "Hồ sơ chờ Chuyên viên kiểm tra tính hợp lệ của hồ sơ". Chuyên viên thao tác "yêu cầu bổ sung", doanh nghiệp gửi lại hồ sơ thì Hồ sơ bị biến thành "Hồ sơ quá hạn bổ sung". Y/C bổ sung 3 hoặc 4 lần

**Comment by trungnt-ksnb** [comment]
http://hanoi.fds.vn:9999/opencps/mt-frontoffice/issues/73

**Comment by khoahp** [comment]
@nhan0987 em xem cái này gấp nhé.

**Comment by nhan0987** [comment]
Kiểm tra lại trên source code core với 1 quy trình chạy thật của đường thuỷ nội  ko thấy xảy ra lỗi này, nhiều khả năng cấu hình sai trên dự án moit. Đề nghị kiểm tra lại.

**Comment by Hongnt31** [comment]
Done
Đã thử YCBS 4 lần không thấy lỗi
thủ tục Xác nhận đăng ký thực hiện khuyến mại theo hình thức mang tính may rủi thực hiện trên địa bàn từ 2 tỉnh, thành phố trực thuộc Trung ương trở lên hoặc theo quy định tại Điều 17 NĐ số 37/2006/NĐ-CP
