### ISSUE TITLE
Cán bộ Tìm kiếm giấy tờ bị Lỗi

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#1262]
1. Đăng nhập TK cán bộ <br\>
2. Vào Tra cứu \ Giấy tờ <br\>
TH1: <br\>
- (1) Tích chọn Chỉ xem giấy tờ kết quả <br\>
- (2) Nhấn tìm kiếm <br\>
![image](https://cloud.githubusercontent.com/assets/20554327/24535747/4084abb8-1600-11e7-8513-3b7459707fe4.png)
KQ: Xuất hiện thông báo  " Dossier BackOffice Management tạm thời không có"
![image](https://cloud.githubusercontent.com/assets/20554327/24535783/7d0f0bf0-1600-11e7-9e5e-b8129a968f1d.png)
 
TH2: <br\>
- Bỏ phần khoanh ô vuông
![image](https://cloud.githubusercontent.com/assets/20554327/24535903/38bdfc76-1601-11e7-9781-5598975aa6a5.png)

**Comment by khoahp** [comment]
@Hongnt31 xem kiem tra lai nha, anh da sua

**Comment by Hongnt31** [comment]
@khoahp 
Lỗi 1 done, Lỗi số 2 vẫn còn
![image](https://cloud.githubusercontent.com/assets/20554327/24536652/0265512e-1606-11e7-8545-79b3f8cfff06.png)

**Comment by khoahp** [comment]
@Hongnt31 phần này em kiểm tra lại giúp anh nhé

**Comment by Hongnt31** [comment]
@khoahp  vẫn còn lỗi
![image](https://cloud.githubusercontent.com/assets/20554327/24606459/59d822fe-1897-11e7-8997-ddcf3015b88c.png)

**Comment by khoahp** [comment]
@Hongnt31 phần này do cấu hình phân quyền tài khoản cán bộ em nhé, nếu bỏ quyền đi như trên con demo.opencps.vn sẽ hết nhé
