### ISSUE TITLE
[ 20160314] Trùng form nhập Item Code (Required)

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#16]
Phần Frontend Admin: Khi thêm mới DictItem trùng form nhập Item Code 
![screenshot from 2016-03-14 17-14-07](https://cloud.githubusercontent.com/assets/17336814/13741325/38b4e936-ea08-11e5-818a-539c1f7ef86e.png)

**Comment by trungnt-ksnb** [comment]
Đã fix xong
