### ISSUE TITLE
Đăng ký tài khoản, phần Tỉnh/Thành phố thiếu Thành phố Hà Nội

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#198]
- Vào Trang chủ OpenCPS
- Chọn Đăng ký
- Nhập thông tin đăng ký
- Trong phần Tỉnh/Thành phố không có Thành phố Hà Nội
  --> Thêm Thành phố Hà Nội trong danh mục Tỉnh/Thành phố

**Comment by khoahp** [comment]
@vuminhcuong 

Ngoài TP Hà Nội ra còn thiếu các thành phố nào khác không? Mình đang sợ danh mục này chưa chuẩn.

Mình sẽ cung cấp mẫu dữ liệu và quy tắc sinh dữ liệu để BA làm master data theo mẫu dữ liệu chuẩn của BA.

**Comment by khoahp** [comment]
@vuminhcuong 

Đã bổ xung thêm, nhóm TEST, test lại các chức năng.
