### ISSUE TITLE
Danh sách Tỉnh/Tp, Quận/Huyện, Xã/Phường chưa sắp xếp hợp lý

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#199]
Danh sách Tỉnh/Tp, Quận/Huyện, Xã/Phường chưa sắp xếp hợp lý. Nên xếp theo ABC, nhưng đừng để Quận 12 lên trên Quận 2

**Comment by khoahp** [comment]
- Nếu sắp xếp theo anphabe, thì quận 12 lên trên quận 2 là đúng theo cách sắp sếp khi so sanh chuỗi String.
