### ISSUE TITLE
[20160314] - Phần tìm kiếm Dict Collection thêm trường All 

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#20]
Chọn tab Data Mangament hiển thị toàn bộ các DictItem
![screenshot from 2016-03-14 17-47-00](https://cloud.githubusercontent.com/assets/17336814/13742158/e27474ba-ea0c-11e5-9946-7675e6abb070.png)

**Comment by trungnt-ksnb** [comment]
Phần này không nên tìm all. Lý do là các dict collection thuộc các phạm trù khác nhau nên không lên trộn lẫn kết quả tìm kiếm vào 1
