### ISSUE TITLE
Tài khoản dùng thử: congdan.cps@gmail.com không đăng nhập được

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#200]
Tài khoản dùng thử: congdan.cps@gmail.com không đăng nhập được

**Comment by vuminhcuong** [comment]
Đã cập nhật lại thông tin tài khoản: congdan.cps@gmail.com --> Hiện tại đã đăng nhập bình thường

**Comment by tanhtanhvn** [comment]
Nếu test đã kiểm tra lại OK thì phải close nó lại.
