### ISSUE TITLE
Menu danh sách cơ quan thiếu thông tin số lượng thủ tục

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#201]
Khi tra cứu thủ tục hành chính, menu danh sách cơ quan chưa có số lượng thủ tục. Cải tiến giao diện hiển thị số lượng bằng icon số lượng sắp xếp bên phải.

**Comment by khoahp** [comment]
@dunglt91 

Dung fix lỗi này nhé, cụ thể màn hình anh bổ xung theo link bên dưới.

http://qa.opencps.vn/thu-tuc-hanh-chinh

**Comment by dunglt91** [comment]
cơ quan quản lý và lĩnh vực thủ tục bị ngược nhau

**Comment by khoahp** [comment]
@tanhtanhvn 

Hiện tại lỗi đã được xử lý và deploy lên trên QA tại địa chỉ http://qa.opencps.vn/thu-tuc-hanh-chinh

@tragiangdt test lại giúp anh nhé

**Comment by tragiangdt** [comment]
Đã test ok
