### ISSUE TITLE
Lập trình Portlet 19 theo giao diện thiết kế mới

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#203]
Giao diện mới cho phép người dùng guest tìm kiếm thông tin trên trang chủ một cách thuận tiện và nhanh chóng.

**Comment by khoahp** [comment]
@tanhtanhvn @tragiangdt

Giang test lại module này rồi closed vào nhé

**Comment by tanhtanhvn** [comment]
Hiện nay vẫn chưa tìm kiếm được theo từ khóa. Trung đã lập trình phần tìm kiếm theo lucence chưa?

**Comment by dangkhanhtrung** [comment]
Em đã lập tình tìm kiếm theo lucene rồi. Có bug là có trường trong bản ghi bị null thì việc đánh chỉ mục cho bản ghi đó có vấn đề. Cho nên chỉ có một số bản ghi được đánh chỉ mục để tìm kiếm mà không phải tất cả.

**Comment by tanhtanhvn** [comment]
Ví dụ tìm kiếm hồ sơ là index theo trường nào? Cần index ít nhất được tên chủ hồ sơ, tên thủ tuc. Hiện nay tìm kiếm theo cả 2 cái này đều không được. Nếu index không chấp nhận trường null thì nó có chấp nhận trường có sâu rỗng không kí tự? Tại sao khi index không làm concat một chuỗi từ hồ sơ xong rồi index theo chuỗi mà mình concat được?

**Comment by dunglt91** [comment]
@tragiangdt test lai nhe
@khoahp
