### ISSUE TITLE
Portlet 20 quản lý thanh toán cho công dân và tổ chức

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#205]
- Xem danh sách các yêu cầu thanh toán và trạng thái thanh toán
- Báo nộp thanh toán bằng chuyển khoản
- Riêng màn hình báo kết quả thanh toán qua keypay sẽ được xử trong milestone tiếp theo

**Comment by khoahp** [comment]
@tragiangdt  em test lại cái này nhé, hiện tại module đã deploy lên server.

**Comment by tragiangdt** [comment]
test done
