### ISSUE TITLE
Portlet ID 22 - Quản lý thu phí cho cán bộ

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#207]
Xem danh sách các yêu cầu thanh toán cần thu phí
Xác nhận các yêu cầu thanh toán đã báo nộp và lập biên lai
Thực hiện thu phí bằng tiền mặt
In biên lai thu phí (có thể lập trình sau trong các version tiếp theo)

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
@khoahp 
- TH đã báo nộp: cán bộ không xem được chứng từ kèm theo
- Không hiển thị Phương thức thanh toán trên danh sách quản lý thu phí
- TH cán bộ xác nhận Hợp lệ TH chuyển khoản: trên màn hình chi tiết hiển thị sai Hình thức thực hiện
