### ISSUE TITLE
Xem nội dung thành phần hồ sơ dưới dạng form in  

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#208]
Tạo tiện ích trong backend cho phép sử dụng JasperReport để sinh form in cho dữ liệu json của thành phần hồ sơ. Tạo giao diện hiển thị ở chế độ preview cho các thành phần hồ sơ

**Comment by khoahp** [comment]
- Xử lý phần nhận dữ liệu Json của Form động, làm datasource cho Jasper.
