### ISSUE TITLE
Người sử dụng khi đăng nhập xong không mặc định vào không gian làm việc

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#209]
B1: Đăng nhập vào link http://qa.opencps.vn/
B2: Đăng nhập bằng tài khoản doanhnghiep.cps@gmail.com, canboxuly2.cps@gmail.com 
B3: Đăng nhập thành công, không vào không gian làm việc

**Comment by khoahp** [comment]
@dunglt91 tìm hiểu về cơ chế hook login của liferay, phần này redirect trang dựa theo role của người đăng nhập

**Comment by dunglt91** [comment]
@tragiangdt #209 Giang viết rõ kịch bản login cho từng đối tượng nào vào trang nào, như vậy mới có thể làm được

**Comment by tragiangdt** [comment]
@dunglt91  @trungnt-ksnb 
Công dân, doanh nghiệp: sau khi login thành công sẽ chuyển luôn vào trang http://qa.opencps.vn/group/guest/khong-gian-lam-viec-frontoffice
Cán bộ: sau khi login thành công sẽ chuyển luôn vào trang http://qa.opencps.vn/group/guest/quan-ly-ho-so
Kế toán: sau khi login thành công sẽ chuyển luôn vào trang http://qa.opencps.vn/group/guest/quan-ly-yeu-cau-thu-phi

**Comment by tragiangdt** [comment]
@dunglt91 @khoahp 
Trên qa vẫn còn lỗi này

**Comment by tragiangdt** [comment]
Thay đổi sitemap, sau khi đăng nhập thành công hệ thống redirect vào trang chủ
