### ISSUE TITLE
 [20160314] - Edit DictItem  không lưu lại được trường Parent Item đã chọn

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#21]
Phần Frontend Admin khi thực hiên Edit DictItem  không lưu lại được trường Parent Item đã chọn

**Comment by trungnt-ksnb** [comment]
Đang xử lý. Do phần này dev sẽ sử dụng phương án khác để chọn parentId(Không sử dụng select box vì không tối ưu) do đó hiện tại chức năng này mới chỉ tạm thời để phục vụ cho chức năng thêm mới DictItem
