### ISSUE TITLE
Các link trên văn bản pháp quy chưa xem được chi tiết

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#210]
B1: Người sử dụng vào địa chỉ http://qa.opencps.vn, Hiển thị mặc định trang chủ.
B2: Kích vào link dưới mục văn bản pháp quy không xem được chi tiết

**Comment by khoahp** [comment]
@hoanb sử dụng CMS của mặc định nhé

**Comment by hoanb** [comment]
Done
