### ISSUE TITLE
Các link dưới mục Hướng dẫn sử dụng chưa xem được chi tiết

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#211]
B1: Người sử dụng vào địa chỉ http://qa.opencps.vn, Hiển thị mặc định trang chủ.
B2: Kích vào link Đăng ký tài khoản, Đăng nhập hệ thống, Nộp hồ sơ trực tuyến, Nhận kết quả trực tuyến
B3: Lỗi không xem được chi tiết/ download file

**Comment by khoahp** [comment]
- Hoa sử dụng CMS để thực hiện các chức năng này nhé

**Comment by hoanb** [comment]
Done
