### ISSUE TITLE
Chưa tra cứu được theo thủ tục hành chính trên trang chủ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#212]
B1: Vào trang chủ http://qa.opencps.vn/
B2: Nhập tại ô Tìm kiếm…. Từ khóa:
Thông báo tập trung kinh tế
B3: Ấn nút Tìm kiếm
B4: Không hiển thị kết quả tìm kiếm theo thủ tục hành chính

**Comment by khoahp** [comment]
@tragiangdt phần này anh @dangkhanhtrung  đã làm, em test lại nhé

**Comment by tragiangdt** [comment]
test done
