### ISSUE TITLE
Đổi tên Cơ quan thực hiện thành Cơ quan quản lý trên trang chủ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#214]
Đổi tên Cơ quan thực hiện thành Cơ quan quản lý trên trang chủ

**Comment by tanhtanhvn** [comment]
Đã thiết kế lại Portlet 19. Trên trang chủ sẽ tìm kiếm thông tin theo 3 đối tượng gồm hồ sơ, giấy tờ kết quả và thủ tục hành chính. Nếu người sử dụng nhập đúng mã số tiếp nhận hồ sơ thì sẽ tra cứu được đầy đủ thông tin về trạng thái hồ sơ
