### ISSUE TITLE
Người sử dụng dịch vụ công không tra cứu được trạng thái hồ sơ theo Mã hồ sơ trên trang chủ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#216]
B1: Vào trang chủ http://qa.opencps.vn/
B2: Nhập số hồ sơ
B3: Ấn nút Tìm kiếm
B4: Không hiển thị màn hình kết quả tìm kiếm nội dung hồ sơ

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
