### ISSUE TITLE
Người sử dụng dịch vụ công không tra cứu được nội dung giấy phép trên trang chủ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#219]
B1: Vào trang chủ http://qa.opencps.vn/
B2: Nhập số giấy phép
B3: Ấn nút Tìm kiếm
B4: Không hiển thị màn hình kết quả tìm kiếm nội dung giấy phép

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
@dunglt91  @khoahp 
Chưa tra cứu được theo nội dung giấy phép
