### ISSUE TITLE
 [20160314] - Chức năng Sortable quản lý DictCollection và quản lý DictItem chưa thực hiện được

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#22]
![screenshot from 2016-03-14 18-05-52](https://cloud.githubusercontent.com/assets/17336814/13742622/6d32ac78-ea0f-11e5-8dc4-f087c562c864.png)
Phần : Frontend Admin Chức năng Sortable quản lý DictCollection và quản lý DictItem chưa thực hiện được

**Comment by trungnt-ksnb** [comment]
Đã fix xong
