### ISSUE TITLE
Nội dung email xác nhận, email cấp mật khẩu, email duyệt tài khoản chưa phù hợp

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#221]
Email xác nhận, có tiêu đề email, nội dung cần điều chỉnh:
- Tiêu đề: "http://qa.opencps.vn: Email Address Verification" đổi thành 
  "Thư xác nhận đăng ký trên OpenCPS"
- Nội dung: Dear nghiệp Doanh bị ngược tên

email cấp mật khẩu:
- Tiêu đề "http://qa.opencps.vn: Your New Account" đổi thành "Cấp mật khẩu tài khoản OpenCPS"
- Nội dung: Dear nghiệp Doanh bị ngược tên

email duyệt tài khoản:
- Tiêu đề "http://qa.opencps.vn: Your New Account" đổi thành "Thư xác nhận kích hoạt tài khoản OpenCPS"
- Nội dung: Dear nghiệp Doanh bị ngược tên

**Comment by khoahp** [comment]
@dunglt91 xử lý phần này nhé,

**Comment by tragiangdt** [comment]
@dunglt91 @khoahp  @trungnt-ksnb 
Nội dung mail  xác nhận: "Dear Anh ty TNHH Hoàng Công," vẫn bị ngược tên

**Comment by khoahp** [comment]
@tragiangdt Hiện tại các email đã sửa theo nội dung của QA đưa ra, giang kiểm tra nội dung email kết hợp với đầu vịec #361 rồi đóng issue này nhé

**Comment by tragiangdt** [comment]
@dunglt91  Nội dung mail xác nhận, email cấp mật khẩu, email duyệt tài khoản: "Dear Anh ty TNHH Hoàng Công," vẫn bị ngược tên

**Comment by khoahp** [comment]
@trungnt-ksnb Trung xử lý phần này nhé, viết function chung lấy tên chuẩn cho người dùng. Hiện tại đang lấy theo tiếng anh.

**Comment by tragiangdt** [comment]
test ok
