### ISSUE TITLE
Yêu cầu sắp xếp trạng thái hồ sơ doanh nghiệp theo thứ tự

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#222]
Trên màn hình quản lý hồ sơ doanh nghiệp, cần sắp xếp trạng thái theo thứ tự sau:
0, Tất cả
1, Mới
2, Chờ tiếp nhận
3, Chờ bổ sung
4, Đang xử lý
5, Chờ thanh toán
6, Kết thúc
7, Hệ thống xử lý
8, Lỗi xử lý

**Comment by tanhtanhvn** [comment]
@trungnt-ksnb 
Cập nhật danh mục trạng thái chỉ còn 8 trạng thái như trên. Các trạng thái được đánh mã số và sibling như trên để đảm bảo sắp xếp theo đúng thứ tự mong muốn nhé.

**Comment by tragiangdt** [comment]
@trungnt-ksnb 
Trên con qa chưa thấy cập nhật anh a

**Comment by khoahp** [comment]
@trungnt-ksnb

**Comment by khoahp** [comment]
@tragiangdt em test lai loi nay tren QA nhe
