### ISSUE TITLE
Bổ sung cột ngày nhận hồ sơ trên danh sách Quản lý hồ sơ của cán bộ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#223]
Bổ sung cột ngày nhận hồ sơ trên danh sách, cho phép Sắp xếp danh sách theo cột ngày nhận (mới nhất / cũ nhất)
Về nghiệp vụ, hồ sơ đến trước cần giải quyết trước

**Comment by khoahp** [comment]
@tragiangdt trong màn hình thiết kế không có trường này nhé, em liên hệ với anh @tanhtanhvn đễ bổ xung nhé.

@trungnt-ksnb  ông bổ xung thêm ngày tiếp nhận theo thiết kế mới nhé.

Hiện tại việc lọc hồ sơ đã theo nghiệp vụ, hồ sơ nào đến trước hiển thị phía trên.

**Comment by khoahp** [comment]
@huymq phần này bổ xung được ngay không em? anh để 1.7 nhé
