### ISSUE TITLE
Menu Không gian làm việc: Bộ lọc lỗi giá trị trong droplist 

### ISSUE THREAD

**Issue by tranmenb** [VietOpenCPS/opencps#228]
- Người làm thủ tục: Đăng nhập và chọn luôn menu "Không gian làm việc" => Droplist bộ lọc lỗi hiện giá trị "Tất cả" , phải sửa thành "Mới"

**Comment by khoahp** [comment]
@trungnt-ksnb Trung: xem lại kịch bản khi công dân vào danh sách của các hồ sơ chuẩn bị, nó hiển thị ra all hay theo trạng thái hồ sơ mới tạo.

**Comment by tragiangdt** [comment]
@trungnt-ksnb 
Phần này vẫn đang lỗi anh ạ, 
B1: Đăng nhập tài khoản doanh nghiệp
B2: Vào Không gian riêng
B3: Lỗi, danh sách hồ sơ hiển thị theo trạng thái mới, không theo trạng thái "Tất cả" trên giao diện
