### ISSUE TITLE
Chức năng bổ xung hồ sơ và rút hồ sơ chưa thực hiện được

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#229]
- Chức năng yêu cầu rút hồ sơ chưa hoạt động
- CHức năng bổ xung rút hồ sơ chưa hoạt động

**Comment by khoahp** [comment]
@trungnt-ksnb Trung xem bổ xung các button chức năng

**Comment by khoahp** [comment]
@tragiangdt em test laij nhe

**Comment by tragiangdt** [comment]
@khoahp  
1. Chưa hiển thị nút hủy hồ sơ đầu NLTT
2. Hiển thị hành động Xác nhận hủy hồ sơ tại Bước xử lý có cấu hình hành động Xác nhận hủy (cấu hình hành động Xác nhận hủy có điều kiện "cancel", những hành động nào được cấu hình có điều kiện thì không hiển thị trên phiếu xử lý tại bước xử lý đó)
Chỉ hiển thị khi nào nhận được điều kiện "cancel" từ NLTT
![2016-09-23_173352](https://cloud.githubusercontent.com/assets/17695836/18783069/f6a3cd48-81b3-11e6-9d05-555b518b1f0c.png)

**Comment by khoahp** [comment]
@huymq @tragiangdt hiện tại đã fix lại check preCondition cho phép hiển thị nút xác nhận huỷ. Nút huỷ hồ sơ phía công dân luôn hiển thị.

Chức năng huỷ hồ sơ báo lỗi => Chuyển @huymq nhé

Chức năng huỷ hồ sơ phía công dân cần check điều kiện thực hiện qua server phân tán, @trungnt-ksnb xử lý

**Comment by Hongnt31** [comment]
1. Chưa hiển thị nút hủy hồ sơ đầu NLTT theo cấu hình chỉ mới hiển thị ở trạng thái đang xử lý
2. Hiển thị hành động Xác nhận hủy hồ sơ tại Bước xử lý có cấu hình hành động Xác nhận hủy (cấu hình hành động Xác nhận hủy có điều kiện "cancel", những hành động nào được cấu hình có điều kiện thì không hiển thị trên phiếu xử lý tại bước xử lý đó)
   Chỉ hiển thị khi nào nhận được điều kiện "cancel" từ NLTT
3. Khi NLTT thực hiện Yêu cầu hủy hồ sơ tại bước không có cấu hình hành động Xác nhận hủy có điều kiện "cancel" thì chưa hiển thị thông báo cho NLTT
4. Khi NLTT thực hiện Yêu cầu hủy hồ sơ tại bước có cấu hình hành động Xác nhận hủy có điều kiện "cancel" thì chưa hiển thị thông báo xác nhận hành động cho NLTT

**Comment by khoahp** [comment]
@tragiangdt test lại nhé

**Comment by tragiangdt** [comment]
1. Chưa hiển thị nút hủy hồ sơ đầu NLTT theo cấu hình chỉ mới hiển thị ở trạng thái đang xử lý
   Cấu hình xin rút hồ sơ tại bước yêu cầu bổ sung hs (trạng thái hs đang là chờ bổ sung) -> Lỗi: trên danh sách hồ sơ của doanh nghiệp ko hiển thị nút xin rút hồ sơ
2. ok
3. Chưa có thông báo
4. ok
5. Kích hoạt tự động kiểm tra 5 phút/ lần hoặc 1 phút /lần khi có điều kiện cancel chưa chạy

**Comment by tragiangdt** [comment]
@khoahp giờ trên con qa không hiển thị nút Xin hủy trên danh sách hồ sơ của NLTT anh ạ

**Comment by Hongnt31** [comment]
@khoahp  vẫn còn các lỗi
1. Chưa hiển thị nút hủy hồ sơ đầu NLTT theo cấu hình chỉ mới hiển thị ở trạng thái chờ xử lý Cấu hình xin rút hồ sơ tại bước yêu cầu bổ sung hs (trạng thái hs đang là chờ bổ sung) -> Lỗi: trên danh sách hồ sơ của doanh nghiệp ko hiển thị nút xin rút hồ sơ
![image](https://cloud.githubusercontent.com/assets/20554327/20175918/d9a00ce0-a777-11e6-9661-436163c7f56a.png)
2.Khi NLTT thực hiện Yêu cầu hủy hồ sơ tại bước có cấu hình hành động Xác nhận hủy có điều kiện "cancel" thì chưa hiển thị thông báo xác nhận hành động thành công hay thất bại cho NLTT

**Comment by Hongnt31** [comment]
@khoahp  vẫn còn các lỗi 
1. Chưa hiển thị nút hủy hồ sơ đầu NLTT theo cấu hình chỉ mới hiển thị ở trạng thái chờ xử lý Cấu hình xin rút hồ sơ tại bước yêu cầu bổ sung hs (trạng thái hs đang là chờ bổ sung) -> Lỗi: trên danh sách hồ sơ của doanh nghiệp ko hiển thị nút xin rút hồ sơ
![image](https://cloud.githubusercontent.com/assets/20554327/20385162/e6d3e974-ace8-11e6-89a3-9031467ffff3.png)
2.Khi NLTT thực hiện Yêu cầu hủy hồ sơ tại bước có cấu hình hành động Xác nhận hủy có điều kiện "cancel" thì chưa hiển thị thông báo xác nhận hành động thành công hay thất bại cho NLTT
3. Hiển thị hành động Xác nhận hủy hồ sơ tại Bước xử lý có cấu hình hành động Xác nhận hủy (cấu hình hành động Xác nhận hủy có điều kiện "cancel", những hành động nào được cấu hình có điều kiện thì không hiển thị trên phiếu xử lý tại bước xử lý đó) Chỉ hiển thị khi nào nhận được điều kiện "cancel" từ NLTT

**Comment by khoahp** [comment]
@nhan0987 xử lý cho anh lỗi này

**Comment by khoahp** [comment]
Done
