### ISSUE TITLE
Giao diện: Lỗi hiển thị text 

### ISSUE THREAD

**Issue by tranmenb** [VietOpenCPS/opencps#231]
Menu Quản lý hồ sơ/Thành phần hồ sơ: Hệ thống không hiển thị hết text tên các thành phần hồ sơ trong trường hợp tên quá dài
![text](https://cloud.githubusercontent.com/assets/17776635/15348159/623cc914-1cf2-11e6-8157-6e7e85506ce1.jpg)

**Comment by tanhtanhvn** [comment]
Giang đào tạo lại Mến cách ghi issue. Ghi thế này không ai hiểu cả. Phần tên phải cụ thể về lỗi để phân biệt các lỗi với nhau. Phần mô tả phải ghi cụ thể từng bước thực hiện phát sinh ra lỗi.

**Comment by khoahp** [comment]
@tranmenb 

Em chi tiết hơn chút nữa nhé. Ví dụ:
- Đối tượng đăng nhập là gì? --> Vào màn hình xử lý gì? --> Lỗi sảy ra ntn? -->...

Với mô tả lỗi của em như trên, điều kiện biên test của em chưa có (quá dài là bao nhiêu), và mong muốn giá trị là bao nhiêu?...

**Comment by trungnt-ksnb** [comment]
@tranmenb 
Done

**Comment by tragiangdt** [comment]
@khoahp 
Đã test ok. anh Khoa close issue giúp em
