### ISSUE TITLE
Màn hình quản lý danh sách thủ tục hành chính chưa hiển thị trường trạng thái thủ tục hành chính

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#232]
Màn hình quản lý danh sách thủ tục hành chính chưa hiển thị trường trạng thái thủ tục hành chính theo thiết kế

**Comment by khoahp** [comment]
@dunglt91 em bổ xung thêm phần trạng thái thủ tục khi xem chi tiết

**Comment by khoahp** [comment]
@tragiangdt 

Đã fix em test lại trên con QA nhé

Commit ID https://github.com/VietOpenCPS/opencps/pull/236/commits/ee1a353fe517d93536ee5b983b517be5ea4d5460

**Comment by tragiangdt** [comment]
Trên con QA em vẫn chưa thấy có đâu anh @khoahp

**Comment by tragiangdt** [comment]
Đã test ok
