### ISSUE TITLE
Màn hình quản lý danh sách thủ tục hành chính đang hiển thị nhầm hai cột lĩnh vực thủ tục và cơ quan quản lý với nhau

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#233]
B1: Vào menu thủ tục hành chính
B2: Màn hình quản lý danh sách thủ tục hành chính đang hiển thị nhầm hai cột lĩnh vực thủ tục và cơ quan quản lý với nhau

**Comment by khoahp** [comment]
@dunglt91 
Em cập nhật lại trường này, tại search-container nhé

**Comment by dunglt91** [comment]
ok anh

**Comment by khoahp** [comment]
@tragiangdt 

Đã fix em test lại trên QA http://qa.opencps.vn/thu-tuc-hanh-chinh

Commit ID https://github.com/VietOpenCPS/opencps/pull/236/commits/d1c602836ebb768effb3b31e4703898b705e2252

**Comment by tragiangdt** [comment]
Đã test ok
