### ISSUE TITLE
Lỗi Thông báo: Khi Công dân thêm/sửa thông tin hồ sơ

### ISSUE THREAD

**Issue by tranmenb** [VietOpenCPS/opencps#234]
Công dân:
- Khi thêm/sửa thông tin hồ sơ: Form thêm/sửa Không chọn giá trị Phường/Xã
  => Thực hiện: chọn nút "Ghi lại" báo lỗi org.opencps.dossiermgt.EmptyDossierWardCodeException

**Comment by khoahp** [comment]
@tranmenb Anh chuyển chung các lỗi thông báo, việt hóa về issue #235 nhé!

**Comment by dunglt91** [comment]
fix done!

**Comment by tragiangdt** [comment]
Test done
