### ISSUE TITLE
Lỗi về thông báo, việt hóa form

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#235]
@tranmenb @tragiangdt

Các em cập nhật các lỗi liên quan đến thông báo, lỗi Việt hóa vào chung issue này nhé

@dunglt91 theo dõi Issue này xử lý.
1. Khi thêm/sửa thông tin hồ sơ: Form thêm/sửa Không chọn giá trị Phường/Xã => Thực hiện: chọn nút "Ghi lại" báo lỗi org.opencps.dossiermgt.EmptyDossierWardCodeException 

....

**Comment by tragiangdt** [comment]
Khi tra cứu thur tục hành chính không có kết quả, hệ thống hiển thị "no-serviceinfo-were-found "

**Comment by dunglt91** [comment]
@khoahp @trungnt

đã việt hóa

**Comment by tragiangdt** [comment]
@dunglt91 Màn hình tải giấy tờ khi chuẩn bị hồ sơ  chưa việt hóa display-name (Bắt buộc)

**Comment by tragiangdt** [comment]
@dunglt91 Màn hình XỬ lý của cán bộ xử lý hồ sơ có text " system-receive" chưa được việt hóa

**Comment by tragiangdt** [comment]
@dunglt91 Màn hình tải file giấy tờ kết quả (tab xử lý hồ sơ của cán bộ) chưa việt hóa

**Comment by khoahp** [comment]
@tragiangdt @tragiangdt @dangkhanhtrung @dunglt91 

Các anh em rà soát lại một lần trên giao diện màn hình của mình xây dựng, bổ xung các key còn thiếu nhé!
