### ISSUE TITLE
Màn hình "Hồ sơ chờ xử lý" chức năng bộ lọc chưa hoạt động

### ISSUE THREAD

**Issue by tranmenb** [VietOpenCPS/opencps#237]
Ảnh mô tả chi tiết:
![b l c](https://cloud.githubusercontent.com/assets/17776635/15348117/1131d0f0-1cf2-11e6-9cfb-af6ee71aa288.jpg)

**Comment by khoahp** [comment]
@tranmenb 

Em cập nhật chi tiết trong phần mô tả nhé, cái nào khó diễn tả có thể chụp cả anh màn hình.

**Comment by tranmenb** [comment]
Vâng ah.

**Comment by tragiangdt** [comment]
@khoahp 
Vẫn còn lỗi

**Comment by khoahp** [comment]
@trungnt-ksnb TrungNT xem lại phần này nhé

**Comment by khoahp** [comment]
@trungnt-ksnb phần này select cho chạy hàm tìm kiếm nhưng kết quả sai. Trung xem lại, chuyển qua 1.2 nhé
