### ISSUE TITLE
Hiển thị lại tên trạng thái hồ sơ trong phần Phiếu xử lý hồ sơ/Thông tin hồ sơ

### ISSUE THREAD

**Issue by tranmenb** [VietOpenCPS/opencps#239]
Ảnh mô tả: ![hi n th ten tr ng thai](https://cloud.githubusercontent.com/assets/17776635/15348241/2c01c29a-1cf3-11e6-9f65-ba025e232d76.jpg)

**Comment by khoahp** [comment]
@trungnt-ksnb

**Comment by trungnt-ksnb** [comment]
@tranmenb 
Done

**Comment by tragiangdt** [comment]
@trungnt-ksnb 
Vẫn còn lỗi

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
@khoahp  Trên con QA vẫn hiển thị trạng thái là số

**Comment by khoahp** [comment]
@trungnt-ksnb

**Comment by tragiangdt** [comment]
@khoahp  
test done
