### ISSUE TITLE
Hiển thị trùng tên người phụ trách trong màn hình Phiếu xử lý hồ sơ/Xử lý

### ISSUE THREAD

**Issue by tranmenb** [VietOpenCPS/opencps#240]
Ảnh mô tả: ![trung text](https://cloud.githubusercontent.com/assets/17776635/15348278/82964b76-1cf3-11e6-9767-b4ecb723c940.jpg)

**Comment by khoahp** [comment]
@trungnt-ksnb 

Trung kiểm tra màn hình giúp mình nhé

**Comment by trungnt-ksnb** [comment]
@tranmenb 
Done

**Comment by tragiangdt** [comment]
@tranmenb 
Test done
