### ISSUE TITLE
Không nhập hết được tên, tên ngắn thủ tục hành chính khi thêm mới/sửa thủ tục hành chính

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#243]
B1: Đăng nhập tài khoản quản trị
B2: Vào quản lý thủ tục hành chính
B3: Thêm mới/sửa tên, tên ngắn thủ tục hành chính
Độ dài tên, tên ngắn, mô tả thủ tục hành chính quá ngắn, không nhập hết được tên TTHC

**Comment by tanhtanhvn** [comment]
Sửa lại theo thiết kế gồm có 2 trường tên và tên đầy đủ. Trường tên sẽ được sử dụng trong các danh sách hiển thị. Trường tên đầy đủ chỉ dùng để hiển thị khi tra cứu

**Comment by khoahp** [comment]
@dunglt91 

Em bổ xung thêm trường fullName, bỏ trường shortName của entity serviceInfo.

Lưu ý cần thay đổi tại các file jsp tạo mới (cập nhật) thủ tục hành chính, file xem chi tiết. Tại các file Java cần thay đổi lại ServiceImpl. Và các file phục vụ cho search thủ tục.

**Comment by dunglt91** [comment]
fix done!

@trungnt-ksnb @tragiangdt @khoahp @tanhtanhvn

**Comment by tragiangdt** [comment]
test done
