### ISSUE TITLE
Thiếu chức năng nộp hồ sơ trực tuyến trên màn hình tra cứu danh bạ thủ tục

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#244]
Thiếu chức năng nộp hồ sơ trực tuyến trên màn hình tra cứu danh bạ thủ tục khi đã đăng nhập bằng tài khoản NLTT

**Comment by khoahp** [comment]
@dunglt91 

Em bổ xung thêm một nút Nộp hồ sơ trực tuyến tại cuối màn hình xem chi tiết TTHC. Đường dẫn lấy từ trường onlineUrl trong bảng serviceinfo.

@tragiangdt 

Em cập nhật thông tin nộp hồ sơ trực tuyến tạm thời bằng cách vào màn hình chuẩn bị hồ sơ của thủ tục, copy URL rồi paste vào trường onlineURL khi tao (cập nhật) thủ tục hành chính cấp 2.

**Comment by dunglt91** [comment]
@khoahp  @tragiangdt  @trungnt-ksnb  fix done

**Comment by tragiangdt** [comment]
test done
