### ISSUE TITLE
Chưa xem được file kết quả đã upload trên màn hình xử lý hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#245]
B1: Đăng nhập tài khoản canboxuly2.cps@gmail.com
B2: Chọn xử lý 1 hồ sơ/ Upload file kết quả
B3: Chưa xem được file kết quả đã upload

**Comment by khoahp** [comment]
@trungnt-ksnb 

Trung xem lại phần này, lần trước mình thấy được rồi mà.

**Comment by tragiangdt** [comment]
@trungnt-ksnb Mới chỉ có chức năng tải về máy để xem, chưa có chức năng xem online
