### ISSUE TITLE
Cột thủ tục hiển thị nhầm mã định danh Màn hình danh sách hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#246]
B1: Đăng nhập tài khoản NLTT
B2: Vào Không gian làm việc
B3: Trên màn hình danh sách hồ sơ cột thủ tục đang hiển thị nhầm mã định danh

**Comment by khoahp** [comment]
@trungnt-ksnb 

Trung thay mã thủ tục hành chính bằng tên nhé!

**Comment by tragiangdt** [comment]
Đã test ok
