### ISSUE TITLE
Chỉnh sửa thêm điều kiện thực hiện đối với các thao tác xử lý trong quy trình

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#247]
Trong quy trình xử lý hồ sơ cần bổ sung điều kiện để thực hiện thao tác và cờ đánh dấu cho phép thực hiện xử lý cùng lúc nhiều hồ sơ. Khi hiển thị thao tác thực hiện tại mỗi bước cần phải kiểm tra điều kiện thực hiện (nếu có)

**Comment by tanhtanhvn** [comment]
Thêm cờ đánh dấu thao tác kết thúc xử lý để cập nhật finishDatetime trong hồ sơ. Số lượng trạng thái của hồ sơ chỉ còn 8 gồm: new, receiving, processing, ended, waiting, paying, system, error.
@khoahp : Ưu tiên sửa giao diện cập nhật quy trình để làm được backend xử lý theo đúng cấu hình của quy trình trong DB.

**Comment by khoahp** [comment]
@tragiangdt, @tanhtanhvn 

Anh mới bổ xung thêm một cờ đánh dấu là bước này là bước hoàn thành (cập nhật fisnishDate)

**Comment by khoahp** [comment]
@tragiangdt, @tanhtanhvn 

Trà Giang test lại nhé, anh đã cập nhật lên con QA

**Comment by tragiangdt** [comment]
@khoahp Anh chưa chuyển số lượng hồ sơ chỉ còn 8 trạng thái: new, receiving, processing, ended, waiting, paying, system, error.
- Đã có cờ đánh dấu là bước hoàn thành

**Comment by tanhtanhvn** [comment]
@khoahp Khoa update lại cái này chưa để close lại. Giang kiểm tra lại sau khi đã fix nhé
