### ISSUE TITLE
Không sửa được Thao tác trong quy trình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#249]
B1: Vào một quy trình
B2: Vào thay đổi Thao tác 
B3: Nhấn nút Thêm
B4: Lỗi không lưu lại được các giá trị đã sửa

**Comment by tragiangdt** [comment]
@khoahp  
Vẫn còn một số trường sửa chưa được

**Comment by khoahp** [comment]
@dunglt91 em trao đổi với @tragiangdt  xem trường nào không sửa được, phải đọc lại thiết kế và logic, có thể có trường không cho phép sửa

**Comment by tragiangdt** [comment]
@dunglt91 
- Phân công người xử lý
- Thêm kết quả xử lý
- Bước sau thực hiện thao tác

**Comment by khoahp** [comment]
@dunglt91 bug này fix chưa em ới

**Comment by dunglt91** [comment]
@khoahp #249
Bug nay em fix roi anh nhe

**Comment by tragiangdt** [comment]
@dunglt91 
Vẫn còn bug: 
B1: sửa kết quả xử lý 
B2: Nhấn nút Thêm
B3: Mở xem lại thao tác không thấy lưu vết kết quả xử lý

**Comment by tragiangdt** [comment]
tesst done
