### ISSUE TITLE
Danh sách hồ sơ trong màn hình quản lý hồ sơ của NLTT chưa sắp xếp theo thứ tự mới-cũ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#252]
B1: Đăng nhập bằng tài khoàn người làm thủ tục
B2: Vào không gian làm việc
B3: Danh sách hồ sơ trong màn hình quản lý hồ sơ của NLTT chưa sắp xếp theo thứ tự mới-cũ

**Comment by khoahp** [comment]
@trungnt-ksnb

**Comment by trungnt-ksnb** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
@trungnt-ksnb Danh sách hồ sơ của NLTT vẫn sắp xếp theo thứ tự cũ-mới, hồ sơ mới tạo luôn ở dưới danh sách

**Comment by tragiangdt** [comment]
Đã test ok
