### ISSUE TITLE
Lỗi hiển thị những thủ tục hành chính có trạng thái bí mật trên danh sách thủ tục hành chính 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#254]
B1: Vào http://qa.opencps.vn/
B2: Vào menu thủ tục hành chính
B3: Lỗi hiển thị những thủ tục hành chính có trạng thái bí mật trên danh sách thủ tục hành chính

**Comment by tragiangdt** [comment]
Lỗi này @dunglt91 đã sửa rồi anh Khoa ạ.

**Comment by khoahp** [comment]
@tragiangdt 

Vậy em close vào nhé

**Comment by dunglt91** [comment]
@khoahp  @trungnt-ksnb @tragiangdt , Fixed
