### ISSUE TITLE
Sửa giao diện màn hình đăng ký tài khoản Công dân

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#255]
- Vào: http://qa.opencps.vn/home 
- Chọn Đăng ký 
- Trong màn hình Đăng kí tài khoản công dân, sửa lại giao diện:  
- Sửa chữ bắt buộc thành dấu \* màu đỏ như file màn hình (Màn hình: DK_001_Đăng ký tài khoản công dân)  
- Sửa lại khoảng cách các trường như file màn hình (Màn hình: DK_001_Đăng ký tài khoản công dân) 
- Sửa thông tin tiêu đề:  - Thư điện tử thành "Địa chỉ thư điện tử - Email" -  Tệp đính kèm thành "Tệp đính kèm (Chứng mình thư/Giấy tờ định danh)"  (Màn hình: DK_001_Đăng ký tài khoản công dân) 
- Bỏ bắt buộc các trường, chỉ giữ lại bắt buộc 2 trường: Tên đầy đủ và Thư điện tử (Màn hình: DK_001_Đăng ký tài khoản công dân) 
- **File màn hình:**  
  [https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh](https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh)

**Comment by khoahp** [comment]
@trungnt-ksnb 

TrungNT: ông hook sửa tablib mặc định của liferay.

@dunglt91 

Em chỉnh sửa các file CSS nhé.
