### ISSUE TITLE
Sửa giao diện màn hình danh sách hồ sơ của cán bộ

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#257]
- Vào: http://qa.opencps.vn/home
- Chọn Đăng nhập, đăng nhập bằng tài khoản:
  canboxuly2.cps@gmail.com/cps12345
- Chọn Không gian làm việc
- Trong màn hình danh sách hồ sơ của cán bộ, sửa lại giao diện:
  1. Sửa lại nút [Xử lý] như màn hình (Màn hình: CB_001_QLHS – Danh sách hồ sơ)
  2. Sửa lại khoảng cách như hình (Màn hình: CB_001_QLHS – Danh sách hồ sơ)
     3.Thêm phân trang theo hình (Màn hình: CB_001_QLHS – Danh sách hồ sơ) 
- **File màn hình:** 
  [https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh](https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh)

**Comment by khoahp** [comment]
@vuminhcuong anh đã cập nhật đầu việc sửa lại giao diện thiết kế tại 2 issues #398 và #400 em close issues này giúp anh nhé
