### ISSUE TITLE
Sửa giao diện màn hình xử lý hồ sơ của cán bộ

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#260]
- Vào: http://qa.opencps.vn/home
- Chọn Đăng nhập, đăng nhập bằng tài khoản:
  canboxuly2.cps@gmail.com/cps12345
- Chọn Không gian làm việc, chọn 1 hồ sơ để xem chi tiết
- Chọn Xử lý
- Trong màn hình xử lý hồ sơ khi cán bộ chọn, sửa lại giao diện:
  1. Sửa lại menu bên phải như màn hình (CB_004_QLHS – Xử lý)
  2. Sửa lại khoảng cách giữa các thành phần như hình (CB_004_QLHS – Xử lý)
  3. Bỏ bớt 1 ô trên cùng của menu bên phải như hình (CB_004_QLHS – Xử lý)
  4. Thêm phân chia các phần dữ liệu như hình (Màn hình: CB_004_QLHS – Xử lý) 
- **File màn hình:** 
  [https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh](https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh)

**Comment by khoahp** [comment]
@vuminhcuong anh đã cập nhật đầu việc sửa lại giao diện thiết kế tại 2 issues #398 và #400 em close issues này giúp anh nhé
