### ISSUE TITLE
Sửa giao diện màn hình quản lý hồ sơ của công dân, doanh nghiệp

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#261]
- Vào: http://qa.opencps.vn/home
- Chọn Đăng nhập, đăng nhập bằng tài khoản:
  doanhnghiep.cps@gmail.com/cps12345
- Chọn Không gian làm việc
- Trong màn hình danh sách hồ sơ của công dân, doanh nghiệp, sửa lại giao diện:
  1. Bỏ tab Giấy tờ, Hồ sơ ngoài như hình (Màn hình: DN_001_QLHS – Danh sách hồ sơ)
  2. Sửa lại màn hình như file html (Màn hình: DN_001_QLHS – Danh sách hồ sơ)
- **File màn hình:** 
  [https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh](https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh)

**Comment by khoahp** [comment]
@vuminhcuong anh đã cập nhật đầu việc sửa lại giao diện thiết kế tại 2 issues #398 và #400 em close issues này giúp anh nhé
