### ISSUE TITLE
Sửa giao diện màn hình thông tin hồ sơ của công dân, doanh nghiệp

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#262]
- Vào: http://qa.opencps.vn/home
- Chọn Đăng nhập, đăng nhập bằng tài khoản:
  doanhnghiep.cps@gmail.com/cps12345
- Chọn Không gian làm việc
- Chọn Xem một hồ sơ
- Trong màn hình thông tin hồ sơ, sửa lại giao diện:
  1. Sửa lại menu bên phải như hình (Màn hình: DN_002_QLHS – Thông tin hồ sơ)
  2. Sửa lại khoảng cách giữa các thành phần như hình (Màn hình: DN_002_QLHS – Thông tin hồ sơ)
  3. Để mặc định chủ hồ sơ là tên của tài khoản đăng nhập (Màn hình: DN_002_QLHS – Thông tin hồ sơ)
- Sửa lại các thành phần màn hình (Màn hình: DN_002_QLHS – Thông tin hồ sơ)
- **File màn hình:** 
  [https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh](https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh)

**Comment by khoahp** [comment]
@vuminhcuong anh đã cập nhật đầu việc sửa lại giao diện thiết kế tại 2 issues #398 và #400 em close issues này giúp anh nhé
