### ISSUE TITLE
Lỗi trạng thái hồ sơ chưa cấu hình được

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#264]
Trạng thái hồ sơ chưa cấu hình được, đang fix code.

**Comment by khoahp** [comment]
@trungnt-ksnb 

Trung rà soát các phần cần sửa trong màn hình danh sách chuẩn bị hồ sơ, màn hình xem chi tiết hồ sơ... Thay lại toàn bộ bằng cách lấy ra theo danh mục (dataitem).

**Comment by khoahp** [comment]
@tanhtanhvn phần này xin chuyển sang ver 1.2 anh nhé?

**Comment by khoahp** [comment]
@tragiangdt anh đóng vào do trùng bug nhé
