### ISSUE TITLE
Trường tên đầy đủ của doanh nghiệp khi đăng ký tài khoản không lưu được vào DB

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#268]
B1: Đăng ký tài khoản doanh nghiệp
B2: Lỗi Trường tên đầy đủ của doanh nghiệp khi đăng ký tài khoản không lưu được vào DB

**Comment by khoahp** [comment]
@dunglt91 

Dũng trao đổi với anh Trung phần này xem có phải là phần tách tên có vấn đề không nhé!

**Comment by dunglt91** [comment]
fix done! @tragiangdt  @khoahp

**Comment by tragiangdt** [comment]
Đã test ok
