### ISSUE TITLE
Trạng thái hồ sơ "Chờ xử lý" đổi thành "Chờ bổ sung"

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#272]
Trạng thái hồ sơ "Chờ xử lý" đổi thành "Chờ bổ sung", hiện tại đang việt hóa nhầm trạng thái waiting là chờ xử lý

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
DOne

**Comment by tragiangdt** [comment]
@trungnt-ksnb Trên con qa chưa done

**Comment by tragiangdt** [comment]
Đã test done
