### ISSUE TITLE
Nhấn Ghi lại khi chuẩn bị hồ sơ, hệ thống luôn thông báo "Yêu cầu của bạn đã được xử lý không thành công."

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#274]
- Đăng nhập tài khoản doanh nghiệp
- Thêm mới 1 hồ sơ
- Lỗi: Nhấn Ghi lại khi chuẩn bị hồ sơ, hệ thống luôn thông báo "Yêu cầu của bạn đã được xử lý không thành công."

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
Done

**Comment by tragiangdt** [comment]
Đã test ok
