### ISSUE TITLE
Hệ thống luôn sinh 1 số tiếp nhận khi gửi hồ sơ mà chưa cần đến bước Tiếp nhận hồ sơ của cán bộ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#275]
B1: Đăng nhập tài khoản doanh nghiệp
B2: Nộp hồ sơ
B3: Lỗi Hệ thống luôn sinh 1 số tiếp nhận khi gửi hồ sơ mà chưa cần đến bước Tiếp nhận hồ sơ của cán bộ

**Comment by tragiangdt** [comment]
@khoahp 
Mong muốn: Cấu hình tiếp nhận ở bước nào thì bước đó mới sinh số tiếp nhận, không phải cứ nộp hồ sơ là sinh số tiếp nhận luôn anh a.

**Comment by khoahp** [comment]
@tragiangdt em test lại trên con QA nhé

**Comment by tragiangdt** [comment]
@khoahp 
Hiện tại hệ thống đang sinh số tiếp nhận khi nộp hồ sơ.

**Comment by tragiangdt** [comment]
Test ok
