### ISSUE TITLE
Mã tiếp nhận của hồ sơ thay đổi khác nhau sau mỗi bước xử lý

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#280]
B1: Khi nộp hồ sơ, 1 mã hồ sơ được sinh ra
B2: Vào tài khoản cán bộ, thực hiện xử lý hồ sơ
B3: Lỗi Mã tiếp nhận hồ sơ lại nhảy sang 1 mã khác

**Comment by khoahp** [comment]
@tragiangdt em test lại trên QA nhé.

**Comment by tragiangdt** [comment]
@khoahp  Vẫn còn sót TH Bổ sung hồ sơ: khi DN nộp bổ sung hồ sơ thì hệ thống sinh ra 1 số tiếp nhận khác

**Comment by tragiangdt** [comment]
test ok

**Comment by tragiangdt** [comment]
@khoahp  
Vẫn còn lỗi TH:
Hồ sơ đã có mã tiếp nhận, cán bộ yêu cầu bổ sung hồ sơ. Sau đó DN nộp bổ sung thì hồ sơ này bị mất số tiếp nhận.

**Comment by tragiangdt** [comment]
test done
