### ISSUE TITLE
Tổng số thủ tục hành chính trên menu Cơ quan quản lý và Lĩnh vực thủ tục không bằng số TTHC trên danh sách

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#288]
B1: Đăng nhập vào http://qa.opencps.vn/thu-tuc-hanh-chinh
B2: Lỗi Tổng số thủ tục hành chính trên menu Cơ quan quản lý, Lĩnh vực thủ tục không bằng số TTHC trên danh sách

**Comment by khoahp** [comment]
@dunglt

**Comment by tragiangdt** [comment]
@dunglt91  
Đã hotfix dữ liệu
