### ISSUE TITLE
Lĩnh vực thủ tục "Cạnh tranh và tập trung kinh tế"  xuất hiện ở cột Cơ quan quản lý

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#289]
B1: Vào đường link http://qa.opencps.vn/thu-tuc-hanh-chinh
B2: Thủ tục Thông báo tập trung kinh tế có Lĩnh vực thủ tục "Cạnh tranh và tập trung kinh tế"  xuất hiện ở cột Cơ quan quản lý

**Comment by khoahp** [comment]
@dunglt91

**Comment by tragiangdt** [comment]
@dunglt91  đã hotfix dữ liệu
