### ISSUE TITLE
Thành phần giấy tờ nộp vào không chọn khai trực tuyến nhưng trên màn hình nhập đơn vẫn hiển thị chức năng khai trực tuyến

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#290]
B1: Cấu hình thành phần hồ sơ là giấy nộp vào, không nhập trường ký hiệu mã đơn
B2: Vào thêm mới/sửa hồ sơ, danh sách thành phần hồ sơ trên màn hình chuẩn bị hồ sơ vẫn hiển thị chức năng khai trực tuyến

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
Done
Vẫn có form khai trực tuyến nhưng ẩn nút xem trước, nút lưu form và hiển thị thông báo chưa có form động

**Comment by tragiangdt** [comment]
@trungnt-ksnb Anh sửa như vậy chưa đúng thiết kế
