### ISSUE TITLE
Lỗi Tải file đính kèm khi chuẩn bị hồ sơ xong hệ thống quay ra màn hình danh sách hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#291]
B1: Sửa hồ sơ
B2: Thêm 1 tệp đính kèm
B3: Nhập tên tệp đính kèm trùng với tệp trước, sao cho nhấn lưu lại thông báo lỗi
B4: Nhập lại tên têp đính kèm đúng
B5: Nhấn ghi lại, lỗi: hệ thống quay lại màn hình danh sách hồ sơ (phải quay lại màn hình thành phần hồ sơ)

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
Done em  nhé

**Comment by tragiangdt** [comment]
đã test ok
