### ISSUE TITLE
Nên xóa file .project ở thư mục gốc

### ISSUE THREAD

**Issue by vuthao** [VietOpenCPS/opencps#3]
Nên xóa file .project ở thư mục gốc.
Nguyên nhân, khi checkout bằng eclipse về sẽ gây lỗi không tạo được project, khi đó sẽ mất công Add lại project.

Sau khi xóa xong, Add project lại tự sinh ra file này, cần .gitignore nó

**Comment by tanhtanhvn** [comment]
@khoahp em nghiên cứu và xử lý issue này nhé. Thảo đã có kinh nghiệm món này nên việc này có thể xảy ra.

**Comment by khoahp** [comment]
@vuthao cảm ơn anh thảo.
@tanhtanhvn em sẽ bỏ file này đi.

**Comment by khoahp** [comment]
Em đã cập nhật lại, anh appove giúp em nhé
