### ISSUE TITLE
NLTT chưa xem được thông báo yêu cầu bổ sung (yêu cầu cần phải xử lý) trên tab Kết quả thực hiện

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#306]
B1: Cán bộ văn thư vào xử lý hồ sơ có trạng thái tiếp nhận hồ sơ
B2: Chọn thao tác hướng dẫn doanh nghiệp bổ sung hs
B3: Lỗi NLTT chưa xem được thông báo yêu cầu bổ sung (yêu cầu cần phải xử lý) trên tab Kết quả thực hiện

**Comment by khoahp** [comment]
@tragiangdt em test lại phần này nhé

**Comment by tragiangdt** [comment]
@trungnt-ksnb Trên qa vẫn chưa dc anh nhé

**Comment by trungnt-ksnb** [comment]
@tragiangdt  done

**Comment by tragiangdt** [comment]
test done

**Comment by tragiangdt** [comment]
Lỗi này trên qa lại gặp phải ạ

**Comment by khoahp** [comment]
@tragiangdt test lại nhé

**Comment by tragiangdt** [comment]
test done trên qa

**Comment by tragiangdt** [comment]
@khoahp Lỗi này bị lặp lại

**Comment by khoahp** [comment]
@tragiangdt em test lai nhe

**Comment by Hongnt31** [comment]
1. Đổi Loại yêu cầu thành : Yêu cầu bổ sung hồ sơ
2. Chưa có ghi chú của cán bộ ở phần Thông báo
   ![image](https://cloud.githubusercontent.com/assets/20554327/19336690/b5b287a0-9137-11e6-928a-222769284ba4.png)

**Comment by Hongnt31** [comment]
@khoahp 
Chưa Đổi Loại yêu cầu thành : Yêu cầu bổ sung hồ sơ
![image](https://cloud.githubusercontent.com/assets/20554327/20182712/45301f8c-a795-11e6-86e3-730fe169c2c9.png)

**Comment by khoahp** [comment]
@Hongnt31 em test lại lỗi này nhé, anh đã cập nhật

**Comment by Hongnt31** [comment]
Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20381238/23145e60-acd9-11e6-9317-f7c7635c2cc7.png)
