### ISSUE TITLE
NLTT nhìn thấy được file kết qủa khi cán bộ xử lý mới upload file kết quả 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#313]
B1: Đăng nhập tài khoản cán bộ xử lý, chọn hồ sơ đang ở bước xử lý hồ sơ
B2: Tả file kết quả
B3: Vào tài khoản NLTT, xem kết quả hiển thị hồ sơ đưọc chọn
Lỗi: NLTT nhìn thấy được file kết qủa khi cán bộ xử lý mới upload file kết quả

**Comment by khoahp** [comment]
@trungnt-ksnb bị trùng bug em đóng lại nhé

**Comment by tragiangdt** [comment]
@khoahp  Trùng với bug nào đã fix vậy anh?
