### ISSUE TITLE
Cán bộ nhìn thấy được nội dung hồ sơ đã sửa đổi khi NLTT vào sửa đổi hồ sơ nhưng chưa gửi bổ sung

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#314]
B1: NLTT vào sửa đổi hồ sơ đang ở trạng thái chờ bổ sung
B2: NLTT không gửi nộp bổ sung
B3: Vào tài khoản cán bộ xử lý, cán bộ xem lại hồ sơ đã yêu cầu bổ sung, cán bộ xem được nội dung hồ sơ đã sửa đổi.

**Comment by tragiangdt** [comment]
@trungnt-ksnb @khoahp 
Lỗi này xuất hiện lại

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
@trungnt-ksnb @khoahp 
- Trạng thái hồ sơ Chờ bổ sung không có nút Ghi lại
- NLTT tải file lên nhưng chưa gửi hồ sơ, CB vẫn xem được nội dung NLTT tải lên

**Comment by khoahp** [comment]
@trungnt-ksnb xem lại lỗi này nhé

**Comment by trungnt-ksnb** [comment]
@khoahp done

**Comment by tragiangdt** [comment]
@trungnt-ksnb em vừa test trên qa vẫn còn lỗi này ạ

**Comment by khoahp** [comment]
@trungnt-ksnb sửa cái này nhé, @tragiangdt theo dõi bug này.

**Comment by trungnt-ksnb** [comment]
@tragiangdt check lại nhé

**Comment by Hongnt31** [comment]
Vẫn còn lỗi

**Comment by Hongnt31** [comment]
@khoahp  @tragiangdt lỗi xảy ra ở đơn khai trực tuyến. Khi NLTT sửa lại form chưa gửi lại YCBS thì bên cán bộ đã nhận dk

**Comment by tragiangdt** [comment]
test done trên qa
