### ISSUE TITLE
Chưa lọc theo bước xử lý tại Màn hình quản lý danh sách các phiếu quy trình chờ xử lý cho người dùng cán bộ 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#319]
B1: Đăng nhập tài khoản cán bộ
B2: Chọn lọc theo bước xử lý tại Màn hình quản lý danh sách các phiếu quy trình chờ xử lý cho người dùng cán bộ 
B3: Lỗi không lọc được

**Comment by khoahp** [comment]
@trungnt-ksnb Trung confirm lại cái này xem nhé

**Comment by khoahp** [comment]
@trungnt-ksnb @tanhtanhvn chuyển sang rc-1.2 anh nhé

**Comment by tragiangdt** [comment]
@trungnt-ksnb  @khoahp  Chưa lọc theo Bước xử lý trên màn hình Hồ sơ chờ xử lý

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại nhé

**Comment by tragiangdt** [comment]
@khoahp @trungnt-ksnb 
TH có >1 bước xử lý trên màn hình Hồ sơ chờ xử lý thì check list Lọc theo bước xử lý không hiển thị tên bước xử lý nào cả

**Comment by khoahp** [comment]
@tragiangdt anh đóng bug này nhé
