### ISSUE TITLE
Trường nhập  "Địa chỉ thực hiện DVC cấp 3" trong màn hình quản lý thủ tục hành chính có độ dài quá ngắn

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#324]
B1: Đăng nhập tài khoản quản trị
B2: Vào quản lý thủ tục hành chính
B3: Thêm mới/sửa đổi 1 TTHC
B4: Lỗi: Trường nhập  "Địa chỉ thực hiện DVC cấp 3" trong màn hình quản lý thủ tục hành chính có độ dài quá ngắn

**Comment by khoahp** [comment]
@dunglt91  ưu tiên cái này em nhé

**Comment by tragiangdt** [comment]
test ok
