### ISSUE TITLE
Lỗi không xem được lại được tài liệu đính kèm 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#328]
TH1: Cán bộ không xem được file đính kèm do DN nộp
- Doanh nghiệp tải file đính kèm
- Doanh nghiệp nộp hồ sơ
- Đăng nhập tài khoản cán bộ, mở hồ sơ DN nộp, không xem được file đính kèm trong Nội dung hồ sơ

TH2: 
- Cán bộ xử lý tải lên giấy tờ kết quả, sau đó gửi lên lãnh đạo
- Lãnh đạo mở hồ sơ này, không xem lại được file kết quả mà cán bộ đã tải lên

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
