### ISSUE TITLE
Không hiển thị giấy tờ kết quả khi hồ sơ ở trạng thái kết thúc

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#329]
B1: Thực hiện xử lý hồ sơ thủ tục Thông báo tập trung kinh tế
B2; Cán bộ thực hiện tải tệp kết quả
B3: Kết thúc quy trình, trạng thái hồ sơ là keets thúc
B4: đăng nhập tài khoản doanh nghiệp
B5: Không hiển thị giấy tờ kết quả khi hồ sơ này

**Comment by khoahp** [comment]
@tragiangdt bị trùng bug em đóng lại nhé
