### ISSUE TITLE
Nhấn nút Ghi lại khi thêm mới 1 thao tác, hệ thống quay ra màn hình danh sách quy trình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#330]
B1: Đăng nhập tài khoản quản trị
B2: Vào 1 quy trình, thực hiện thêm mới thao tác hành động
B2: Nhấn nút Ghi lại, 
Lỗi hệ thống quay ra màn hình danh sách quy trình 
Mong muốn: hệ thống quay lại danh sách thao tác khi nhấn nút Ghi lại

**Comment by khoahp** [comment]
@dunglt91 dũng sửa lại theo yêu cầu BA nhé

**Comment by tragiangdt** [comment]
test done
