### ISSUE TITLE
Nội dung ghi chú của thông tin hồ sơ NLTT nhập không hiển thị trên phiếu xử lý hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#334]
B1: NLTT nhập thông tin hồ sơ
B2: NLTT nộp hồ sơ
B3: Đăng nhập tài khoản cán bộ xem thông tin hồ sơ
Nội dung ghi chú thông tin hồ sơ NLTT nhập không hiển thị trên phiếu xử lý hồ sơ

**Comment by khoahp** [comment]
@trungnt-ksnb

**Comment by khoahp** [comment]
@tragiangdt

**Comment by khoahp** [comment]
@trungnt-ksnb nội dung ghi chú của người nộp không hiển thị trên thông tin phiếu xử lý

**Comment by tragiangdt** [comment]
@trungnt-ksnb 
Nội dung ghi chú chưa hiển thị trên thông tin hồ sơ

**Comment by khoahp** [comment]
@trungnt-ksnb ông xem phần này có theo thiết kế kế chưa?

**Comment by tragiangdt** [comment]
@huymq NLTT nhập thông tin Ghi chú trong thông tin hồ sơ, bên cán bộ chưa xem thông thông tin này trên màn hình xem thông tin hồ sơ

**Comment by tragiangdt** [comment]
test done trên qa
