### ISSUE TITLE
Hệ thống quay lại màn hình danh sách hồ sơ khi doanh nghiệp thực hiện tải tệp

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#346]
B1: Đăng nhập tài khoản doanh nghiệp
B2: Thêm mới hồ sơ
B3: Tải 1 giấy đính kèm
B4: Trên màn hình tải tệp, nhấn Ghi lại
B5: Lỗi Hệ thống quay lại màn hình danh sách hồ sơ khi doanh nghiệp thực hiện tải tệp xong

**Comment by khoahp** [comment]
@tragiangdt re-test

**Comment by tragiangdt** [comment]
@trungnt-ksnb @khoahp 
Trên QA vẫn còn lỗi này

**Comment by khoahp** [comment]
@trungnt-ksnb Trung kiểm tra lại lỗi này trên màn hình chuẩn bị hồ sơ của người làm thủ tục

**Comment by tragiangdt** [comment]
test ok
