### ISSUE TITLE
Hash length extension attack in keypay

### ISSUE THREAD

**Issue by duongkai** [VietOpenCPS/opencps#347]
In the file

https://github.com/VietOpenCPS/opencps/blob/489bb995944f688e537c9ffe02e07b6cab168208/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/keypay/security/HashFunction.java

Class HashFunction.hashAllFields(Map fields, String SECURE_SECRET) will do like this to check the integrity of request:

```
sign = MD5 (SECRET + all_data_fields) 
```

in which SECRET is the secret key it wishes to input. 
Doing like this to check the integrity of request will lead to attack named "**hash length extension**", allows hacker will make a forgery request **without knowing the SECRET**. It is very old and famous attack.

Please refer this doc for getting more details: https://sites.google.com/a/tetcon.org/2012/program#TOC-16h05---16h50:-Nh-m-Xu-n-Nam---Mua-h-ng-kh-ng-m-t-ti-n---L-h-ng-trong-m-t-s-h-th-ng-thanh-to-n-tr-c-tuy-n-t-i-Vi-t-Nam-slide-paper-

Should switch to use HMAC in this case.

**Comment by khoahp** [comment]
@duongkai 

Xin cảm ơn bạn đã phát hiện và chỉ ra các lỗi liên quan đến việc thanh toán, cộng đồng OpenCPS đã tiếp nhận và fix lỗi này trong bản cập nhật sớm nhất 1.1 (15/06/2016).

**Comment by tuanta** [comment]
@nguyennv is working on implementing a new Payment abstract layer. He will also pay attention on this issue.

**Comment by sonna1990** [comment]
@duongkai 

KeyPay cám ơn bạn đã phát hiện và chỉ ra lỗi liên quan đến vấn đề bảo mật trong hệ thống.
Hiện tại nhóm kỹ thuật của KeyPay đang phối hợp cùng công ty Velatek kiểm tra lại vấn đề trên và sẽ có cập nhật trong vài ngày sắp tới.

**Comment by khoahp** [comment]
@duongkai cảm ơn anh đã góp ý, phần này đã chuyển lại yêu xử lý cho bên cung cấp dịch vụ thanh toán qua mạng
