### ISSUE TITLE
Backend xử lý - Hoàn thiện tiện ích về sinh mã số tiếp nhận theo parttern

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#353]

**Comment by khoahp** [comment]
@tragiangdt em test lại nhé

**Comment by tragiangdt** [comment]
@khoahp  vẫn còn lỗi sinh số tiếp nhận, khi chọn kiểu {yy}-{dd}.... thì số tiếp nhập hiện {yy}-09....

**Comment by tragiangdt** [comment]
Test ok

**Comment by khoahp** [comment]
Trường hợp nộp bổ xung hồ sơ không sinh ra mã tiếp nhận

**Comment by tragiangdt** [comment]
test done

**Comment by khoahp** [comment]
@tragiangdt sao không close được hả em

**Comment by tragiangdt** [comment]
Anh tạo issue này mà nên em ko close được.
