### ISSUE TITLE
Backend xử lý - Hoàn tiện ích sinh ngày hẹn trả

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#354]

**Comment by khoahp** [comment]
@trungnt-ksnb hiện tại đã có hàm sinh theo ngày hẹn trả, Trung xem gắn vào popup phiếu xử lý nhé

**Comment by khoahp** [comment]
@tragiangdt test lại. vì đã có trên 1.1 rồi.

**Comment by tragiangdt** [comment]
@khoahp Ngày hẹn trả chưa hiển thị được trên tab Thông tin hồ sơ

**Comment by khoahp** [comment]
@tragiangdt em test lại phần này nhé

**Comment by tragiangdt** [comment]
@khoahp 
Lỗi: Không cấu hình hoặc cấu hình ngày hẹn trả nhưng ngày hẹn trả luôn có dữ liệu là ngày gửi
![2016-09-23_173614](https://cloud.githubusercontent.com/assets/17695836/18783205/c6a86f3a-81b4-11e6-90f7-c7805419e57c.png)

**Comment by tragiangdt** [comment]
@khoahp 
Vẫn còn lỗi ạ. 
1. VD hôm thứ 2 lúc 10h sáng nộp hồ sơ
cáu hình ngày hẹn trả là 2 ngày, thì sẽ trả hồ sơ vào 10h hôm thứ 4
Hiện tại hiển thị giờ hẹn trả là giờ cán bộ xử lý
2. Chưa trừ ngày nghỉ lễ (đã trừ thứ 7 chủ nhật rồi)
3. TH cấu hình sinh ngày hẹn trả tại bước bắt đầu nhận hồ sơ trực tuyến
Cấu hình ngày hẹn trả: 
![2016-11-02_165200](https://cloud.githubusercontent.com/assets/17695836/19924027/c2b4d652-a11c-11e6-867e-01fe853a84a9.png)

Kết quả:
![2016-11-02_165308](https://cloud.githubusercontent.com/assets/17695836/19924055/dfec683e-a11c-11e6-906f-fb57633fb1cd.png)

**Comment by khoahp** [comment]
@nhan0987 em theo dõi bug này nhé

**Comment by Hongnt31** [comment]
@nhan0987  @khoahp 
Hiện tại cấu hình lần đầu thì được nhưng khi cấu hình lại thì bị lỗi

**Comment by khoahp** [comment]
@nhan0987 xem xu ly nhe

**Comment by Hongnt31** [comment]
@khoahp  @nhan0987  Test done
