### ISSUE TITLE
Hoàn thiện module thanh toán phía công dân 

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#358]

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra xem có vấn đề gì ở module này nữa không nhé

**Comment by tragiangdt** [comment]
@khoahp 
- Vẫn hiển thị hành động Thanh toán trực tuyến, Chuyển khoản của hồ sơ ở các trạng thái Đã báo nộp, Đã chứng thực, Đã hoành thành
- TH mở xem chi tiết hồ sơ có trạng thái hoàn thành thanh toán, các trường thông tin sau vẫn trắng:
  Tài khoản ngân hàng  
  Địa chỉ thanh toán
  Hình thức thanh toán  
  Ngày báo nộp  
  Chứng từ nộp kèm theo  
  Ngày giờ được xác nhận
