### ISSUE TITLE
Hoàn thiện module quản lý công dân/tổ chức

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#361]

**Comment by dunglt91** [comment]
@khoahp success

**Comment by khoahp** [comment]
@tragiangdt em rà soát lại một lượt các màn hình theo thiết kế của module quản lý công dân/tổ chức bao gồm:
1. Đăng ký tài khoản: form đăng ký, nội dung email trả về, quy trình kích hoạt
2. Quản lý: xem danh sách tài khoản, xem chi tiết, sửa tài khoản, xoá tài khoản

Các bug sau khi rà soát tách thành các issue nhỏ, trong comment thì add issue #361 vào nhé

**Comment by khoahp** [comment]
@tragiangdt xem lại một lần các chức năng này theo thiết kế nhé
