### ISSUE TITLE
Văn bản đính kèm (TTHC C2) không download được khi không đăng nhập

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#364]
- Trong module TTHC

**Comment by khoahp** [comment]
@dunglt91 add phân quyền khi thêm file nhé

**Comment by dunglt91** [comment]
@khoahp fixed

**Comment by tragiangdt** [comment]
@khoahp Trên con qa vẫn còn lỗi này

**Comment by khoahp** [comment]
@tragiangdt hiện tại những file cũ chỉ cấu hình thủ công để cập nhật lại, em update file mới lên rồi test với tài khoản không đăng nhập nhé

**Comment by tragiangdt** [comment]
@khoahp @dunglt91  Em đã tải file mới lên nhưng khi không đăng nhập vẫn không xem lại file này đâu anh a

**Comment by tragiangdt** [comment]
@khoahp  test done
