### ISSUE TITLE
Sửa màn hình quản lý cán bộ

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#365]
Sửa màn hình giao diện danh sách chức vụ, bỏ popup

https://github.com/VietOpenCPS/doc/raw/master/SRS/usermgt/usermgtjobposlist.png
#360 @dunglt91

**Comment by dunglt91** [comment]
@khoahp fixed

**Comment by khoahp** [comment]
@tragiangdt -> test

**Comment by tragiangdt** [comment]
@khoahp  
B1: Thêm mới 1 chức vụ
B2: Ghi lại
Lỗi: Màn hình hiển thị popup confirm 
![screenshot from 2016-06-07 11-28-21](https://cloud.githubusercontent.com/assets/17695836/15846016/3a0f19fe-2ca3-11e6-8f42-1fd3ce39b143.png)

**Comment by khoahp** [comment]
@tragiangdt @dunglt91

**Comment by dunglt91** [comment]
Mỗi lần tắt popup là mỗi lần gửi dữ liệu lên server để lưu thay đổi. Cái này ko phải là lỗi. Đề nghị @tragiangdt close issue

**Comment by tragiangdt** [comment]
@khoahp Anh close issue a
