### ISSUE TITLE
Màn hình sửa thông tin cán bộ

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#366]
Quản lý cán bộ, => click vào chi tiết cán bộ -> không hiển thị chi tiết trên form sửa cán bộ

**Comment by dunglt91** [comment]
fixed @khoahp

**Comment by dungtkfds** [comment]
click vào Thông tin tài khoản sau khi đăng nhập không ra màn hình sửa thông tin

**Comment by khoahp** [comment]
@tragiangdt 
1. Em kiếm tra lại module quản lý thông tin cán bộ trong  cơ quan, chức năng sửa.
2. Em bố trí thêm trang mới và cấu hình portlet sửa thông tin của tài khoản đăng nhập.

@dungtkfds đây là chức năng sửa tài khoản của User khi đăng nhập vào ạ. Bug này report cho lỗi của cán bộ quản lý tài khoản của cơ quan.
