### ISSUE TITLE
Cán bộ thực hiện click thao tác để chuyển bước, hệ thống không quay lại mà hình danh sách hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#374]
B1: Vào tài khoản cán bộ xử lý
B2: Vào 1 hồ sơ thực hiện xử lý
B3: Trong tab xử lý, cán bộ nhấn 1 thao tác, 
B4: Cán bộ nhấn nút Đồng ý trên popup xác nhận thực hiện
B5: sau khi nhấn nút đồng ý, hệ thống không quay ra màn hình danh sách hồ sơ

**Comment by khoahp** [comment]
@trungnt-ksnb Trung xem lại phần này nhé!

**Comment by tragiangdt** [comment]
test done
