### ISSUE TITLE
Không có chức năng nhập form dữ liệu cho thành phần giấy tờ kết quả

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#376]
B1: Đăng nhập cán bộ xử lý
B2: Vào 1 hồ sơ để xử lý
B3: Vào tab xử lý hồ sơ
B4: Không thấy có chức năng nhập vào form dữ liệu cho thành phần giấy tờ kết quả

**Comment by khoahp** [comment]
@tragiangdt em close bug này đi nhé, a Trung đã disable tạm chức năng này đi, chiều này sau khi cập nhật Module quản lý hồ sơ sẽ mở lại chức năng này.
