### ISSUE TITLE
Portlet 25 - Danh sách thông báo hồ sơ xử lý

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#377]
Thông báo:
- Hồ sơ mới tiếp nhận
- Hồ sơ mới hoàn thành
- Hồ sơ quá hạn xử lý

**Comment by khoahp** [comment]
@tanhtanhvn phần này giao lại cho dunglt anh nhé?

**Comment by tanhtanhvn** [comment]
OK, chuyển hết tất cả phần việc mà đường sắt chưa cần cho Dũng. Trung chỉ làm những phần hoàn thiện cho con đường sắt thôi.

**Comment by khoahp** [comment]
@dunglt91 em xử lý phần này nhé
