### ISSUE TITLE
Không lưu vết  thông tin cán bộ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#380]
B1: Vào tài khoản quản trị
B2: vào quản lý cán bộ
B2: Vào tab cán bột
B4: Nhấn sửa đổi 1 cán bộ
B5: các trường thông tin của cán bộ đều trắng

**Comment by dunglt91** [comment]
@tragiangdt @khoahp fixed

**Comment by tragiangdt** [comment]
Test done
