### ISSUE TITLE
Không xem được lịch sử xử lý hồ sơ ở tài khoản cán bộ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#386]
B1: Đăng nhập tài khoản cán bộ
B2: Vào 1 hồ sơ
B3: Lỗi không xem được lịch sử xử lý hồ sơ

**Comment by dunglt91** [comment]
@khoahp  @tragiangdt  fixed

**Comment by dungtkfds** [comment]
Chưa thấy lỗi này được fix trên qa

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại phần này nhé.

http://qa.opencps.vn/group/guest/quan-ly-ho-so?p_p_id=16_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_16_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fprocessmgt%2Fprocessorder%2Fprocess_order_detail.jsp&_16_WAR_opencpsportlet_processOrderId=3202&_16_WAR_opencpsportlet_backURL=%2Fgroup%2Fguest%2Fquan-ly-ho-so#_16_WAR_opencpsportlet_tab=_16_WAR_opencpsportlet_history

**Comment by tragiangdt** [comment]
@dunglt91  Ngày thực hiện định dạng theo hh:mm dd/mm/yyyy
- Danh sách lịch sử chưa hiển thị ngày nộp hồ sơ

**Comment by tragiangdt** [comment]
@dunglt91  Hôm nay không xem được lịch sử xử lý hồ sơ

**Comment by tragiangdt** [comment]
@dunglt91 @khoahp Giờ vẫn chưa xem lịch sử a.

**Comment by tragiangdt** [comment]
test done
