### ISSUE TITLE
Chọn chế độ "Thành phần phía công dân và cán bộ xử lý" khi cấu hình dịch vụ công bị lỗi

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#393]
B1: Vào tài khoản quản trị
B2: Vào link quản trị http://qa.opencps.vn/group/guest/quan-tri
B3: Vào menu Dịch vụ công mức 3
B4: Vào tab Dịch vụ công
B5: Chọn cập nhật cấu hình 1 dịch vụ công
B6: Chọn chế độ "Thành phần phía công dân và cán bộ xử lý" khi cấu hình dịch vụ công bị thông báo lỗi "Cơ quan không có trong tổ chức nào "

**Comment by dunglt91** [comment]
@tanhtanhvn  @tragiangdt  @tragiangdt #393
Khi chọn chế độ có tồn tại BACK OFFICE thì cơ quan đó phải có trong tổ chức, theo thiết kế là vậy (nghĩa là có trong working unit), hiện tại cục đường sắt chỉ mới có trong danh mục (DATA ITEM) mà không có trong WORKING UNIT nên mới bị báo đỏ.

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại phần này rồi đóng issue lại nhé

**Comment by tragiangdt** [comment]
Test ok
