### ISSUE TITLE
Vẫn hiển thị nút thao tác trên màn hình xử lý khi đó là thao tác kết thúc quy trình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#394]
Trong màn hình cấu hình quy trình, cấu hình thao tác "Trả kết quả", bước sau thực hiện = 0
Trong màn hình xử lý hồ sơ, vẫn hiển thị nút Trả kết quả

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
@trungnt-ksnb  @khoahp  Vẫn còn lỗi anh ạ

**Comment by khoahp** [comment]
@trungnt-ksnb kiểm tra điều kiện hiển thị nút. Nếu bước sau (postStepId = 0) thì không hiển thị.

**Comment by tragiangdt** [comment]
Không phải lỗi. Nếu bước sau postStepId = 0) thì chuyển trạng thái hồ sơ thành kết thúc, vẫn hiển thị thao tác.
