### ISSUE TITLE
Không hiển thị danh sách thủ tục hành chính khi thêm mới hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#395]
B1: Đăng nhập tài khoản quản trị, Cập nhật cấu hình dịch vụ công, chọn chế độ loại 3 "Thành phần phía công dân và cán bộ xử lý"
B2: Đăng nhập tài khoản Doanh nghiệp, thêm mới hồ sơ
B3: Lỗi Không hiển thị danh sách thủ tục hành chính khi thêm mới hồ sơ

**Comment by khoahp** [comment]
@tragiangdt phần này anh TrungNT đã tiếp nhận và xử lý nhé.

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
Done

**Comment by tragiangdt** [comment]
@trungnt-ksnb 
Hôm nay khi thực hiện thêm mới hồ sơ, hệ thống không hiển thị danh sách thủ tục hành chính để thêm hồ sơ.
