### ISSUE TITLE
Xóa tệp đính kèm thành phần hồ sơ mẫu trực tuyến thì nội dung khi khai đơn trực tuyến cũng bị xóa

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#396]
B1: Vào tài khoản doanh nghiệp/ Thêm mới hồ sơ
B2: Vào Khai trực tuyến
B3: Nhấn ghi lại, sau đó nhấn "xuất file"
B4: Xóa tệp đính kèm của đơn
B5: Lỗi: Xóa tệp đính kèm thành phần hồ sơ mẫu trực tuyến thì nội dung khi khai đơn trực tuyến cũng bị xóa

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
Phần này có thiết kế mới. Hiện tại các thành phần được lưu dưới dạng version chứ không xóa hẳn. Trà Giang xem lại nhé

**Comment by tragiangdt** [comment]
Đã đổi thiết kế, khai trực tuyến thì không có tải tệp đính kèm
