### ISSUE TITLE
Sửa giao diện màn hình thành phần hồ sơ khi người làm thủ tục tạo mới hồ sơ

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#397]
- Vào: http://qa.opencps.vn/home
- Chọn Đăng nhập, đăng nhập bằng tài khoản:
  doanhnghiep.cps@gmail.com/cps12345
- Chọn Không gian làm việc
- Chọn Thêm mới hồ sơ
- Chọn Thêm
- Chọn Thành phần hồ sơ
- Trong màn hình Thành phần hồ sơ, sửa lại giao diện:
  1. Sửa lại menu bên phải như hình (Màn hình: DN_003_QLHS – Thành phần hồ sơ)
  2. Sửa lại khoảng cách giữa các thành phần như hình (Màn hình: DN_003_QLHS – Thành phần hồ sơ)
  3. Để mặc định chủ hồ sơ là tên của tài khoản đăng nhập (Màn hình: DN_002_QLHS – Thông tin hồ sơ)
- Sửa lại các thành phần màn hình như file html(Màn hình: DN_002_QLHS – Thông tin hồ sơ)
- **File màn hình:** 
  [https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh](https://github.com/vuminhcuong/doc/tree/cuong_master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh)

**Comment by khoahp** [comment]
@vuminhcuong em trao đổi với anh @tanhtanhvn về giao diện màn hình này nhé, nếu đã được duyệt anh sẽ bố trí người làm.

**Comment by vuminhcuong** [comment]
@khoahp Anh Tuấn Anh đã duyệt các màn hình sau:
1. DN_001_QLHS – Danh sách hồ sơ
2. DN_002_QLHS – Thông tin hồ sơ
3. DN_003_QLHS – Thành phần hồ sơ
4. DN_004_QLHS – Chọn thủ tục nộp hồ sơ
Anh Khoa bố trí người làm ạ

**Comment by khoahp** [comment]
@vuminhcuong anh đã cập nhật đầu việc sửa lại giao diện thiết kế tại 2 issues #398 và #400 em close issues này giúp anh nhé
