### ISSUE TITLE
Hoàn thiện giao diện màn hình theo thiết kế mới

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#400]
Hoàn thiện các giao diện màn hình sau
1. DN_002_QLHS – Thông tin hồ sơ
2. DN_003_QLHS – Thành phần hồ sơ
3. DN_004_QLHS – Chọn thủ tục nộp hồ sơ

@dunglt91 đầu việc này thực hiện sau khi anh Trung đã chuẩn hóa theme nhé, em ưu tiên đầu việc khác trước nhé

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tanhtanhvn** [comment]
Chuyển sang 1.3, chờ thiết kế mới của giao diện. Chỉ cần làm đúng, đủ các chức năng theo mockup.
