### ISSUE TITLE
Không thêm được tài khoản cán bộ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#409]
B1: Vào tài khoản quản trị
B2: vào quản lý cán bộ
B2: Vào tab cán bộ
B4: Thêm mới cán bộ
B5: Nhập các thông tin cán bộ, nhấn Ghi lại đều báo lỗi Yêu cầu không được xử lý thành công

**Comment by khoahp** [comment]
@dunglt91 thêm thẻ validator cho màn hình thêm

**Comment by khoahp** [comment]
@dunglt91 phần này bổ xung chưa Dũng ơi?

**Comment by tragiangdt** [comment]
tesst done
