### ISSUE TITLE
Không xem lại được file đính kèm biểu mẫu thủ tục

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#410]
B1: Đăng nhập tài khoản quản trị
B2: Vào link http://qa.opencps.vn/group/guest/quan-tri
B3: Vào quản lý thủ tục hành chính
B4: Vào tab Biểu mẫu thủ tục
B5: Chọn xem lại 1 biểu mẫu
Lỗi: - Không xem lại được file đính kèm biểu mẫu thủ tục
- Không sửa được biểu mẫu thủ tục

**Comment by khoahp** [comment]
@dunglt91 xem lại anh bug này nhé. Phần dịch vụ công cấp 2

**Comment by khoahp** [comment]
@dunglt91 trả lời anh phần này nhé

**Comment by tragiangdt** [comment]
test ok
