### ISSUE TITLE
Không hiển thị chủ hồ sơ trên danh sách Quản lý yêu cầu thu phí

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#416]
B1: Đăng nhập bằng tài khoản quản trị
B2: Vào http://qa.opencps.vn/group/guest/quan-ly-yeu-cau-thu-phi
Không hiển thị chủ hồ sơ trên danh sách Quản lý yêu cầu thu phí

**Comment by khoahp** [comment]
@tragiangdt em test lại nhé

**Comment by tragiangdt** [comment]
test done
