### ISSUE TITLE
Hiển thị sai phương thức thanh toán trên danh sách quản lý yêu cầu thu phí

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#417]
B1: Đăng nhập bằng tài khoản quản trị
B2: Vào http://qa.opencps.vn/group/guest/quan-ly-yeu-cau-thu-phi
Lỗi: -  Trên màn hình danh sách lúc nào cũng hiển thị phương thức thanh toán là tiền mặt (Chưa theo thiết kế)

**Comment by khoahp** [comment]
@tragiangdt em test lại nhé

**Comment by tragiangdt** [comment]
@khoahp 
Trên con qa hiện không hiển thị mặc định Phương thức thanh toán Tiền mặt nữa, nhưng bây giờ cột phương thức thanh toán lại trắng, ko ghi nhận ddc phương thức thanh toán

**Comment by khoahp** [comment]
@trungnt-ksnb phần này select cho chạy hàm tìm kiếm nhưng kết quả sai. Trung xem lại, chuyển qua 1.2 nhé

**Comment by tragiangdt** [comment]
@binhth

**Comment by tragiangdt** [comment]
@khoahp  Vẫn hiển thị sai anh a

**Comment by dunglt91** [comment]
@tragiangdt Giang miêu tả rõ lại sai như thế nào giúp tớ nhé

**Comment by tragiangdt** [comment]
@dunglt91  
- Khi trạng thái của phiếu thanh toán là Hoàn thành, dựa vào hình thức nộp tiền của doanh nghiệp mà có phương thức thanh toán tương ứng.
  TH kế toán xác nhận thu tiền mặt: phương thức thanh toán là Tiền mặt
  TH chuyển khoản: phương thức thanh toán là Chuyển khoản
  TH thanh toán trực tuyến: phương thức thanh toán là Trực tuyến
  TH trạng thái phiếu thanh toán không = hoàn thành: để trống
- Hiện tại là trường phương thức đang trống trong tất cả các TH

**Comment by khoahp** [comment]
@tragiangdt xem lại bug này ntn

**Comment by khoahp** [comment]
@dunglt91 xem lại bug này xem

**Comment by binhth** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
