### ISSUE TITLE
Không thanh toán trực tuyến được treen danh sách yêu cầu thanh toán

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#419]
B1: Vào tk quản trị
B2: vào http://qa.opencps.vn/group/guest/danh-sach-yeu-cau-thanh-toan
B3: Lọc hồ sơ có trạng thái Chờ nộp
B4: Chọn hành động nộp Trực tuyến
Lỗi không click được nút Trực tuyến

**Comment by khoahp** [comment]
@tragiangdt thanh toán trực tuyến được em cần cấu hình:
1. Địa chỉ trả về của thanh toán trực tuyến (Đăng nhập vào tk quản trị -> modulde hồ sơ -> vào cấu hình -> chọn trang trả về khi thanh toán trực tuyến)
2. Cấu hình chuỗi pattern thanh toán trực tuyến trong cấu hình quy trình
3. Cấu hình thông tin thanh toán trong module thanh toán 

Em test lại nhé

**Comment by tragiangdt** [comment]
Test done
