### ISSUE TITLE
Cập nhật lại cấu hình ServiceConfig

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#422]
- @dunglt91 Cập nhật lại cấu hình service config theo thiết kế mới 
- @trungnt-ksnb Cập nhật lại phần lấy danh sách thủ tục theo service config

**Comment by khoahp** [comment]
Phần này @dunglt91  đã làm xong phần cấu hình @trungnt-ksnb xem có kịp làm nốt phần lọc thủ tục theo cấu hình mới cho rc-1.1 không?

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test ok

**Comment by khoahp** [comment]
Okie. Anh cloé vào nhé! Thank all.
