### ISSUE TITLE
Chưa check những thành phần hồ sơ được cấu hình bắt buộc khi nộp hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#424]
B1: Cấu hình thành phần hồ sơ bắt buộc
B2: Vào tài khoản DN, thêm mới hồ sơ
B3: Không nhập thành phần hồ sơ nào cả, nhấp ghi lại và gửi nộp hồ sơ thành công
Lỗi Chưa check những thành phần hồ sơ được cấu hình bắt buộc khi nộp hồ sơ

**Comment by khoahp** [comment]
@tanhtanhvn phần này đội DEV xin chuyển qua release 1.2 ạ?

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
Done

**Comment by tragiangdt** [comment]
test ok
