### ISSUE TITLE
Chưa lấy được tên Chủ hồ sơ trên màn hình chuẩn bị hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#425]
B1: Đăng nhập tk DN
B2: Thêm mới hồ sơ
B3: Lỗi Chưa lấy được tên Chủ hồ sơ trên màn hình chuẩn bị hồ sơ
![screenshot from 2016-06-09 10-16-52](https://cloud.githubusercontent.com/assets/17695836/15917953/c19cf4e8-2e2b-11e6-90c7-7ad1d1ba4f89.png)

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
Do tài khoản doanh nghiệp bị mất thông tin(cụ thể là mất tên do liên quan đến bug #437), Cập nhật lại thông tin tài khoản doanh nghiệp là được
Done

**Comment by tragiangdt** [comment]
@trungnt-ksnb Em đã sửa thông tin doanh nghiệp (tk   doanhnghiep.cps@gmail.com) rồi, nhưng khi đăng nhập tài khoản DN, sau đó thêm mới hồ sơ vẫn không hiển thị tên chủ hồ sơ

**Comment by tragiangdt** [comment]
test done
