### ISSUE TITLE
Portlet 26 - Tiếp nhận hồ sơ dịch vụ công

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#430]
Hướng dẫn tiếp nhận hồ sơ dịch vụ công theo cơ quan và mức độ cung cấp của dịch vụ.

**Comment by tanhtanhvn** [comment]
@dangkhanhtrung : Trung sắp xếp làm chức năng này để hỗ trợ người làm thủ tục tìm kiếm thông tin và thực hiện nộp hồ sơ dễ dàng hơn trên cổng thông tin

**Comment by khoahp** [comment]
@dangkhanhtrung anh ới, anh xem phần này có kịp cho việc tích hợp vào rc-1.1 hay không? Hay chỉ kịp phục vụ cho phần đường sắt demo? Nếu không kịp cho vào rc-1.2 anh @tanhtanhvn và anh @dangkhanhtrung  nhé?

**Comment by dangkhanhtrung** [comment]
Phần này không kịp cho rc-1.1. Phục vụ đường sắt demo anh làm portlet 23 cơ. Đã xong để demo sẽ cho lại vào kho chính ở rc-1.2.

**Comment by tanhtanhvn** [comment]
Trung chỉ cần làm phần trả kết quả để dùng cho con đường sắt. Phần tiếp nhận hồ sơ thì để Trung to con làm

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
Đã xong
