### ISSUE TITLE
Doanh nghiệp luôn nhận được giấy tờ kết quả sau khi cán bộ upload file kết quả

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#431]
Doanh nghiệp luôn nhận được giấy tờ kết quả sau khi cán bộ upload file kết quả, hồ sơ chưa được xử lý đến bước cấu hình trả kết quả về nhưng DN vẫn nhận ddc kq

**Comment by khoahp** [comment]
@trungnt-ksnb Trung xem lại phần lấy kết quả đầu ra đã dựa trên cờ syncStatus chưa nhé. Trong backend xử lý (SyncFromBackoffice.java) line 78->84 là đoạn cập nhật kết quả đồng bộ hồ sơ.

**Comment by khoahp** [comment]
@tragiangdt lỗi này chiều nay em test.
