### ISSUE TITLE
Trạng thái của phiếu thanh toán chưa đúng

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#452]
Sửa lại trang thái của phiếu thanh toán chỉ có 4 trường hợp: 0-requested (chờ nộp); 1-confirmed (báo nộp); 2-approved (hoàn thành); 3-rejected (không hợp lệ).
Thay đổi tiêu đề "Tất cả trạng thái" bằng "Lọc theo trạng thái phiếu thanh toán". Khi lần đầu mở phải hiển thị danh sách tất cả các trạng thái.
Bổ sung trường syncStatus dùng để kiểm soát việc đồng bộ phiếu thanh toán giữa 2 hệ thống.

**Comment by tragiangdt** [comment]
@binhth

**Comment by khoahp** [comment]
@dunglt91 em trao đổi với @tragiangdt  về phần này nhé

**Comment by dunglt91** [comment]
Phan nay de nghe @tragiangdt test lai, anh @dangkhanhtrung  da sua roi ma, de y test roi dong issue nhe

**Comment by tragiangdt** [comment]
@khoahp 
1. Sửa lại trang thái của phiếu thanh toán chỉ có 4 trường hợp: 0-requested (chờ nộp); 1-confirmed (báo nộp); 2-approved (hoàn thành); 3-rejected (không hợp lệ).
-> Trên danh sách quản lý thu phí của cán bộ, không hiển thị đúng tên trạng thái
2. Thay đổi tiêu đề "Tất cả trạng thái" bằng "Lọc theo trạng thái phiếu thanh toán". Khi lần đầu mở phải hiển thị danh sách tất cả các trạng thái.
-> Trên danh sách quản lý thu phí của cán bộ: Chưa có "Lọc theo trạng thái phiếu thanh toán"
3. Bổ sung trường syncStatus dùng để kiểm soát việc đồng bộ phiếu thanh toán giữa 2 hệ thống.
-> Không test trên giao diện được

**Comment by binhth** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
1. Trạng thái của phiếu thanh toán đã có 4 trường hợp: 0-requested (chờ nộp); 1-confirmed (báo nộp); 2-approved (hoàn thành); 3-rejected (không hợp lệ).
2. Thay đổi tiêu đề "Tất cả trạng thái" bằng "Lọc theo trạng thái phiếu thanh toán". Khi lần đầu mở phải hiển thị danh sách tất cả các trạng thái.

**Comment by binhth** [comment]
@tragiangdt ??? còn gì nữa.

**Comment by tragiangdt** [comment]
test done

**Comment by tragiangdt** [comment]
@khoahp test done
