### ISSUE TITLE
Hiển thị cơ quan và sắp xếp trong danh sách phiếu thanh toán

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#453]
Cơ quan của phiếu thanh toán phải là cơ quan thực hiện thủ tục.
Các phiếu thanh toán luôn được sắp xếp ưu tiên theo thời gian cập nhật. Phiếu nào được cập nhật mới nhất thì hiển thị lên đầu tiên.
Chú ý khi thực hiện một thao tác thanh toán phải có thông báo kết quả và phiếu được cập nhật mới nhất phải được hiển thị lên đầu danh sách.

**Comment by tragiangdt** [comment]
@binhth

**Comment by tragiangdt** [comment]
@khoahp Phiếu được cập nhật mới nhất chưa hiển thị lên đầu danh sách trong porlet Quản lý yêu cầu thu phí
(Trên Danh sách yêu cầu thanh toán phí, Phiếu được cập nhật mới nhất Đã hiển thị lên đầu danh sách)

**Comment by khoahp** [comment]
@dunglt91 em sửa phần này theo thiết kế nhé

**Comment by tragiangdt** [comment]
test ok

**Comment by tragiangdt** [comment]
@khoahp Phiếu được cập nhật mới nhất chưa hiển thị lên đầu danh sách trong porlet Quản lý yêu cầu thu phí (Trên Danh sách yêu cầu thanh toán phí, Phiếu được cập nhật mới nhất Đã hiển thị lên đầu danh sách)
Lỗi này trước em test đã ok r, nhưng bây giờ lỗi đã lặp lại

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
@dunglt91 Dũng xem lại nhé

**Comment by dunglt91** [comment]
@tragiangdt  xem lại nhé

**Comment by tragiangdt** [comment]
@dunglt91 Trên con qa hiện vẫn lỗi 
"Phiếu được cập nhật mới nhất chưa hiển thị lên đầu danh sách trong porlet Quản lý yêu cầu thu phí (Trên Danh sách yêu cầu thanh toán phí, Phiếu được cập nhật mới nhất Đã hiển thị lên đầu danh sách)
Lỗi này trước em test đã ok r, nhưng bây giờ lỗi đã lặp lại"

**Comment by khoahp** [comment]
@dunglt91 xem xem lại hàm finder xem order theo cái nào nhé

**Comment by dunglt91** [comment]
@khoahp em xem code đã có order theo ngày rồi, @tragiangdt test kĩ xem, trước nó ok rồi mà @@!

**Comment by tragiangdt** [comment]
@dunglt91 @khoahp 
Trên qa vẫn bị lỗi sắp xếp 
Phiếu được cập nhật mới nhất chưa hiển thị lên đầu danh sách trong porlet Quản lý yêu cầu thu phí.

**Comment by khoahp** [comment]
@tragiangdt  anh chuyển lên 1.5 nhé

**Comment by dunglt91** [comment]
@huymq anh assign cho anh @binhth cái này anh nhé

**Comment by binhth** [comment]
@tragiangdt 
giải pháp: cập nhật trường modifieddate khi thao tác với phiếu thanh toán

**Comment by tragiangdt** [comment]
@khoahp Trên qa vẫn bị lỗi sắp xếp
Phiếu được cập nhật mới nhất chưa hiển thị lên đầu danh sách trong porlet Quản lý yêu cầu thu phí.

**Comment by tragiangdt** [comment]
@khoahp 
Theo yêu cầu của @binhth  thì phải xóa hết các phiếu yêu cầu thanh toán cũ thì mới test được lỗi "Phiếu được cập nhật mới nhất chưa hiển thị lên đầu danh sách trong porlet Quản lý yêu cầu thu phí." anh ạ. Anh vào DB xóa hết phiếu thanh toán giúp em ạ

**Comment by khoahp** [comment]
@huymq xem nhé

**Comment by Hongnt31** [comment]
@tragiangdt  @khoahp  Test done
