### ISSUE TITLE
Portlet - ID 24: Tra cứu xem log xử lý hồ sơ dành cho admin

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#456]
Xem chi tiết yêu cầu thiết kế tại

https://github.com/VietOpenCPS/doc/wiki/Ph%C3%A2n-t%C3%ADch-qu%E1%BA%A3n-l%C3%BD-h%E1%BB%93-s%C6%A1

**Comment by tragiangdt** [comment]
Đã xong
