### ISSUE TITLE
Portlet - ID 25: Danh sách thông báo hồ sơ xử lý

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#457]
@dunglt91 xem chi tiết thiết kế tại 

https://github.com/VietOpenCPS/doc/wiki/Ph%C3%A2n-t%C3%ADch-qu%E1%BA%A3n-l%C3%BD-h%E1%BB%93-s%C6%A1

**Comment by khoahp** [comment]
@tragiangdt fixed

**Comment by tragiangdt** [comment]
test ok

**Comment by tragiangdt** [comment]
Đã xong
