### ISSUE TITLE
Chưa đặt tên bước bắt đầu và kết thúc trong quy trình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#463]
B1: Vào tài khoản quản trị
B2: Vào xem chi tiết 1 quy trình
B3: Vào tab Thao tác
Lỗi chưa có bước bắt đầu và kết thúc để chọn khi cấu hình.
![2016-06-16_loi buoc bat dau kt](https://cloud.githubusercontent.com/assets/17695836/16108797/8dc65c50-33cf-11e6-8bf8-5889b11f61f2.png)

**Comment by khoahp** [comment]
@dunglt91 
- Tại thao tác, khi preStepId = 0 => Bắt đầu
- Khi postStepId = 0 => Kết thúc

**Comment by dunglt91** [comment]
@khoahp @tragiangdt done!

**Comment by khoahp** [comment]
@tragiangdt cái này em test lại nhé

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
test done
