### ISSUE TITLE
Kích hoạt tự động thực hiện theo lịch 5phút/lần chưa chạy

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#464]
B1: Đăng nhập tài khoản quản trị trên qa 
B2: Vào cấu hình điều kiện thực hiện payok, chọn kích hoạt tự động thực hiện thao lịch 5phút/lần
và cấu hình trả kết quả về tại bước này
B3: Chạy hồ sơ sử dụng quy trình này, DN thanh toán thành công, 
Lỗi: 5 phút sau hồ sơ không nhận được kết quả trả về như đã cấu hình

**Comment by khoahp** [comment]
@tragiangdt fixed

**Comment by tragiangdt** [comment]
test done
