### ISSUE TITLE
Lỗi gửi hồ sơ thành công nhưng trên ds vẫn hiển thị trạng thái Mới

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#465]
B1: Đăng nhập tài khoản DN
B2: Tạo mới hồ sơ
B3: Ra ngoài danh sách quản lý hồ sơ, nhấn nút gửi hồ sơ
B4: Lỗi gửi hồ sơ thành công nhưng trên ds vẫn hiển thị trạng thái Mới. 
Phải refresh lại trang quản lý hồ sơ thì hồ sơ mới đổi trạng thái
![2016-06-16_gui hs](https://cloud.githubusercontent.com/assets/17695836/16110757/843f2a2c-33d9-11e6-853d-7078d133c5f3.png)

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
