### ISSUE TITLE
Hồ sơ không chuyển sang trạng thái kết thúc

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#466]
Cán bộ xử lý thực hiện nhấn thao tác (thao tác, hành động có bước sau xử lý là bước kết thúc), thì 
Lỗi: - hồ sơ không chuyển trạng thái sang kết thúc.
- trên màn hình của cán bộ xử lý không thay đổi gì, hồ sơ không mất khỏi danh sách Hồ sơ chờ xử lý của cán bộ

**Comment by khoahp** [comment]
@tragiangdt xem lại chức năng này nhé

**Comment by tragiangdt** [comment]
@khoahp  
TH: trong 1 quy trình có nhìu luồng xử lý khác nhau để kết thúc quy trình (trên danh sách thao tác có >1 bước sau xử lý là bước kết thúc) thì vẫn bị lỗi như trên.

**Comment by khoahp** [comment]
@tragiangdt fixed

**Comment by tragiangdt** [comment]
test done
