### ISSUE TITLE
Không lưu vết  thông tin cập nhật cấu hình dịch vụ công

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#467]
B1: Đăng nhập tài khoản quản trị, vào cấu hình dịch vụ công cấp 3
B2: Vào tab Cấu hình dịch vụ công
B3: Vào sửa đổi 1 dvc
B4: tích chọn các chế độ: Cổng tiếp nhận, tiếp nhận 1 cửa, công dân nộp hs, DN nộp hồ sơ,...
Nhấn ghi lại, hệ thống thông báo yêu cầu xử ly thành công
Lỗi: - Mở xem chi tiết, Không lưu vết  tcác thông tin trên
- Không nhập dữ liệu vào trường bắt buộc vẫn lưu thành công
  @dunglt91 

![2016-06-16_cap nhat ch dvc](https://cloud.githubusercontent.com/assets/17695836/16111565/506f3918-33dd-11e6-9dc3-8ece9976e283.png)

**Comment by khoahp** [comment]
@dunglt91 sửa gấp lỗi này em ơi

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
