### ISSUE TITLE
Lỗi phân trang trên danh sách thao tác trên quy trình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#469]
Không xem được trang 2 của danh sách thao tác trong quy trình
Kích vào trang 2, hệ thống báo:
@khoahp 
![screenshot from 2016-06-16 17-07-12](https://cloud.githubusercontent.com/assets/17695836/16113102/e0ea1678-33e4-11e6-8750-b7ed5bc6d9ea.png)

![screenshot from 2016-06-16 17-06-21](https://cloud.githubusercontent.com/assets/17695836/16113067/b5e517f2-33e4-11e6-88f7-563c810a0829.png)

**Comment by khoahp** [comment]
@tragiangdt fixed

**Comment by tragiangdt** [comment]
Đã hiển thị 100 bản ghi trong 1 trang
