### ISSUE TITLE
TH lãnh đạo yêu cầu kiểm tra lại, hệ thống chưa trả hồ sơ về đúng cho cán bộ vừa mới xử lý hồ sơ này

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#477]
TH lãnh đạo yêu cầu kiểm tra lại, hệ thống chưa trả hồ sơ về đúng cho cán bộ vừa mới xử lý hồ sơ này

**Comment by tragiangdt** [comment]
@khoahp @huymq Lỗi này từ lâu rồi, các anh ưu tiên sửa trước nhé

**Comment by khoahp** [comment]
@tragiangdt em test lại lỗi này nhé

**Comment by tragiangdt** [comment]
@khoahp Lỗi này chưa được anh nhé

**Comment by tragiangdt** [comment]
test done trên qa

**Comment by tragiangdt** [comment]
@khoahp  Vẫn còn TH NLTT nộp bổ sung hồ sơ, hệ thống chưa gán cho cán bộ đã xử lý hồ sơ này (cán bộ vừa mới xử lý hs này)

**Comment by tragiangdt** [comment]
tesst done tren qa
