### ISSUE TITLE
Không lưu vết trường Phân công cán bộ xử lý trên màn hình cấu hình thao tác

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#486]
B1: Đăng nhập tài khoản quản trị
B2: Vào 1 quy trình
B3: Vào sửa đổi 1 thao tác
B4: Sửa đổi người xử lý. Sau đó nhấn Ghi lại
Lỗi: Không lưu vết trường Phân công cán bộ xử lý trên màn hình cấu hình thao tác
@dunglt91

**Comment by dunglt91** [comment]
@khoahp fixed

**Comment by tragiangdt** [comment]
Test done
