### ISSUE TITLE
Lỗi create file form nhập trực tuyến nhiều lần

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#487]
Lỗi create file ĐƠN nhiều lần. thực hiện :
bước1. Khi khai xong 1 mẫu form nhập trực tuyến chọn ghi lại  -> Chọn tiếp create file(lần 1)
bước 2. Vào sửa mẫu đơn trên và ghi lại->Chọn create file (lần thứ 2) => Báo lỗi Yêu cầu của bạn đã được xử lý không thành công.

**Comment by tragiangdt** [comment]
@trungnt-ksnb Vẫn lỗi như vậy a

**Comment by tragiangdt** [comment]
@trungnt-ksnb   sửa form và create file lần thứ 3, thứ 4 thì bị lỗi

**Comment by khoahp** [comment]
@trungnt-ksnb xem sớm phần này nhé

**Comment by trungnt-ksnb** [comment]
@tragiangdt Giang xem lại phần này nhé, hiện tại anh ko tái hện được lỗi này theo mô tả ơ trên

**Comment by tragiangdt** [comment]
Tesst done
