### ISSUE TITLE
Lỗi duplicate hồ sơ trên danh sách Hồ sơ chờ xử lý

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#488]
B1: Vào tài khoản văn thư tiếp nhận hồ sơ, trên popup xác nhận chọn  phân công công người xử lý tiếp theo là Lãnh đạo (Trong cấu hình quy trình: không tích chọn phân công người xử lý ở Bước tiếp nhận hồ sơ)
B2: Vào tài khoản lãnh đạo, vào màn hình danh sách hồ sơ chờ xử lý 
Lỗi duplicate hồ sơ trên danh sách Hồ sơ chờ xử lý

**Comment by khoahp** [comment]
@trungnt-ksnb chuyển sang 1.3 nhé

**Comment by tragiangdt** [comment]
@huymq @khoahp Lỗi này hôm nay lại xuất hiện lại trên qa

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại lỗi này

**Comment by tragiangdt** [comment]
Lỗi này để trạng thái theo dõi thui anh.

**Comment by tragiangdt** [comment]
@khoahp Anh tạo thêm 1 nhãn theo dõi r gán cho issue này ạ

**Comment by khoahp** [comment]
@tragiangdt okie em, anh đã tạo nhãn theo dõi rồi nhé

**Comment by tragiangdt** [comment]
@khoahp Sau khi click vào nút Ghi lại tren popup xác nhận chuyển bước xử lý, nhấn F5 1 lần nữa,  trên màn hình người được lựa chọn xử lý tiếp theo sẽ hiển thị 2 phiếu xử lý

**Comment by trungnt-ksnb** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
