### ISSUE TITLE
Lỗi: Người không được phân công xử lý, nhưng vẫn vào xử lý được hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#489]
B1: Vào cấu hình quy trình, tại bước bắt đầu, gán phân công người xử lý là người xử lý 1
B2: DN tạo hồ sơ -> nộp hồ sơ
B3: Người xử lý 2 ở cùng role với người xử lý 1, vào tab Xử lý hồ sơ, các nút thao tác không bị disable.
Lỗi: Người không được phân công xử lý, nhưng vẫn vào xử lý được hồ sơ

**Comment by trungnt-ksnb** [comment]
@tragiangdt 
Done

**Comment by tragiangdt** [comment]
@khoahp  @trungnt-ksnb 
Vẫn còn lỗi này anh nhé

**Comment by trungnt-ksnb** [comment]
![screenshot from 2016-07-19 00-11-14](https://cloud.githubusercontent.com/assets/17334393/16923637/6e14cc4a-4d45-11e6-944b-a34eed517d1b.png)

![screenshot from 2016-07-19 00-12-18](https://cloud.githubusercontent.com/assets/17334393/16923652/7cc5d66c-4d45-11e6-8521-ad73448070d3.png)

@tragiangdt  Em test lại nhé, anh test lại vẫn thấy đúng

**Comment by trungnt-ksnb** [comment]
Lưu ý với đội test là mọi người phải luôn phân biệt rõ ràng là các issue OpenCPS ko liên quan gì đến các dự án. Mình thấy một số issue được test trên các dự án rồi lên OpenCPS báo lỗi là không đúng

**Comment by trungnt-ksnb** [comment]
@khoahp Xem lại phần này nhé. có vẻ như tại bước đầu tiên backend chưa lưu được assignUserId

**Comment by khoahp** [comment]
@trungnt-ksnb okie ông

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi này anh nhé

**Comment by tragiangdt** [comment]
@huymq @khoahp Lỗi này từ lâu r các anh ưu tiên sửa nhé,

**Comment by tragiangdt** [comment]
@khoahp issue này anh đã fix chưa ạ?

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại lỗi này

**Comment by tragiangdt** [comment]
@khoahp trên qa vẫn còn lỗi này anh nhé

**Comment by khoahp** [comment]
@trungnt-ksnb xử lý phần này nhé

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại lỗi này rồi nhé

**Comment by tragiangdt** [comment]
@khoahp  Lỗi này trên qa vẫn còn anh.
Em cấu hình thủ tục: Xác nhận đăng ký tổ chức hội chợ/triển lãm thương mại tại Việt Nam
1. Cấu hình hành động từ bước bắt đầu: Gán phân công cho Cán bộ xử lý 2 thực hiện xử lý bước sau Kiểm tra hồ sơ
![2016-09-19_120438](https://cloud.githubusercontent.com/assets/17695836/18622974/605d6da8-7e61-11e6-9e18-019f089ee7c9.png)
2. Vào tài khoản Test3, vẫn xử lý được hồ sơ ở bước Kiểm tra hồ sơ
![screenshot from 2016-09-19 12-08-26](https://cloud.githubusercontent.com/assets/17695836/18623024/2ca7d452-7e62-11e6-9ba3-9cfe770ec1db.png)

**Comment by khoahp** [comment]
@trungnt-ksnb cái này có vẻ nghiêm trọng này, ông xem phần này nhé

**Comment by tragiangdt** [comment]
test done trên qa
