### ISSUE TITLE
Cán bộ xử lý sửa đổi được Đơn nhập trực tuyến của Doanh nghiệp

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#495]
B1: Cán bộ vào xem Đơn nhập trực tuyến
B2: Sửa đổi thông tin trên đơn
B3: Nhấn ghi lại, hệ thống báo thành công

**Comment by khoahp** [comment]
@trungnt-ksnb xem lại phần này nhé

**Comment by tragiangdt** [comment]
@trungnt-ksnb  
Cán bộ vẫn sửa ddc form đơn,
Nhấn Ghi lại, -> tắt popup -> Không hiển thị nút Xem biểu mẫu trên thành phần hồ sơ

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by tragiangdt** [comment]
test done
