### ISSUE TITLE
Kế toán xác nhận nộp tiền (TH nộp tiền mặt), phiếu thanh toán không đổi trạng thái 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#496]
- Kế toán xác nhận nộp tiền (TH nộp tiền mặt), phiếu thanh toán không đổi trạng thái thành Hoàn thành, vẫn là trạng thái Chờ nộp.

**Comment by khoahp** [comment]
@tragiangdt test lại phần này nhé

**Comment by tragiangdt** [comment]
test ok
