### ISSUE TITLE
Tích hợp JMS Queue trên JBoss để gửi nhận dữ liệu giữa hai hệ thống backend

### ISSUE THREAD

**Issue by tanhtanhvn** [VietOpenCPS/opencps#497]
Dùng JMS để đồng bộ dữ liệu giữa các backend cài đặt trên 2 hệ thống backend khác nhau. Việc gửi và nhận dữ liệu được thực hiện theo đúng cơ chế producer/consumer - P2P.
Mỗi backend được cài trên một JBoss Server. Cấu hình JBoss để tạo một JMS queue trên server. Khi một backend muốn gửi dữ liệu cho backend khác thì thực hiện tạo một msg gửi vào remote queue như hướng dẫn sau đây. 
http://stackoverflow.com/questions/1900791/jboss-jms-remote-queue

Trường hợp sử dụng JBoss AS 6 hoặc 7 thì sẽ phải dùng Hornetq có sẵn trong JBoss. Cấu hình có thể xem thêm ở đây
https://lukaszantoniak.wordpress.com/2012/12/11/jboss-as-7-remote-jms-queue/

**Comment by khoahp** [comment]
@nguyennv bên mình sẽ dùng JBoss AS 7.1.3 nhé anh, anh download tại đây:
- https://drive.fds.vn/index.php/s/fZPvR0wb5cgJv56
  Phần này anh ngâm cứu cho em chuyền file cho em nhé!

**Comment by khoahp** [comment]
@tanhtanhvn em đóng đóng feature này do đã hoàn thành, quá trình test JMS có vấn đề gì sẽ tạo các issue khác.
