### ISSUE TITLE
Tài khoản công dân/doanh nghiệp mới đăng ký không có menu Quản lý hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#502]
Tài khoản công dân/doanh nghiệp mới đăng ký không có role OCPS_CITIZEN và site opencps

**Comment by khoahp** [comment]
@dunglt91 sửa phần này
- Xem phần cấu hình có hỗ trợ chức năng này?
- Nếu không có thể add vào khi thêm mới tài khoản

**Comment by dunglt91** [comment]
fixed @tragiangdt @khoahp

**Comment by tragiangdt** [comment]
test done
