### ISSUE TITLE
Tài khoản cán bộ vẫn giữ chức vụ cũ sau khi sửa đổi chức vụ cán bộ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#506]
B1: Vào tài khoản quản trị, sửa đổi chức vụ tài khoản cán bộ
B2: Trên màn hình Cập nhật thông tin cán bộ đã lưu được chức vụ mới
B3: Đăng nhập  bằng tài khoản cán bộ vừa được sửa
Lỗi: Vẫn hiển thị menu xử lý của chức vụ cũ (trong liferay, tk này vẫn lưu role cũ, chưa update role mới thay đổi)
@dunglt91

**Comment by khoahp** [comment]
@dunglt91 sửa phần này nhé

**Comment by dunglt91** [comment]
fixed @khoahp @tragiangdt

**Comment by tragiangdt** [comment]
test done
