### ISSUE TITLE
Thành phần hồ sơ không hiển thị theo thứ tự cấu hình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#514]
B1: Vào tài khoản quản trị, cấu hình dịch vụ công mức 3, cấu hình thành phần hồ sơ
B2: Chọn kiểu thành phần Nhóm tùy chọn/nhóm giấy tờ khác/ nhóm giấy tờ riêng cho 1 thành phần hồ sơ (VD: TP2)
B3: Tạo thành phần con của TP2 trên vừa tạo gồm: TP2.1 và TP2.2
Lỗi: Trên màn hình chuẩn bị hồ sơ, thứ tự hiển thị các thành phần là:
TP2
  TP2.2
  TP2.1

**Comment by dunglt91** [comment]
@tragiangdt @khoahp Đã fix, mà thứ tự cấu hình tên thành TP2, TP2.2, TP2.1 phải đánh đúng với sibling Tràng Giang nhé

**Comment by tragiangdt** [comment]
@dunglt91 
Lỗi này vẫn còn nhé, ngoài nhóm tùy chọn bị lỗi vậy ra, nhóm giấy tờ khác + nhóm giấy tờ riêng cũng bị lỗi hiển thị vậy.
Cấu hình:
    TP2 có sibling 2.0
    TP2.1 có sibling 2.1
    TP2.2 có sibling 2.2
Ngoài danh sách thành phần hồ sơ đã hiển thị đúng:
    TP2
    TP2.1
    TP2.2
Những lỗi Trên màn hình chuẩn bị hồ sơ (tk công dân doanh nghiệp đăng nhập), thứ tự hiển thị các thành phần là:
    TP2
    TP2.2
    TP2.1

**Comment by dunglt91** [comment]
Loi man hinh chuan bi ho so la man hinh nao vay Tra Giang, la man hinh tu danh sach mau ho so vao phai khong, cau chup man hinh loi cho minh nhe

**Comment by tragiangdt** [comment]
@dunglt91  Đây Dũng nhé, màn hình doanh nghiệp chuẩn bị hồ sơ ấy
![2016-07-19_102754](https://cloud.githubusercontent.com/assets/17695836/16937706/8a632f8a-4d9b-11e6-8d05-d21ef697b0cd.png)

**Comment by dunglt91** [comment]
Cái này Giang báo lại anh Trung nhé, phần này anh Trung làm

**Comment by trungnt-ksnb** [comment]
@tragiangdt  done
@dunglt91 Hàm getTreeDossierPart(long dossierpartId) em viết chưa chuẩn, anh đã chỉnh lại. Khi em dùng stack trong java thì ghi nhớ tính chất là last-in----first-out

**Comment by tragiangdt** [comment]
@trungnt-ksnb 
Vẫn còn lỗi đối với TH Thành phần hồ sơ riêng anh ạ,

**Comment by tragiangdt** [comment]
![2016-07-19_102754](https://cloud.githubusercontent.com/assets/17695836/16937720/bceec9c8-4d9b-11e6-9d46-23d0d71d4add.png)

**Comment by khoahp** [comment]
@trungnt-ksnb xem lại lỗi này nhé

**Comment by tragiangdt** [comment]
test done

**Comment by tragiangdt** [comment]
@trungnt-ksnb  trên danh sách thành phần hồ sơ, vẫn hiển thị thành phần loại giấy tờ kết quả

**Comment by khoahp** [comment]
@trungnt-ksnb xem phần này nhé

**Comment by tragiangdt** [comment]
@khoahp  Phần liên quan đến hồ sơ riêng anh chuyển lên 2.0, nên em close issue này
