### ISSUE TITLE
Xóa tổ chức, hệ thống báo thành công nhưng trên màn hình danh sách vẫn còn tổ chức đó

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#526]
B1: Vào tài khoản quản trị
B2: Vào quản lý tổ chức
Lỗi: Xóa tổ chức, hệ thống báo thành công nhưng trên màn hình danh sách vẫn còn tổ chức đó. 
Khi vào bảng điều khiển trung tâm, tổ chức này đã bị xóa.

**Comment by khoahp** [comment]
@dunglt91 phần này fix sớm nhé!

**Comment by dunglt91** [comment]
@tragiangdt fixed

**Comment by tragiangdt** [comment]
test done
