### ISSUE TITLE
Số phiên bản giấy tờ tăng không đúng nghiệp vụ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#527]
B1: Tải lên 1 file giấy tờ, số phiên bản tăng lên 1
B2: Xóa giấy tờ này đi
B3: Tải lại 1 file khác, số phiên bản tăng lên 2
-> Số phiên bản giấy tờ chỉ tăng khi sửa đổi gửi bổ sung hồ sơ.

**Comment by trungnt-ksnb** [comment]
@tragiangdt nghiệp vụ này em đọc ở đâu?.
Anh đã hỏi anh @tanhtanhvn truớc khi làm.
