### ISSUE TITLE
Lỗi phân trang

### ISSUE THREAD

**Issue by hoanb** [VietOpenCPS/opencps#534]
- Mẫu hồ sơ lỗi phân trang:
- Không có trang 2
- Kết quả hiển thị chưa có tổng
- Khi kích xem mẫu hô sơ từ mẫu 21 không thêm được thành phần hồ sơ (Báo trắng màn hình)
- Lỗi phân trang thành phần hồ sơ:
- Không có trang 2
- xem thành phần tiếp báo không tìm thấy kết quả
- Lỗi phân trang quy trình : Lỗi tương tự phân trang thành phần hồ sơ

**Comment by khoahp** [comment]
@dunglt91 trao đổi với @hoanb rồi fix nhé

**Comment by tragiangdt** [comment]
test done
