### ISSUE TITLE
Trường serviceProcessID không được lưu vào bảng service_config

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#535]
Khi thêm mới hoặc sửa 1 quy trinh, Trường serviceProcessID không được lưu vào bảng service_config

**Comment by khoahp** [comment]
@dunglt91

**Comment by dunglt91** [comment]
@tragiangdt #535 xem khi nào thì serviceProcessId được thêm vào serviceConfig nhé

**Comment by dunglt91** [comment]
@tragiangdt fix rồi nhé, có thể một số những cấu hình quy trình cũ sẽ không thay danh sách DVC đã cấu hình trước đó, cần cấu hình quy trình lại, cụ thể là chọn các DVC từ process

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by khoahp** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
