### ISSUE TITLE
Không hiển thị tên chủ cơ sở trên danh sách quản lý thu phí

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#541]
Một số lỗi như sau:
![ql thu phi_2016-07-06_164731](https://cloud.githubusercontent.com/assets/17695836/16614202/07476f04-439a-11e6-8918-fcf2c212bc12.png)

**Comment by khoahp** [comment]
@dunglt91 fix lỗi này nhé

**Comment by dunglt91** [comment]
@tragiangdt do doanh nghiệp chưa có tên chứ không phải ko hiển thị lên đâu nhé cậu (check trường name trong bảng opencps_acc_business)

**Comment by tragiangdt** [comment]
@dunglt91 Trường name trong bảng opencps_acc_business có tên Công ty TNHH Phát Trien mà Dũng

**Comment by dunglt91** [comment]
Cái này còn tùy, cậu vao bằng tai khoản citizen thi kiểm tra trường full 
name, nếu vào bằng tài khoản doanh nghiệp thì kiểm tra trường name của 
business

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
tên chủ cơ sở đã hiển thị trên danh sách quản lý thu phí
