### ISSUE TITLE
Chưa check bắt buộc thành phần kq tại thao tác xử lý 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#544]
1. Cấu hình quy trình:
   trong màn hình cập nhật thao tác X, chọn kết quả xử lý là Thành phần hồ sơ A (check bắt buộc)
2. xử lý hồ sơ thuộc quy trình này, đến bước có thao tác trên
   Trên màn hình Xử lý hồ sơ của cán bộ, không thực hiện khai form trực tuyến hoặc tải tệp thành phần hồ sơ A
   Lỗi: Nhấn nút thao tác X, hồ sơ chuyển được bước xử lý, ko check bắt buộc thành phần hồ sơ A

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by tragiangdt** [comment]
test done
