### ISSUE TITLE
Danh sách thành phần kết quả xử lý hồ sơ không hiển thị theo cấu hình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#545]
1. vào màn hình cập nhật Bước xử lý A,
   Tại trường Cập nhật kết quả xử lý hồ sơ, chọn giấy tờ kết quả KQ1, KQ2
2. Thực hiện xử lý tthc gắn quy trình này, tại bước xử lý A
   Trên màn hình xử lý hồ sơ của cán bộ, danh sách giấy tờ kết quả đang hiển thị hết, không theo cấu hình như trên.

**Comment by trungnt-ksnb** [comment]
@tragiangdt mô tả rõ hơn nhé. Trên màn hình xử lý hồ sơ của cán bộ, danh sách giấy tờ kết quả đang hiển thị hết  nghĩa là sao? là hiển thị hết KQ1, KQ2 phải không ?

**Comment by tragiangdt** [comment]
Thực hiện xử lý tthc gắn quy trình này, tại bước xử lý A Trên màn hình xử lý hồ sơ của cán bộ, danh sách giấy tờ kết quả đang hiển thị hết các thành phần là giấy tờ kết quả (gồm KQ1, KQ2, KQ3, KQ4,...)

**Comment by khoahp** [comment]
@trungnt-ksnb xem lại phần này nhé

**Comment by tragiangdt** [comment]
@trungnt-ksnb Lỗi này vẫn còn anh nhé

**Comment by khoahp** [comment]
@trungnt-ksnb xem lại phần giấy tờ trả về nhé, cái này fix sớm, không để hiển thị tất cả ra nữa nhé.

**Comment by tragiangdt** [comment]
@khoahp Lỗi này vẫn còn, anh bỏ label fixed đi ạ

**Comment by tragiangdt** [comment]
test done trên qa

**Comment by tragiangdt** [comment]
@Hongnt31 @hoanb @vuminhcuong 
Lỗi Danh sách thành phần kết quả xử lý hồ sơ không hiển thị theo cấu hình đã được sửa, mọi người khi cấu hình quy trình lưu ý nhé
