### ISSUE TITLE
Sửa tên chức vụ, trong bảng điều khiển trung tâm không lưu vết

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/opencps#546]
B1: Sửa tên chức vụ trong quản lý tổ chức
![screenshot from 2016-07-07 14-48-42](https://cloud.githubusercontent.com/assets/17334000/16646120/9229887e-4452-11e6-81dc-4a80eccfe9fe.png)

B2: Cán bộ xử lý 3 vt đã thay đổi theo chức vụ sửa đổi
![screenshot from 2016-07-07 14-44-44](https://cloud.githubusercontent.com/assets/17334000/16646164/e15aae5a-4452-11e6-98e0-4f278b659491.png)
Lỗi: trong bảng điều khiển trung tâm, tên chức vụ không thay đổi
![screenshot from 2016-07-07 14-44-19](https://cloud.githubusercontent.com/assets/17334000/16646191/fdce8fd4-4452-11e6-8123-ff9ea7f901df.png)

**Comment by khoahp** [comment]
@dunglt91 xử lý nhé

**Comment by dunglt91** [comment]
@vuminhcuong anh thử đổi sang tên ngắn hơn xem, cái 111 khả năng dài hay sao ấy anh, em check database thì role name có thay đổi anh nhé :dancer:

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
@dunglt91 
Trong liferay chưa cập nhật Tiêu đề

**Comment by dunglt91** [comment]
@tragiangdt @khoahp fixed

**Comment by tragiangdt** [comment]
@vuminhcuong  test done
