### ISSUE TITLE
lỗi bảo mật chỗ xử lý hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#550]
phiên bản 1.2 có một lỗi bảo mật chỗ xử lý hồ sơ:
người dùng có thể thay đổi tham số _16_WAR_opencpsportlet_processOrderId=5201 trên địa chỉ để thực hiện việc xử lý hồ sơ bất kỳ

**Comment by dunglt91** [comment]
@khoahp anh @trungnt-ksnb  bảo để anh ấy xem phần này

**Comment by khoahp** [comment]
Close issue này cho vào issue #503
