### ISSUE TITLE
Chỗ chọn người xử lý có thể thay đổi id thành 1 người khác, hồ sơ sẽ chuyển đến người đã được đổi id

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#552]
enable bằng f12 
chỗ chọn người xử lý có thể thay đổi id thành 1 người khác, hồ sơ sẽ chuyển đến người đã được đổi id

**Comment by khoahp** [comment]
Close bug này cho vào issue #503
