### ISSUE TITLE
Tài khoản quản trị không sửa được thông tin doanh nghiệp/công dân

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#553]
1. Vào tài khoản quản trị, vào quản lý côn dân, tổ chức
2. sửa đổi thông tin công dân tổ chức
3. Nhấn ghi lại, hệ thống báo lỗi

**Comment by khoahp** [comment]
@dunglt91

**Comment by khoahp** [comment]
@dunglt91 em xử lý dứt điểm nhé.

**Comment by khoahp** [comment]
@tragiangdt test laij loi nay nhe

**Comment by tragiangdt** [comment]
@khoahp  Trên qa quản trị vẫn chưa sửa được thông tin doanh nghiệp/công dân anh a

**Comment by dunglt91** [comment]
@khoahp @tragiangdt fixed

**Comment by tragiangdt** [comment]
test done
