### ISSUE TITLE
Công dân/tổ chức không sửa được thông tin cá nhân

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#554]
1. Đăng nhập vào tài khoản công dân/doanh nghiệp, 
2. vào thông tin tài khoản công dân tổ chức
3. Sửa đổi thông tin/ đổi pass đều báo lỗi hệ thống

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by khoahp** [comment]
@tragiangdt xem lại lỗi này được chưa em

**Comment by tragiangdt** [comment]
@khoahp 
Lỗi này trước đã đổi pass + đổi tên doanh nghiệp/công dân được rồi a.
Nhưng chưa thay đổi được: Loại hình công ty, Loại hình tổ chức,  Loại hình hoạt động 
Bây giờ opencps dùng theme mới nên mới nên ko test được anh ạ

**Comment by dunglt91** [comment]
@tragiangdt done!

**Comment by tragiangdt** [comment]
test done
