### ISSUE TITLE
Cán bộ không sửa được thông tin tài khoản

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#555]
1. Đăng nhập vào tài khoản cán bộ
2. vào thông tin tài khoản cán bộ
3. Sửa đổi thông tin/ đổi pass đều báo lỗi hệ thống

**Comment by khoahp** [comment]
@dunglt91

**Comment by tragiangdt** [comment]
@khoahp 
3. Đã thay đổi pass thành công
Vẫn còn lỗi: Sửa đổi thông tin cá nhân, nhấn ghi lại hệ thống báo yêu cầu của bạn đã được thực hiện thành công, nhưng các thông tin trên màn hình không thay đổi.
-Trường Tên đầy đủ, số di động, số cố định, Giới tính, Ngày sinh: đã được lưu vào bảng emloyee
-Trường Thư điện tử: sửa đổi thông tin không được lưu vào bảng emloyee

**Comment by khoahp** [comment]
@dunglt91 em xử lý dứt điểm các phần liên quan đến đăng ký tài khoản công dân/doanh nghiệp nhé, anh thấy những lỗi như thế này không nên lặp lại nhiều nữa

**Comment by dunglt91** [comment]
@khoahp @tragiangdt fixed, luc nao ranh test nhe @tragiangdt, to vua day len git, cho cac anh ay deploy nhe

**Comment by tragiangdt** [comment]
@khoahp Anh Khoa deploy lên qa đi anh, em vừa test lại vẫn lỗi như vậy

**Comment by dunglt91** [comment]
@tragiangdt http://qa.opencps.vn/group/guest/thong-tin-tai-khoan-cb (tài khoản cán bộ xử lý 2), tớ vừa sửa tóe loe nhoe được rồi, nó cập nhật dữ liệu vào db (còn trên giao diện phải thoát nick ra vào lại mới thấy thay đổi). Còn vì sao thoát ra vào mới thấy thay đổi cậu hỏi anh @trungnt-ksnb xem, anh ấy làm chỗ này.

**Comment by tragiangdt** [comment]
@dunglt91 @khoahp 
Phát sinh thêm lỗi: cán bộ sửa đổi thông tin tài khoản, phải logout rồi login lại hệ thống mới nhìn thấy được thay đổi.
Các thông tin sửa đổi sau khi login lại đã được cập nhật.

**Comment by dunglt91** [comment]
@trungnt-ksnb anh xem lại chỗ này xem ạ.
@tragiangdt Lỗi này có từ đầu chứ có phải phát sinh đâu :)

**Comment by khoahp** [comment]
@tragiangdt cái này còn lỗi không để close vào nhé

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi: cán bộ sửa đổi thông tin tài khoản, phải logout rồi login lại hệ thống mới nhìn thấy được thay đổi.
Các thông tin sửa đổi sau khi login lại đã được cập nhật.

**Comment by dunglt91** [comment]
@huymq  phần này anh @trungnt-ksnb làm anh nhé.

**Comment by tragiangdt** [comment]
test done trên qa
