### ISSUE TITLE
Người làm thủ tục nhấn gửi nộp hồ sơ, hồ sơ chuyển thành trạng thái lỗi

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#566]
Sau khi cấu hình lại quy trình map với DVC, 
Người làm thủ tục nhấn gửi nộp hồ sơ, hồ sơ chuyển thành trạng thái lỗi

**Comment by khoahp** [comment]
@tragiangdt đã fix trên con QA

**Comment by khoahp** [comment]
@tragiangdt xem lại lỗi này nhé

**Comment by tragiangdt** [comment]
@khoahp  @trungnt-ksnb 
Trên con qa, khi nộp hồ sơ vẫn báo lỗi như vậy

**Comment by tragiangdt** [comment]
test done
