### ISSUE TITLE
Lỗi phân trang chức vụ

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#580]
@dunglt91 fix gấp phần này,
@hoanb or @tragiangdt test lại

**Comment by tragiangdt** [comment]
@dunglt91  Dũng sửa nhé

**Comment by dunglt91** [comment]
@khoahp @tragiangdt fixed (tắt chế độ phân trng chức vụ trong navigator)

**Comment by Hongnt31** [comment]
vẫn còn lỗi phân trang form danh sách chức vụ:
lỗi khi tạo được 20 chức vụ khi tạo thêm chức vụ thứ 21 không thấy

**Comment by khoahp** [comment]
@dunglt91 em xem lại phần này nhé, chưa xử lý được thì tạm bỏ phân trang đi.

**Comment by dunglt91** [comment]
@Hongnt31 phát hiện hay đấy Hồng, cái này phải update cả bên thành phần hồ sơ :+1: 
done!

**Comment by Hongnt31** [comment]
Test done @khoahp  a đóng issue giúp e với nhé

**Comment by khoahp** [comment]
Okie em.
