### ISSUE TITLE
Chuyên viên soạn văn bản (Bắt buộc đính kèm) rồi gửi duyệt nhưng chưa đính kèm vẫn được gửi duyệt thành công

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#582]
@trungnt-ksnb đã fix phần này,

@tragiangdt or @hoanb confirm lại

**Comment by tragiangdt** [comment]
@khoahp  @trungnt-ksnb 
Vẫn còn lỗi trên qa anh nhé.
Các bước để tái hiện lỗi:
B1: Vào tài khoản quản trị, vào cấu hình quy trình
B2: Tại bước xử lý hồ sơ, trong màn hình cập nhật thao tác, tại thao tác Gửi duyệt hồ sơ, trường kết quả xử lý Văn bản xác nhận check bắt buộc
B3: thực hiện xử lý hồ sơ gắn với quy trình đã tạo đến bước Xử lý hồ sơ
Trên màn hình xử lý hồ sơ, cán bộ không tải lên file Văn bản xác nhận, nhấn nút Gửi duyệt hồ sơ
Lỗi: Hệ thống chưa check thông tin giấy tờ kết quả Văn bản xác nhận đã có file hay chưa

**Comment by tragiangdt** [comment]
@khoahp  test done
