### ISSUE TITLE
Lỗi phân trang thành phần hồ sơ

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#583]
@dunglt91 fix gấp cái này, nếu chưa xử lý phân trang khi có navigator, thì cho hiển thị hết thành phần hồ sơ?

@trungnt-ksnb, @huymq  có sáng kiến nào khi phân trang tại một trang có navigator không?

**Comment by huymq** [comment]
Thành phần hồ sơ nhiều thế cơ à :D. 
Phân trang trong navigator thì dùng ajax cho đơn giản. Dùng search container thì phải giữ được cái navigator của nó, sợ hơi loằng ngoằng

**Comment by dunglt91** [comment]
@Anh Huy, thành phần hồ sơ thì không nhiều a ạ, em đang tạm không cho nó 
phân trang, vấn đề là những cái khác cũng dùng nhiều search container 
trong navigator
Thành phần hồ sơ nhiều thế cơ à :D.

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
test done

**Comment by tragiangdt** [comment]
@dunglt91 @khoahp 
Hiện tại chỉ hiển thị được 20 tp hồ sơ thôi, nhập thêm tphs vào đều báo thành công nhưng không hiển thị trên danh sách

**Comment by huymq** [comment]
@dunglt91 @khoahp Giải pháp tạm thời cứ để fix số lượng phân trang là 100 hoặc 200. Tuy nhiên vẫn để bug theo dõi vì chưa fix được triệt để

**Comment by khoahp** [comment]
@dunglt91 tạm thời là vậy, anh open lại bug này.

**Comment by dunglt91** [comment]
@tragiangdt cậu test trên QA với số thành phần trên 20 chưa, @khoahp @huymq cái này hôm t7 em đã sửa lại thành có bao nhiêu hiển thị bấy nhiêu rồi, em test trên local trên 20 dữ liệu nó sổ ra hết, bản fix mới nhất em đẩy lên hôm thứ 7 vừa qua, anh Huy merge về thử xem thế nào.

**Comment by dunglt91** [comment]
@khoahp @huymq @tragiangdt đây nếu mà đúng thì nó hiển thị tương tự như links này.
http://qa.opencps.vn/web/guest/quan-ly-can-bo?p_p_id=2_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_2_WAR_opencpsportlet_workingunitId=1101&_2_WAR_opencpsportlet_redirectURL=%2Fweb%2Fguest%2Fquan-ly-can-bo&_2_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fusermgt%2Fadmin%2Fedit_workingunit.jsp#_2_WAR_opencpsportlet_tab=_2_WAR_opencpsportlet_jobpos

**Comment by tragiangdt** [comment]
@dunglt91 
Trên qa vẫn chưa hiển thị hết các tp hs nhé
Link: http://qa.opencps.vn/group/guest/quan-ly-dich-vu-cong-muc-3?p_p_id=12_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_12_WAR_opencpsportlet_dossierTemplateId=301&_12_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fdossiermgt%2Fadmin%2Fedit_dossier.jsp&_12_WAR_opencpsportlet_backURL=%2Fgroup%2Fguest%2Fquan-ly-dich-vu-cong-muc-3#_12_WAR_opencpsportlet_tab=_12_WAR_opencpsportlet_dossierpartlist

**Comment by dunglt91** [comment]
oko thanks @tragiangdt  đã fix!

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại giúp anh nhé

**Comment by tragiangdt** [comment]
@dunglt91 @khoahp 
Trên qa vẫn chưa hiển thị hết các tp hs, Thêm mới tp hs hệ thống báo yêu cầu thực hiện thành công nhưng trên danh sách ko hiển thị tp này

**Comment by khoahp** [comment]
@tragiangdt kiểm tra lại giúp nhé a vừa cập deploy bản mới lên đấy

**Comment by tragiangdt** [comment]
test done

**Comment by khoahp** [comment]
@tragiangdt anh đóng issue nhé
