### ISSUE TITLE
Lỗi phân trang mẫu hồ sơ

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#584]
Chưa thể hiện rõ kết quả phân trang, Nếu chọn kết quả là 5 thì không hiển thị phân trang
Từ trang thứ 2 không thêm được thành phần hồ sơ.

@dunglt91 xem lại bug này nhé, bên test báo vẫn còn.

@hoanb or @tragiangdt confirm nhé

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
test done
