### ISSUE TITLE
Thủ tục hành chính: Cột cơ quan quản lý và lĩnh vực quản lý title đang lẫn nhau

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#586]
@hoanb or @tragiangdt kiểm tra lại

@dunglt91 hỗ trợ nhé, phần này đã fix rồi.

**Comment by tragiangdt** [comment]
@Dũng: trước mới fix lỗi này trên portlet tra cứu thủ tục hành chính thôi. Ở portlet Quản lý thủ tục hành chính vẫn còn lỗi này.

**Comment by khoahp** [comment]
@dunglt91 em fix trên phần quản lý luôn nhé.

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by khoahp** [comment]
@tragiangdt xử lý

**Comment by tragiangdt** [comment]
test done
