### ISSUE TITLE
DN: Doanh nghiệp xem lịch sử trắng, xem kết quả không có kết quả mà hiển thị lịch sử bên tab kết quả

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#587]
@tragiangdt mô tả rõ cho anh cái này nhé, viết tối nghĩa quá.

**Comment by tragiangdt** [comment]
B1: đăng nhập tài khoản doanh nghiệp
B2: vào xem chi tiết hồ sơ
B3: kích vào tab kết quả, dánh sách lịch sử xử lý hồ sơ hiển thị trên tab kết quả
Kích vào tab Lịch sử xử lý thì hiển thị trắng

**Comment by tragiangdt** [comment]
test done
