### ISSUE TITLE
Doanh nghiệp bổ sung hồ sơ nhưng không có nút ghi lại

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#589]
@trungnt-ksnb vs tôi fix phần này nhé, xem lại vấn đề về quy trình.

**Comment by trungnt-ksnb** [comment]
@khoahp  done

**Comment by tragiangdt** [comment]
@trungnt-ksnb @khoahp 
Vẫn không có nút ghi lại trong màn hình chuẩn bị nộp bổ sung hồ sơ anh nhé

**Comment by tragiangdt** [comment]
@trungnt-ksnb  Vẫn không có nút ghi lại trong màn hình chuẩn bị nộp bổ sung hồ sơ anh nhé

**Comment by khoahp** [comment]
@trungnt-ksnb xem lại nhé

**Comment by tragiangdt** [comment]
@khoahp qa vẫn còn lỗi này anh

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại và close vào nhé

**Comment by tragiangdt** [comment]
@khoahp  test done trên qa

**Comment by tragiangdt** [comment]
@khoahp Anh close issue này giúp em a
