### ISSUE TITLE
Lỗi tìm kiếm theo cơ quan phía doanh nghiệp

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#591]
Lỗi tìm kiếm theo cơ quan phía doanh nghiệp
1. Doanh nghiệp đăng nhập
2. Vào thêm hố sơ
3. Tìm kiếm hồ sơ theo cơ quan => báo không tìm dịch vụ công nào

@trungnt-ksnb xem giúp lỗi này nhé, xem có thể hỗ trợ cho @binhth fix lỗi này

**Comment by trungnt-ksnb** [comment]
@khoahp 
Lỗi này như sau
- Field govAgecyIndex trong bảng opencps_service_config hiện tại đang rỗng do đó không tìm đuợc theo cơ quan

Xử lý như sau:
- Nhờ DBA hỗ trợ update filed govAgencyIndex
- Thêm phần cập nhật govAgencyIndex vào hàm add hoặc update ServiceConfig, phần này để dunglt làm cho nhanh

**Comment by khoahp** [comment]
@tuhoanganh & @dunglt91 xử lý nhé

**Comment by dunglt91** [comment]
@khoahp @tragiangdt  fixed

**Comment by tragiangdt** [comment]
@dunglt91 @khoahp 
Vẫn chưa lọc được theo Cơ quan thực hiện anh nhé

**Comment by dunglt91** [comment]
anh @trungnt-ksnb  em đã thêm hàm tìm kiếm vào serviceConfig cho anh rồi, @tragiangdt vẫn chưa tìm được theo cq thực hiện anh ạ

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi này anh

**Comment by binhth** [comment]
@tragiangdt 
giải pháp: sửa truyền sai tham số của truờng cơ quan thực hiện

**Comment by tragiangdt** [comment]
Đã test ok trên opencps-dev.
@hoanb  Để lọc đúng cần vào cấu hình lại dịch vụ công (vào màn hình cập nhật cấu hình dịch vụ công, sau đó nhấn Đồng ý)
![cap nhat cau hinh dvc](https://cloud.githubusercontent.com/assets/17695836/17843529/3eed17fe-6859-11e6-92f5-0002ae4209af.png)

**Comment by huymq** [comment]
@dunglt91 check lại lỗi này nhé. Cần chạy script cập nhật hoặc cấu hình gì thì báo lại để close sớm issues này

**Comment by dunglt91** [comment]
@huymq phần này như @tragiangdt nói ở trên anh ạ.
Đầu tiên do tách cơ quan thực hiện và cơ quan quản lý nên dữ liệu govagencyIndex bi lệch, phần này có thể cập nhật cấu hình dịch vụ công theo danh sách cơ quan thực hiện đang có trong phần cấu hinh dịch vụ công cấp 3, hoặc update bằng script trong db, 2 cách này đều được anh nhé,
hiện tại em test trên opencps-dev ok rồi.

**Comment by huymq** [comment]
@tragiangdt lỗi này được chưa để close em

**Comment by khoahp** [comment]
@tragiangdt test lại lỗi này, okie em close vào nhé

**Comment by tragiangdt** [comment]
test done trên qa
