### ISSUE TITLE
Xóa tổ chức báo thành công nhưng kết quả vẫn không xóa được (Đã xóa hết cán bộ, chức vụ trong tổ chức)

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#592]
@dunglt91 fix lỗi này, việc fix phải làm triệt để không để báo đi báo lại một bug ntn nữa

**Comment by dunglt91** [comment]
Lỗi này em đã bảo Trà Giang test lại không vấn đề gì rồi mà, chưa đóng 
bug thôi anh. Chỗ này đề nghị các test đã test rồi thì nên đóng bug hoặc 
confirm, kẻo khi rà soát lại báo lên một đống thế này khó kiểm soát lại 
mất thời gian xem lại

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
test done
