### ISSUE TITLE
Phân trang dịch vụ công lỗi 

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#593]
Phân trang dịch vụ công lỗi
1. Vào ứng dụng dịch vụ công cấp 3
2. Chọn tab Cấu hình dịch vụ công
3. Next trang hoặc chọn số lượng hiển thị => Báo không có dịch vụ công nào

@dunglt91 có vẻ phần xử lý phân trang nào của em cũng có vấn đề, xem lại nhé, vì đây là những thứ cơ bản nhất.

**Comment by dunglt91** [comment]
@khoahp  @tragiangdt  success

**Comment by tragiangdt** [comment]
test done
