### ISSUE TITLE
DN: Phân trang giấy tờ lỗi: Kích phân trang về màn hình hồ sơ

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#594]
@tragiangdt or @hoanb trả lời xem phần trang giấy tờ khi cấu hình hay khi chuẩn bị nộp hồ sơ?

**Comment by tragiangdt** [comment]
@hoanb "trả lời xem phần trang giấy tờ khi cấu hình hay khi chuẩn bị nộp hồ sơ?"

**Comment by khoahp** [comment]
@tragiangdt em xem lại phần này nhé

**Comment by tragiangdt** [comment]
Đã bỏ phân trang giấy tờ
test done

**Comment by khoahp** [comment]
@tragiangdt anh đóng issue này nhé
