### ISSUE TITLE
DN: Xem mẫu đơn khai trực tuyến báo lõi no-attachment-file

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#596]
@trungnt-ksnb xem phần này phát nhé

**Comment by trungnt-ksnb** [comment]
@khoahp 
Khoa mô tả rõ giúp mình. Mình test vẫn thấy ok

**Comment by khoahp** [comment]
@tragiangdt xem lại luôn nhé

**Comment by tragiangdt** [comment]
@khoahp 
Trên qa phần này ko lỗi
