### ISSUE TITLE
Danh mục trạng thái tại các bước xử lý mà doanh nghiệp đang nhìn thấy hiện đang fix cứng chưa có danh mục.

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#597]

**Comment by khoahp** [comment]
@dunglt91 xử lý cho anh phần này nhé, file này /opencps-portlet/docroot/html/portlets/processmgt/admin/edit_step.jsp cập nhật lại trạng thái theo taglib

**Comment by dunglt91** [comment]
@khoahp anh @trungnt-ksnb đã fix

**Comment by tragiangdt** [comment]
@khoahp  Lỗi này vẫn còn a

**Comment by dunglt91** [comment]
@tragiangdt hqua tớ chuyển r nhé, đợi anh @khoahp đẩy lên :dancer:

**Comment by dunglt91** [comment]
@tragiangdt cậu test đi nhé, xong tag anh Huy vào nhé

**Comment by tragiangdt** [comment]
@huymq @khoahp 
test done
