### ISSUE TITLE
Thủ tục hành chính DVC2: Thông tin chi tiết chưa tự động xuống dòng đang sử dụng </br> để thay thế

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#599]
Thủ tục hành chính DVC2: Thông tin chi tiết chưa tự động xuống dòng đang sử dụng </br> để thay thế
- Thành phần hồ sơ
- đối tượng thực hiện
- Lệ phí thủ tục
- Kết quả thực hiện
- Văn bản pháp lý

@dunglt91 bổ xung thêm phần editor cho các trường như trên, thay vì text filed như cũ.

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
test done
