### ISSUE TITLE
Chưa tìm kiếm được dịch vụ công

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#601]
Chưa tìm kiếm được dịch vụ công
1. Vào ứng “Dịch vụ công mức 3”
2. Vào tab Cấu hình dịch vụ công
3. Tìm kiếm theo tên báo không có dịch vụ công nào

@dunglt91 thực hiện nhé,

**Comment by dunglt91** [comment]
@khoahp @tragiangdt success

**Comment by tragiangdt** [comment]
test done
