### ISSUE TITLE
Thông tin ngày gửi, ngày cập nhật, ngày hẹn trả chưa đúng

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#602]
Đăng nhập tk NLTT
Thông tin Ngày gửi, Ngày cập nhật, ngày hẹn trả, Tình trạng chưa hiển thị trên tab Kết quả (khi xem chi tiết 1 hồ sơ)

**Comment by khoahp** [comment]
@tragiangdt  Em test lại nhé

**Comment by tragiangdt** [comment]
@khoahp 
Vẫn còn lỗi anh:
1. Ngày tiếp nhận (chỉ cập nhật ngày tiếp nhận khi sinh số tiếp nhận)
2. Ngày hẹn trả (không cấu hình ngày hẹn trả nhưng lúc nào trường này cũng có giá trị)
![2016-09-23_173614](https://cloud.githubusercontent.com/assets/17695836/18783168/915e8bca-81b4-11e6-93c1-2f941c296e78.png)

**Comment by khoahp** [comment]
@Hongnt31 phần này không test à em

**Comment by Hongnt31** [comment]
@khoahp Test done
