### ISSUE TITLE
Thông tin ghi chú NLTT nhập khi nộp hồ sơ hoặc sửa đổi bổ sung chưa hiển trên danh sách Lịch sử xử lý (Lịch sử xử lý bên NLTT và bên Cán bộ)

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#604]
@tragiangdt or @hoanb theo thiết kế phần này có hiển thị trong danh sách không?

**Comment by tragiangdt** [comment]
Có anh. TH khi nộp hồ hơ, NLTt nhập ý kiến 1, TH khi bổ sung hồ sơ, nltt lại nhập ý kiến tiếp. Vậy phải hiển thị đc 2 lần NLTT đã nhập ạ.

**Comment by khoahp** [comment]
@dunglt91

**Comment by khoahp** [comment]
@dunglt91 bổ xung thông tin theo thiết kế nhé

**Comment by tragiangdt** [comment]
@khoahp @huymq Lỗi này từ lâu rồi, các anh ưu tiên sửa trước nhé

**Comment by huymq** [comment]
@dunglt91 xem xử lý nhé

**Comment by thanhld2901** [comment]
Chuyển lại cho đội core. @tragiangdt  comfirm giúp anh nhé

**Comment by huymq** [comment]
@thanhld2901 Okie anh. Cái này em sẽ xử lý

**Comment by tragiangdt** [comment]
@huymq 
Lỗi này vẫn còn anh nhé

**Comment by huymq** [comment]
@tragiangdt test lại nhé

**Comment by tragiangdt** [comment]
@khoahp  Lỗi này trên qa vẫn còn anh

**Comment by khoahp** [comment]
@tragiangdt phần lịch sử này tạm thời để như vậy, anh đã cho lên bug của 2.0 làm lại phần ghi log trên #1062

**Comment by tragiangdt** [comment]
@khoahp  vậy anh close issue này nhé
