### ISSUE TITLE
Màn hình lịch sử xử lý hồ sơ của NLTT chưa đúng theo thiết kế

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#607]

**Comment by khoahp** [comment]
@tragiangdt em confirm lại nhé

**Comment by tragiangdt** [comment]
Đã thay đổi màn hình lịch sử xử lý hồ sơ theo thiết kế, nhưng còn 1 vấn đề nữa:
chỉ hiển thị bản ghi nào có syncStatus = 1-yêu cầu đồng bộ, 2-đồng bộ thành công, 3-đồng bộ bị lỗi

**Comment by tragiangdt** [comment]
@khoahp Hiện tại vẫn hiển thị tất cả các bản ghi log trên màn hình quá trình xử lý hồ sơ

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại lỗi này nhé, anh vừa deploy lên server

**Comment by tragiangdt** [comment]
@khoahp Còn 2 lỗi:
1. Hiện tại vẫn hiển thị tất cả các bản ghi log trên màn hình quá trình xử lý hồ sơ
2. Có dòng lịch sử mà hiển thị đối tượng xử lý trống
![2016-09-22_165243](https://cloud.githubusercontent.com/assets/17695836/18743855/3cecb37a-80e5-11e6-9ec8-3a7ed31ecfbb.png)

**Comment by khoahp** [comment]
@tragiangdt close lỗi này nhé, phần log được cập nhật qua issue #1062
