### ISSUE TITLE
Hiển thị ngày hẹn trả popup xác nhận chuyển bước khi không được cấu hình

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#612]

**Comment by khoahp** [comment]
@tragiangdt bug này anh thêm vào nhưng đọc lại chưa rõ ý, em mô tả giúp anh nhé

**Comment by tragiangdt** [comment]
1. Quản trị vào cập nhật thao tác xử lý, không check trường Ngày hẹn trả
2. Vào tài khoản cán bộ xử lý, click 1 hành động (thao tác vừa cập nhật), trên màn hình xác nhận chuyển bước, vẫn hiển thị trường Ngày hẹn trả

**Comment by khoahp** [comment]
@trungnt-ksnb xem lại phần này trên pop-up chuyển hồ sơ nhé

**Comment by trungnt-ksnb** [comment]
@khoahp done

**Comment by tragiangdt** [comment]
@trungnt-ksnb Trên qa vẫn còn lỗi này ạ
1. Quản trị vào cập nhật thao tác xử lý, không check trường Ngày hẹn trả
![2016-09-22_161346](https://cloud.githubusercontent.com/assets/17695836/18742653/b84760ca-80df-11e6-86ed-123d0e2edaeb.png)
1. Vào tài khoản cán bộ xử lý, click 1 hành động (thao tác vừa cập nhật), trên màn hình xác nhận chuyển bước, vẫn hiển thị trường Ngày hẹn trả
   ![2016-09-22_161515](https://cloud.githubusercontent.com/assets/17695836/18742676/ca4bd6e8-80df-11e6-8aeb-d7c8a21310a0.png)

**Comment by khoahp** [comment]
@huymq chuyển lại issue này cho huy nhé
