### ISSUE TITLE
Danh sách lịch sử xử lý hiển thị trên tab Kết quả khi xem chi tiết một hồ sơ (đăng nhập tk NLTT)

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#613]

**Comment by trungnt-ksnb** [comment]
@khoahp mô tả rõ hơn n hé

**Comment by khoahp** [comment]
@tragiangdt em mô tả rõ nhé

**Comment by tragiangdt** [comment]
@trungnt-ksnb  
Hình đây anh:
![screenshot from 2016-07-15 17-56-34](https://cloud.githubusercontent.com/assets/17695836/16938869/54b389d8-4da6-11e6-93fd-f1790fec21b6.png)

**Comment by khoahp** [comment]
Trên qa không lỗi
