### ISSUE TITLE
Trên màn hình xác nhận chuyển bước, không hiển thị người được phân công xử lý ở bước sau (người đã được cấu hình trong quy trình)

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#614]
@tragiangdt phần này em test lại trên con QA nhé

**Comment by tragiangdt** [comment]
@anh Khoa: anh đã sửa lỗi này trên qa r ạ.

**Comment by tragiangdt** [comment]
@khoahp Trên qa vẫn còn lỗi này anh nhé

**Comment by Hongnt31** [comment]
@khoahp Trên qa hết lỗi này rùi anh nhé

**Comment by tragiangdt** [comment]
@khoahp 
Lỗi này chưa được anh ới

**Comment by tragiangdt** [comment]
@khoahp @huymq Lỗi này từ lâu rồi, các anh ưu tiên sửa trước nhé

**Comment by tragiangdt** [comment]
@khoahp  Lỗi này vẫn còn anh nhé

**Comment by khoahp** [comment]
@tragiangdt em test lại, anh đã cập nhật nhé

**Comment by tragiangdt** [comment]
@khoahp  test done trên qa
