### ISSUE TITLE
Lỗi giao diện , lỗi không đăng xuất đươc trên trình duyệt safari

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#615]

**Comment by khoahp** [comment]
@tragiangdt nếu test trên safari 5 (safari trên windows) thì ngừng hỗ trợ bản này nhé, hiện tại safari đã đến phiên bản 9 và phiên bản trên windown từ 2012 đã ngừng hỗ trợ rồi.

**Comment by tragiangdt** [comment]
Vậy anh close bug này nhé
