### ISSUE TITLE
Không tạo được 2 cơ quan quản lý cho  1 thủ tục hành chính

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#618]
B1: Đăng nhập tk quản trị
B2: Vào cấu hình dịch vụ công
B3: thêm dịch vụ công,
chọn dvc đã được cấu hình để thêm cơ quan quản lý nữa,
Nhấn Ghi lại, hệ thống báo "Lỗi hệ thống"

**Comment by dunglt91** [comment]
@tragiangdt lỗi này fix rồi mà
@khoahp cái này do cái index DB bị trùng đó anh.

**Comment by tragiangdt** [comment]
Test done
