### ISSUE TITLE
Thành phần hồ sơ là kiểu loại "Nhiều giấy tờ kết quả " không hiển thị trên danh sách kết quả xử lý hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#622]
![2016-07-19_094548](https://cloud.githubusercontent.com/assets/17695836/16937016/a743676a-4d95-11e6-9d51-d5cfad0ac3f1.png)

**Comment by tragiangdt** [comment]
Đã lên trên opencps-dev

**Comment by tragiangdt** [comment]
@trungnt-ksnb 
Trên qa chưa được ạ

**Comment by khoahp** [comment]
@tragiangdt anh đóng issue này nhé

**Comment by tragiangdt** [comment]
test done trên qa
