### ISSUE TITLE
Thành phần "Giây tờ kết quả" hiển thị trên danh sách chuẩn bị hồ sơ của NLTT, không hiển thị trên ds Xử lý hồ sơ của cán bộ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#625]
Thành phần "Giây tờ kết quả" của Hồ sơ riêng hiển thị trên danh sách chuẩn bị hồ sơ của NLTT, không hiển thị trên ds Xử lý hồ sơ của cán bộ
![2016-07-19_102754](https://cloud.githubusercontent.com/assets/17695836/16937761/0d1da18a-4d9c-11e6-95cb-94c08471885c.png)

**Comment by khoahp** [comment]
@tragiangdt anh chuyển lên 2.0 các phần liên quan đến hồ sơ riêng nhé

**Comment by khoahp** [comment]
@tragiangdt anh close phần này vào nhé
