### ISSUE TITLE
Không có nút Ghi lại, Xem trước tạo form trên màn hình khai trực tuyến giấy tờ kết quả

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#626]
Không có nút Ghi lại, Xem trước tạo form trên màn hình khai trực tuyến giấy tờ kết quả
(Lỗi này xuất hiện sau khi sửa lỗi #495 )

**Comment by khoahp** [comment]
@binhth

**Comment by tragiangdt** [comment]
Đã có nút Ghi lại trên form động
