### ISSUE TITLE
Phương thức thanh toán không hiển thị trên danh sách Quản lý thu phí

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#632]
- Phương thức thanh toán không hiển thị trên danh sách Quản lý thu phí (TH trạng thái của phiếu thanh toán là Hoàn thành)

![07476f04-439a-11e6-8918-fcf2c212bc12](https://cloud.githubusercontent.com/assets/17695836/16942203/0a64fab0-4dbf-11e6-9164-9b5ae2fd2f12.png)

**Comment by khoahp** [comment]
@tragiangdt fix các lỗi liên quan đến thanh toán done nhé

**Comment by tragiangdt** [comment]
@khoahp  @binhth 
Phương thức thanh toán vẫn chưa hiển thị trên danh sách quản lý thu phí
![2016-08-01_170458](https://cloud.githubusercontent.com/assets/17695836/17290726/28334aec-580a-11e6-8142-789367aa786e.png)

**Comment by binhth** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
