### ISSUE TITLE
Hiển thị sai cơ quan thực hiện trên danh sách chọn DVC 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#637]
B1: Đăng nhập tk quản trị, vào quản lý quy trình
B2: Vào tab Dịch vụ
B3: Trên popup hiển thị danh sách dịch vụ công:
Lỗi: - Cấp quản lý đổi thành cơ quan thực hiện
- Hiển thị sai cơ quan quản thực hiện (Đang hiển thị cấp quản lý tthc)

![2016-07-19_150936_co quan thuc hien](https://cloud.githubusercontent.com/assets/17695836/16944056/0d6eba84-4dc9-11e6-99ff-cefcd4889abb.png)

**Comment by khoahp** [comment]
@dunglt91 cả phần việt hoá nữa :(

**Comment by dunglt91** [comment]
@tragiangdt cái này lấy đúng tên cơ quan trong serviceconfig rồi mà cậu
@khoahp done!

**Comment by tragiangdt** [comment]
@dunglt91 
Cậu xem lại đi, mình kiểm tra lại thì chưa lấy đúng.
Cậu sửa luôn text: Cấp quản lý đổi thành Cơ quan thực hiện + Việt hóa nữa

**Comment by khoahp** [comment]
@tragiangdt phần này có phải tên lấy bị ngược không em?

@dunglt91 em sửa mấy chỗ việt hoá đi nhé, sửa nhanh không nhìn trông không đẹp

**Comment by tragiangdt** [comment]
@khoahp Phần này không lấy tên ngược mà lấy sai ạ.
Thủ tục "Xác nhận đăng ký thực hiện khuyến mại theo hình thức mang tính may rủi thực hiện trên địa bàn từ 2 tỉnh, thành phố trực thuộc Trung ương trở lên hoặc theo quy định tại Điều 17 NĐ số 37/2006/NĐ-CP" 
cấu hình có 2 cơ quan quản lý là Cục Xúc tiến thưong mại và Cục ĐƯờng sắt, hiện tại đang hiển thị là Cục Xúc tiến thương mại hết

**Comment by khoahp** [comment]
@dunglt91 em xem lại nhé!

**Comment by dunglt91** [comment]
@tragiangdt tớ cấu hình như này vẫn hiện tên cơ quan đúng mà, phần việt hóa tớ đã chuyển sang cơ quan thực hiện, Giang kiểm tra lại xem
![bug2](https://cloud.githubusercontent.com/assets/17336343/17269786/5eaf0b54-567c-11e6-9cb1-c2b96b68241d.png)

**Comment by khoahp** [comment]
@tragiangdt em xem lại lỗi này nhé

**Comment by tragiangdt** [comment]
Test done. Trên qa đã hiển thị đúng
