### ISSUE TITLE
Hiển thị sai cơ quan thực hiện trên danh sách dvc trong quy trình

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#638]
B1: Đăng nhập tk quản trị, vào quản lý quy trình
B2: Vào tab Dịch vụ
B3: Trên danh sách dịch vụ công:
Lỗi: - Cấp quản lý đổi thành cơ quan thực hiện
- Hiển thị sai cơ quan quản thực hiện 
  ![2016-07-19_151101_co quan thuc hien](https://cloud.githubusercontent.com/assets/17695836/16944272/f5713ad2-4dc9-11e6-8529-e402e498e401.png)

**Comment by dunglt91** [comment]
@tragiangdt  sau giang báo bug paste giúp tớ cái links nhé!

**Comment by tragiangdt** [comment]
@dunglt91 
Link: http://qa.opencps.vn/web/guest/quan-ly-quy-trinh?p_p_id=15_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_15_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fprocessmgt%2Fadmin%2Fedit_process.jsp&_15_WAR_opencpsportlet_serviceProcessId=801&_15_WAR_opencpsportlet_backURL=%2Fweb%2Fguest%2Fquan-ly-quy-trinh#_15_WAR_opencpsportlet_tab=_15_WAR_opencpsportlet_service

**Comment by khoahp** [comment]
@dunglt91 phần này anh thấy sửa nhanh được mà, như trong thủ tục hành chính cấp 2 đấy, có cập và cơ quan thực hiện thôi?

Fix sớm nhé!

**Comment by dunglt91** [comment]
@khoahp trong thủ tục hành chính cấp 2 là cấp và cơ quan Ban Hành thủ tục, cơ quan thực hiện thủ tục là cơ quan được cấu hình trong DVC cấp 3 chứ ạ?
Cái này em sửa hôm t7 và đưa lên git rồi mà anh nhỉ?

**Comment by khoahp** [comment]
@tragiangdt xem lại nhé

**Comment by dunglt91** [comment]
anh @khoahp anh thử merge lại xem nó có ăn không anh nhé

**Comment by dunglt91** [comment]
@tragiangdt test lại tớ phát nhé

**Comment by tragiangdt** [comment]
test done
