### ISSUE TITLE
Tên Doanh nghiệp hiển thị không đồng nhất

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#641]
Doanh nghiệp vào xem thông tin tài khoản, Tên Doanh nghiệp hiển thị không đồng nhất
![2016-07-19_181734](https://cloud.githubusercontent.com/assets/17695836/16948167/48c0ec24-4ddd-11e6-90e6-876b39743914.png)

**Comment by khoahp** [comment]
Sửa theo giao diện thiết kế mới

**Comment by dunglt91** [comment]
@tragiangdt @khoahp đã chỉnh sửa

**Comment by tragiangdt** [comment]
@khoahp @dunglt91 
Trên giao diện thiết kế mới chưa hiển thị Tên doanh nghiệp, click vào Thay đổi thì không hiển thị gì cả.
![2016-08-01_135700](https://cloud.githubusercontent.com/assets/17695836/17285889/ebd6b3f0-57ef-11e6-82b5-b99c31adea64.png)

**Comment by dunglt91** [comment]
@tragiangdt cái nút đó anh @trungnt-ksnb xử lý,  trước anh @khoahp bảo cứ hiện lên nhưng chưa làm gi

**Comment by khoahp** [comment]
@tragiangdt phần này chỉ có phần hình thôi nhé, phần cho việc sửa trực tiếp lên đấy chưa có. anh sẽ chuyển qua bản 1.5.

**Comment by tragiangdt** [comment]
test done (sửa theo thiết kế mới)
