### ISSUE TITLE
Danh sách hồ sơ mới chờ xử lý không đúng thiết kế

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#644]
Danh sách hồ sơ mới chờ xử lý không đúng thiết kế

**Comment by khoahp** [comment]
@huymq anh chuyển lại phần này nhé

**Comment by khoahp** [comment]
@tragiangdt phần này được chưa em?

**Comment by tragiangdt** [comment]
@khoahp 
Phần này chưa được anh ạ
mokup thiết kế:
https://raw.githubusercontent.com/VietOpenCPS/doc/master/SRS/processmgt/16processmgtprocessorderdonelist.png
