### ISSUE TITLE
Chưa hiển thị số giấy tờ, loại giấy tờ (nếu có) của thành phần hồ sơ trong Nội dung hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#645]
1. Đăng nhập tài khoản cán bộ
2. Vào xem nội dung hồ sơ của 1 hồ sơ
   Lỗi: thành phần hồ sơ có nhận số giấy tờ nhưng không hiển thị lên
   ![16processmgtprocessorderdossierfile](https://cloud.githubusercontent.com/assets/17695836/16974413/8b2533e8-4e66-11e6-9d40-de358aab3886.png)

**Comment by khoahp** [comment]
@binhth

**Comment by tragiangdt** [comment]
@binhth Chưa được nhé

**Comment by tragiangdt** [comment]
Đã lên số giấy tờ
