### ISSUE TITLE
UIUX - Portet 19 tìm kiếm trên trang chủ

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#646]
@binhth chỉnh sửa lại phần hiển thị dữ liệu theo thiết kế mới

Cập nhật lại địa chỉ file
https://drive.google.com/folderview?id=0B-1snMLbTiwIOEtNUndEWUJ1eEU&usp=sharing

Ưi tiên cao nhé

**Comment by khoahp** [comment]
@tragiangdt test lại nhé, anh thấy chuẩn theo thiết kế mới rồi

**Comment by Hongnt31** [comment]
@khoahp anh kiểm tra lại giúp em
TH1:
1.Chọn tìm kiếm hồ sơ.
2.Nhập key tìm kiếm "201607296160"
KQ  trả về không đúng
![hinh ch p t 2016-08-01 16-48-52](https://cloud.githubusercontent.com/assets/20554327/17290269/da2df75e-5807-11e6-8198-a781bba45593.png)
TH2:
1.Chọn tìm kiếm thủ tục hành chính
2.Nhập key tìm kiếm "201607296160"
KQ  trả về không đúng
![hinh ch p t 2016-08-01 16-50-47](https://cloud.githubusercontent.com/assets/20554327/17290331/238e8918-5808-11e6-9e9a-4a6e672c2824.png)
TH3: 
1.Chọn tìm kiếm giấy tờ
2.Nhập key tìm kiếm "201607207946"
KQ  trả về không đúng
![hinh ch p t 2016-08-01 16-51-47](https://cloud.githubusercontent.com/assets/20554327/17290452/afbebbe2-5808-11e6-8b58-42eacbbb8942.png)

**Comment by tragiangdt** [comment]
test done
