### ISSUE TITLE
UIUX - Module login theo thiết kế mới

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/opencps#648]
@dunglt91 chỉnh sửa lại phần JSP

Link 

https://drive.google.com/folderview?id=0B-1snMLbTiwITU1DUVhKUUNBQjQ&usp=sharing

@trungnt-ksnb giúp cho phần hook nhé

**Comment by Hongnt31** [comment]
@khoahp anh kiểm tra giúp em
- ghi chú textbox email viết đúng theo thiết kế "Địa chỉ email"
- thêm ghi cho textbox pass theo đúng thiết kế  "Mật khẩu"
- Viết đúng "Quên mật khẩu ?"
  ![hinh ch p t 2016-08-01 17-28-31](https://cloud.githubusercontent.com/assets/20554327/17291326/662350e2-580d-11e6-969c-4bfd053b9ae9.png)

**Comment by khoahp** [comment]
@dunglt91 sửa lại theo đúng thiết kế nhé, dung place holder trong các input theo thiết kế. Chuẩn chỉ từ chi tiết nhỏ nhất.

**Comment by dunglt91** [comment]
@tragiangdt fixed

**Comment by tragiangdt** [comment]
test done
