### ISSUE TITLE
Chưa hiển thị nội dung thông báo phí trên tab Kết quả 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#649]
- Chưa hiển thị nội dung thông báo phí trên tab Kết quả 
- Chưa việt hóa
  ![2016-07-20_114129](https://cloud.githubusercontent.com/assets/17695836/16975331/69cbcdde-4e6f-11e6-89cc-4464f6cbc987.png)

**Comment by khoahp** [comment]
Phần này anh xử lý

**Comment by khoahp** [comment]
@tragiangdt cái này được chưa

**Comment by tragiangdt** [comment]
@khoahp 
- Chưa hiển thị nội dung thông báo phí trên tab Kết quả: Phần này đang hiển thị nội dung ghi chú của người xử lý bước trước (phải hiển thị nội dung trong cấu hình sinh phí $$)

**Comment by khoahp** [comment]
@tragiangdt em test lại nhé

**Comment by tragiangdt** [comment]
Anh @khoahp : Anh cho thêm hiển thị cả số tiền trên thông báo (Ghi chú + tổng số tiền)

![2016-09-22_140201](https://cloud.githubusercontent.com/assets/17695836/18739648/44c69ae0-80cf-11e6-9361-edcf018e2a7d.png)

**Comment by khoahp** [comment]
@tragiangdt test lai nhe, anh da bo xung them so tien vao

**Comment by tragiangdt** [comment]
@khoahp 
Vẫn còn lỗi:
1. chỗ số tiền có kỹ tự ¤
2. sau text GCN chưa có dấu cách "GCN(¤"
![2016-09-22_173520](https://cloud.githubusercontent.com/assets/17695836/18745051/f9c04d72-80ea-11e6-826d-81c40d6d3214.png)

**Comment by khoahp** [comment]
@tragiangdt đầu giờ chiều test lại lỗi này nhé

**Comment by Hongnt31** [comment]
1. ok
2. sau text GCN chưa có dấu cách "GCN(¤"

**Comment by Hongnt31** [comment]
@khoahp  vẫn chưa có dấu cách giữa GCN và dấu "("
![image](https://cloud.githubusercontent.com/assets/20554327/20174961/226b856c-a773-11e6-9af4-75776e7a9137.png)

**Comment by khoahp** [comment]
@Hongnt31 anh vừa cập nhật bản mới, hần này em test lại nhé

**Comment by Hongnt31** [comment]
@khoahp  Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20208925/cfb4d38a-a823-11e6-8603-e5aea90eb369.png)
