### ISSUE TITLE
Chưa việt hóa businessDomain, businessType , cityID, districtId, wardId

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#651]
Vào tài khoản quản trị, vào quản lý tài khoản công dân tổ chức
Xem chi tiết tài khoản doanh nghiệp
![2016-07-20_150716](https://cloud.githubusercontent.com/assets/17695836/16980390/ea96667a-4e8f-11e6-9080-b3f5cc592282.png)
![2016-07-20_153039](https://cloud.githubusercontent.com/assets/17695836/16980440/2650f838-4e90-11e6-92ba-660128a476db.png)

**Comment by khoahp** [comment]
@dunglt91 sửa luôn nếu xuất hiện trong màn hình thiết kế mới nhé

**Comment by dunglt91** [comment]
anh @trungnt-ksnb xem lại cái này anh nhé, nó ra key dạng city-id đã thì mới Việt hóa được còn key như này em Việt hóa cũng không có thay đổi gì

**Comment by khoahp** [comment]
@dunglt91 phần citi-id vs citiId có gì khác nhau đâu nhỉ? nó là cặp biến và giá trị dạng String để mapping thôi mà?

@trungnt-ksnb xem nó là ntn?

**Comment by dunglt91** [comment]
@khoahp nếu key là citiId thì em việt hóa nó vẫn ra như thế.

**Comment by khoahp** [comment]
@tragiangdt theo màn hình mới thì đã việt hoá nhé

**Comment by tragiangdt** [comment]
test done
