### ISSUE TITLE
Chưa hiển thị các thành phần bắt buộc trên màn hình chuẩn bị hồ sơ 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#652]
1. Đăng nhập tào khoản doanh nghiệp
2. Thêm mới 1 hồ sơ
   .3 Vào thành phần hồ sơ
   Lỗi: Chưa hiển thị các thành phần bắt buộc trên màn hình chuẩn bị hồ sơ

**Comment by khoahp** [comment]
@trungnt-ksnb phần này theo thiết kế có thành phần bắt buộc không? nếu có ông cho vào nhé

**Comment by khoahp** [comment]
@huymq em xử lý cái này nhé

**Comment by khoahp** [comment]
@tragiangdt em test lại nhé

**Comment by tragiangdt** [comment]
trên qa hiện vẫn là không đánh dấu thành phần bắt buộc lên trên màn hình chuẩn bị hồ sơ

**Comment by Hongnt31** [comment]
@khoahp 
Vẫn còn lỗi này
![image](https://cloud.githubusercontent.com/assets/20554327/20132539/0377b5c8-a696-11e6-9ea7-6a43f48c1af1.png)

**Comment by Hongnt31** [comment]
@khoahp  Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20384370/1fb4fd58-ace6-11e6-8e7f-411ed059688f.png)
