### ISSUE TITLE
Xuất hiện popup danh sách hồ sơ

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#653]
1.Đăng nhập tài khoản doanh nghiệp
2.Tạo hồ sơ mới
3. Vào thành phần hồ sơ, vào màn hình đính kèm file
4. Nhập tên file không chọn file đính kèm
5.Nhấn đồng ý
KQ: Xuất hiện thông báo chưa được việt hóa
6. Đính kèm file
7. Nhấn đồng ý
KQ: xuất hiện popup danh sách hồ sơ

![hinh ch p t 2016-07-20 15-58-15](https://cloud.githubusercontent.com/assets/20554327/16981363/8936fcbe-4e94-11e6-8dc0-53a4198072ee.png)

**Comment by khoahp** [comment]
@Hongnt31 cần cho biết thông báo chưa việt hoá nội dung là gì? Nội dung sau khi việt hoá là gì nhé@

**Comment by binhth** [comment]
@khoahp clear session error when action success

**Comment by binhth** [comment]
@Hongnt31

**Comment by Hongnt31** [comment]
test done
