### ISSUE TITLE
Tại trang đăng ký tài khoản công dân/tổ chức: Phần tải CMTND/Hộ chiếu cho phép tải lên cả loại file PDF

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#654]
Tại trang đăng ký tài khoản công dân/tổ chức: Phần tải CMTND/Hộ chiếu cho phép tải lên cả loại file PDF

**Comment by dunglt91** [comment]
@tragiangdt @khoahp  fixed

**Comment by tragiangdt** [comment]
@dunglt91  Hiện tại khi đăng ký tài khoản công dân, hệ thống đều báo "Lỗi hệ thống" a

**Comment by khoahp** [comment]
@tragiangdt @trungnt-ksnb  phần đăng ký tài khoản công dân, đăng ký được nhưng không thấy gửi email xác nhận, tài khoản doanh nghiệp lỗi phần chọn taglib danh mục tỉnh huyện xã.
Trung xem hộ lại phần này nhé!

**Comment by dunglt91** [comment]
@trungnt-ksnb Anh Trung xem laij phần tạo DLfolder bị dính cái này “[stdout](http-/0.0.0.0:80-2)        at com.liferay.portlet.documentlibrary.service.permission.DLFolderPermission.check(DLFolderPermission.java:62)”

**Comment by tragiangdt** [comment]
test done
