### ISSUE TITLE
Phân trang Dossier BackOffice Management lỗi

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#668]
Phân trang Dossier BackOffice Management lỗi
1. Chọn các trang trên cổng
2. Nhấn nút Cuối cùng ->

**Comment by dunglt91** [comment]
@tragiangdt cái này kiểm tra lại nhé

**Comment by tragiangdt** [comment]
@dunglt91 Vẫn lỗi thế mà

**Comment by dunglt91** [comment]
@tragiangdt backofffice là trang cán bộ?
Cậu gửi links cho tớ xem tnao @@!

**Comment by tragiangdt** [comment]
@dunglt91 
Link: http://qa.opencps.vn/web/guest/tra-cuu-ho-so?p_p_id=18_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_18_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fprocessmgt%2Fbackofficedossier%2Fbackofficedossierlist.jsp&_18_WAR_opencpsportlet_tab1=top_tabs_dossierlist&_18_WAR_opencpsportlet_delta=20&_18_WAR_opencpsportlet_keywords=&_18_WAR_opencpsportlet_advancedSearch=false&_18_WAR_opencpsportlet_andOperator=true&_18_WAR_opencpsportlet_groupId=20182&_18_WAR_opencpsportlet_createDate=01%2F08%2F2016+13%3A58%3A21&_18_WAR_opencpsportlet_receiveDatetime=01%2F08%2F2016+13%3A58%3A21&_18_WAR_opencpsportlet_dossierStatus=new&_18_WAR_opencpsportlet_serviceDomainCode=&_18_WAR_opencpsportlet_orderByCol=&_18_WAR_opencpsportlet_orderByType=&_18_WAR_opencpsportlet_resetCur=false&_18_WAR_opencpsportlet_cur=25

**Comment by dunglt91** [comment]
Tổng nó có 25 page nên bấm trang cuối cùng 25 trang nó ko có @@! kết quả.
Kq nó đến có 4 trang thôi mà.

**Comment by dunglt91** [comment]
@trungnt-ksnb anh xem giúp em cái này với, lỗi này em bó tay ạ :(

**Comment by dunglt91** [comment]
@tragiangdt da fix

**Comment by tragiangdt** [comment]
test done
