### ISSUE TITLE
Chưa tìm kiếm theo mã tiếp nhận, lọc theo lĩnh vực thủ tục ở màn hình tra cứu hồ sơ Dossier BackOffice Management

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#669]
Chưa tìm kiếm theo mã tiếp nhận, lọc theo lĩnh vực thủ tục ở màn hình tra cứu hồ sơ Dossier BackOffice Management

**Comment by tragiangdt** [comment]
test done trên qa

**Comment by thanhld2901** [comment]
@tragiangdt Phần này kiểm tra lại đã tìm kiếm OK
