### ISSUE TITLE
Cột tình trạng hiển thị trắng trên danh sách tra cứu hồ sơ Dossier BackOffice Management

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#670]
Cột tình trạng hiển thị trắng trên danh sách tra cứu hồ sơ Dossier BackOffice Management

**Comment by thanhld2901** [comment]
@tragiangdt Giang test lai giúp anh nhé

**Comment by Hongnt31** [comment]
Test done trên opencps -dev

**Comment by Hongnt31** [comment]
@tragiangdt  @khoahp  vẫn còn lỗi trên qa.opencps.vn
![image](https://cloud.githubusercontent.com/assets/20554327/20136669/a42883c8-a6a8-11e6-8205-4e4c3cf0d0ce.png)

**Comment by khoahp** [comment]
@nhan0987 xử lý nhé

**Comment by tragiangdt** [comment]
@nhan0987 
Vẫn còn lỗi 
![2017-03-30_180521](https://cloud.githubusercontent.com/assets/17695836/24501400/8847e9a2-1573-11e7-80fa-625cac7b5620.png)

**Comment by khoahp** [comment]
@tragiangdt phần này a đã cập nhật lại,

@Hongnt31 test lại cho anh lỗi này nhé

**Comment by Hongnt31** [comment]
@khoahp  
Hiển thị tình trạng vẫn sai
- Hồ sơ vừa mới nộp ngày hôm nay đã báo đã quá hạn
![image](https://cloud.githubusercontent.com/assets/20554327/24536148/bee2a7e2-1602-11e7-94b4-534d386214d8.png)

**Comment by khoahp** [comment]
@Hongnt31 phần này em tạo một issue khác nhé, phàn hiển thị lỗi do phần tính ngày quá hạn bị sai, lỗi không hiển thị tình trạng đã được hiển thị ra
