### ISSUE TITLE
Danh sách tra cứu hồ sơ Dossier BackOffice Management chưa sắp sếp theo ngày nhận hồ sơ mới-cũ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#671]
Danh sách tra cứu hồ sơ Dossier BackOffice Management chưa sắp sếp theo ngày nhận hồ sơ vào hệ thống CBXL mới-cũ

**Comment by thanhld2901** [comment]
@tragiangdt Giang test lai giúp anh nhé

**Comment by Hongnt31** [comment]
test done trên opencps-dev

**Comment by Hongnt31** [comment]
@khoahp 
test done
