### ISSUE TITLE
Chưa xem được chi tiết hồ sơ trên danh sách tra cứu hồ sơ Dossier BackOffice Management

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#672]
Chưa xem được chi tiết hồ sơ trên danh sách tra cứu hồ sơ Dossier BackOffice Management

**Comment by khoahp** [comment]
@tragiangdt anh close issue này, chuyển các issue của quản lý giấy tờ lưu trữ về issue mới, trong phiên bản 2.0 nhé
