### ISSUE TITLE
Không xem được màn hình quản lý tìm kiếm giấy tờ lưu trữ (Dossier BackOffice Management) 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#673]
Không xem được màn hình quản lý tìm kiếm giấy tờ lưu trữ (Dossier BackOffice Management) 
Kích vào tab Giấy tờ, hệ thống hiển thị danh sách hồ sơ

**Comment by khoahp** [comment]
@tragiangdt phần này chuyển lên 2.0 nhé

**Comment by thanhld2901** [comment]
Giang báo đã xem được OK

**Comment by Hongnt31** [comment]
@khoahp @tragiangdt  Vẫn còn lỗi này:
Không xem được màn hình quản lý tìm kiếm giấy tờ lưu trữ (Dossier BackOffice Management)
Kích vào tab Giấy tờ, hệ thống hiển thị danh sách hồ sơ

**Comment by khoahp** [comment]
Phần tìm kiếm giấy tờ chuyển @nhan0987 thực hiện nhé

**Comment by nhan0987** [comment]
Đã kiểm tra, xem được bình thường

**Comment by Hongnt31** [comment]
Done

**Comment by tragiangdt** [comment]
@khoahp Vẫn chưa xem được tab giấy tờ khi tra cứu hồ sơ trên qa
![2017-03-30_173937](https://cloud.githubusercontent.com/assets/17695836/24500535/f382ed74-156f-11e7-862e-34bcf4e1a146.png)

**Comment by khoahp** [comment]
@Hongnt31 em test lại cho anh nhé

**Comment by Hongnt31** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/20554327/24535679/c52a455e-15ff-11e7-9599-023b7b427675.png)
