### ISSUE TITLE
Sau khi tạo mới mẫu hồ sơ, nhấn nút lưu thì hệ thống không giữ nguyên màn hình 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#675]
Sau khi tạo mới mẫu hồ sơ, nhấn nút lưu thì hệ thống không giữ nguyên màn hình (hiện tại đang quay lại danh sách mẫu hồ sơ)

**Comment by dunglt91** [comment]
@tragiangdt @khoahp  fixed

**Comment by khoahp** [comment]
@tragiangdt test lại nhé

**Comment by tragiangdt** [comment]
@khoahp  @dunglt91 
Trên qa vẫn còn lỗi này a

**Comment by khoahp** [comment]
@dunglt91

**Comment by dunglt91** [comment]
@tragiangdt cậu muốn kịch bản là thế nào, giữ nguyên màn hình là màn hình thêm mới hay màn hình đăng kí xong nó  hiện thêm 2 tab nữa, nếu GIỮ NGUYÊN MÀN hình thì qa nó thêm xong nó giữ nguyên màn hinh thêm mới rồi mà?

**Comment by tragiangdt** [comment]
@dunglt91 
1. click Thêm mới hồ sơ
2. Điền thông tin, click Ghi lại
3. màn hình Ghi lại xong nó hiện thêm 2 tab (TPHS + TTHC) nữa

**Comment by dunglt91** [comment]
@khoahp anh merge vào cho @tragiangdt test nhé.

**Comment by khoahp** [comment]
@dunglt91 phần này  anh đã merge lại và deploy lên QA

@tragiangdt kiểm tra lại nhé!

**Comment by tragiangdt** [comment]
test done
