### ISSUE TITLE
Hiển thị dịch vụ công chưa được gán quy trình xử lý trên màn hình tạo mới hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#677]
1. Đăng nhập tài khoản doanh nghiệp
2. Vào quản lý hồ sơ, nhấn nút Tạo mới hồ sơ
   Lỗi: Hiển thị dịch vụ công chưa được gán quy trình xử lý trên màn hình tạo mới hồ sơ

**Comment by khoahp** [comment]
@trungnt-ksnb xử lý nhé

**Comment by khoahp** [comment]
@huymq em care cái này nhé

**Comment by tragiangdt** [comment]
Issue này không phù hợp TH phân tán
