### ISSUE TITLE
Dữ liệu thông tin tab thủ tục hành chính bị đè lên dữ liệu tab khác

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#693]
Trên trình duyệt chrome
1. Đăng nhâp TK admin
2. Vào thủ tục hành chính 
3. Chọn thủ tục "Cấp giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm đối với các cơ sở sản xuất, kinh doanh thực phẩm thuộc thẩm quyền Bộ Y tế "
KQ: xuất hiện lỗi
![hinh ch p t 2016-07-26 10-28-07](https://cloud.githubusercontent.com/assets/20554327/17125278/4bb3b5e4-531c-11e6-994f-5c20792c1de9.png)

**Comment by khoahp** [comment]
@dunglt91 xem lỗi này có phải khi chưa deploy theme không nhé?

**Comment by dunglt91** [comment]
@Hongnt31 test lại nhé

**Comment by Hongnt31** [comment]
Test done
