### ISSUE TITLE
Thừa nút tạo form ở giao diện nhập dữ liệu trên form động (thiết kế không có)

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#695]
Mockup thiết kế:
https://raw.githubusercontent.com/VietOpenCPS/doc/master/SRS/dossiermgt/13dossiermgtfrontofficedossierfileform.png

**Comment by huymq** [comment]
@tragiangdt capture màn hình em nhé

**Comment by tragiangdt** [comment]
Màn hình này ko giống thiết kế
