### ISSUE TITLE
Lỗi chức năng xem trước trên form khai động

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#699]
Tại màn hình trên form khai động:
1. Nhập thông tin
2. Nhấn nút Xem trước (Chưa nhấn Ghi lại)
Lỗi: Hệ thống cứ xoay mãi, không báo gì cả

**Comment by khoahp** [comment]
Khoa Vũ, [01.08.16 09:31]
cái này là lỗi phần jasper của mình chứ nhỉ

FDS BìnhTH, [01.08.16 09:31]
cái này quay mãi là do jaser bị lỗi ko fix code đâu a @khoavd . bị cái nào thì check lại jasper thôi

@tragiangdt do lỗi jasper nên anh sẽ close lỗi này vào nhé?

**Comment by tragiangdt** [comment]
@khoahp  
TH lỗi này là chưa nhấn nút Ghi lại, mà nhấn nút Xem trước thì hệ thống đều quay vậy. 
Nếu nhấn Ghi lại trước rồi mới nhấn Xem trước thì không bị lỗi

**Comment by khoahp** [comment]
@binhth em xem lại phần này nhé!

**Comment by tragiangdt** [comment]
Màn hình này sai thiết kế
https://raw.githubusercontent.com/VietOpenCPS/doc/master/SRS/dossiermgt/13dossiermgtfrontofficedossierfileform.png
