### ISSUE TITLE
Nhận lưu khi tạo mới thành phần hồ sơ thì load tới form cập nhật hồ sơ

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#713]
1.Đăng nhập TK admin
2. Thêm thành phần sơ
3. Nhập đầy đủ thông tin một thành phần hồ sơ
4. Nhấn "Đồng ý"
KQ: load tới form cập nhật hồ sơ
KQMM: load tới form thành phần hồ sơ

**Comment by khoahp** [comment]
@trungnt-ksnb xử lý cái này chứ

**Comment by khoahp** [comment]
@dunglt91 phần này cấu hình dịch vụ công, em xử lý nhé

**Comment by dunglt91** [comment]
@Hongnt31 load về form đó là đúng rồi em, nó là cái navigator gồm 3 tab đấy. Có 2 trường hơp:
nếu thêm thành phần hồ sơ lỗi : đứng yên tại màn hình thêm hồ sơ và thông báo lỗi.
Nếu thêm thành công trở về form mẫu hồ sơ gồm 3 thành phần : 
tab1 : mẫu hs, 
tab2 : danh sách tphs (gắn mới mẫu hs)
tab3: danh sách dịch vụ công (gắn với mẫu hs)
Việc nó quay về tab Mẫu hồ sơ là chấp nhận được, anh đề nghị đóng bug này!

**Comment by Hongnt31** [comment]
@dunglt91 theo em nên cho load đến form thành phần hồ sơ vì: 
1. Người dùng vừa thêm thành phần hồ sơ sau khi thành công thì người dùng muốn xem lại thành phần hồ sơ vừa tạo
2. Một hồ sơ sẽ có nhiều thành phần hồ sơ, khi người dùng thêm một thành phần hồ sơ xong lại cho load đến form cập nhật hồ sơ sẽ bận tiện khi lại phải click vào tab thành phần hồ sơ rùi mới thêm mới

**Comment by dunglt91** [comment]
1. Cái này thiết kế là vậy, Form cập nhật hồ sơ chứa nhiều thành phần hồ sơ. Khi nào thêm thành công thì nó quay lại form câp hồ sơ, còn thêm thất bại thì đứng yên, anh thấy cái này không vấn đề gì cả và các phần khác đều như vậy, dấu hiệu của thêm thành công là quay về danh sách hoặc nơi chứa danh sách.
2. Còn việc bất tiện, anh nghĩ cũng chưa chắc, vì khi thêm TPHS xong người dùng muốn thêm TPHS mới (thường là như này vì có nhiều TPHS trong bộ HS), nếu đứng nguyên màn hình nhập TPHS như em nói thì thêm TPHS mới người dùng lại phải back lại để thêm mới, vậy cũng bất tiện.

@Hongnt31
