### ISSUE TITLE
Lỗi tiếp nhận hồ sơ qua mạng

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#717]
1. Vào menu tiếp nhận hồ sơ
2. Chọn mô tả
   Lỗi: không hiển thị hướng dẫn nộp hồ sơ qua mạng + nút nộp hồ sơ qua mạng
   (phải chọn cấp quản lý khác, sau đó đó chọn lại cấp QL cũ thì mới hiển thị hướng dẫn nộp hồ sơ qua mạng + nút nộp hồ sơ qua mạng)

**Comment by khoahp** [comment]
@dunglt91 xử lý phần này nhé, đây là phần hướng dẫn nộp hồ sơ qua mạng

**Comment by khoahp** [comment]
@giangdt test lại phàn này em nhé

**Comment by dunglt91** [comment]
@tragiangdt test lai di nhe

**Comment by tragiangdt** [comment]
test done
