### ISSUE TITLE
Không hiển thị địa chỉ tỉnh, huyện, xã của người làm thủ tục

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#718]
1. Đăng nhập tk cán bộ
2. Vào xem chi tiết 1 hồ sơ
   lỗi: Không hiển thị tỉnh, huyện, xã của người làm thủ tục (mới hiển thị địa chỉ)
   ![2016-07-28_144310](https://cloud.githubusercontent.com/assets/17695836/17204819/cee30256-54d1-11e6-9475-a0191f267237.png)

**Comment by khoahp** [comment]
@tragiangdt test lại đi em

**Comment by tragiangdt** [comment]
@khoahp 
Vẫn còn lỗi anh nhé. 
chưa hiển thị được Tỉnh/tp, Huyện/Quận, Xã/Phường của NLTT
![2016-08-01_133951](https://cloud.githubusercontent.com/assets/17695836/17285568/ad74c45a-57ed-11e6-85cf-2f627f5969a3.png)

**Comment by khoahp** [comment]
@tragiangdt em test lại nhé

**Comment by Hongnt31** [comment]
@khoahp  anh ơi vẫn bị lỗi này ạ 
![hinh ch p t 2016-08-01 15-41-10](https://cloud.githubusercontent.com/assets/20554327/17288290/88a2f190-57fe-11e6-9223-a24f20fdfc1b.png)

**Comment by khoahp** [comment]
@binhth xem lại nhé,

**Comment by binhth** [comment]
@khoahp anh thử xóa temp restart lại xem, trên con có mỗi dòng code + thêm value vào đó cả trên local + trên con 2780 của em đều hiển thị 3 cấp theo thứ tự address + [name xã] + [name huyện] + [name tỉnh]

**Comment by khoahp** [comment]
@binhth anh vừa deploy theo quy trình tiêu chuẩn rồi nhé, xoá tmp, khởi động lại.

@Hongnt31 em kiểm tra lại giúp anh nhé!

**Comment by Hongnt31** [comment]
@khoahp  chưa có dấu phẩy ngăn cách đia chỉ,phường/xã,quận/huyện,tỉnh/thành phố
![hinh ch p t 2016-08-01 17-07-15](https://cloud.githubusercontent.com/assets/20554327/17290848/b858f4be-580a-11e6-9f96-cc0d22558b97.png)

**Comment by khoahp** [comment]
@binhth fix lỗi này phát nhé để đóng issue

**Comment by binhth** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
