### ISSUE TITLE
lỗi thêm chức vụ xong xuất hiện form thông tin chung

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#721]
1. Đăng nhập TK admin
2. Vào quản lý cán bộ/Thay đổi thông tin tổ chức/chọn thêm chức vụ
3. Nhập đầy đủ thông tin thêm chức vụ
4. Nhấn ghi lại
   KQ: hiển thị màn hình thông tin chung
   KQMM: hiển thị màn hình danh sách chức vụ

**Comment by khoahp** [comment]
Chuyển sang 1.5

**Comment by khoahp** [comment]
@dunglt91 cho giải pháp thực hiện phần này nhé

**Comment by dunglt91** [comment]
@Hongnt31 done!

**Comment by Hongnt31** [comment]
done trên firefox phiên bản 47.0 trên HĐH win và fedora
còn lỗi trên trình duyệt chrome phiên bản  51.0.2704.106  trên HĐH fedora khi thêm mới không load lại form
