### ISSUE TITLE
Lỗi thừa button hủy bỏ form cập nhật thông tin một bước xử lý 

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#722]
![hinh ch p t 2016-07-29 09-46-34](https://cloud.githubusercontent.com/assets/20554327/17236298/3fdbadfa-5572-11e6-8070-0eb1bcb0fde2.png)

**Comment by khoahp** [comment]
@Hongnt31 test lại đi em

**Comment by Hongnt31** [comment]
@khoahp  anh ơi lỗi này vẫn còn ạ

**Comment by khoahp** [comment]
@Hongnt31 : http://qa.opencps.vn/web/guest/quan-ly-quy-trinh?p_p_id=15_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_15_WAR_opencpsportlet_serviceProcessId=1&_15_WAR_opencpsportlet_redirectURL=%2Fweb%2Fguest%2Fquan-ly-quy-trinh%3Fp_p_id%3D15_WAR_opencpsportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_15_WAR_opencpsportlet_mvcPath%3D%252Fhtml%252Fportlets%252Fprocessmgt%252Fadmin%252Fedit_process.jsp%26_15_WAR_opencpsportlet_serviceProcessId%3D1%26_15_WAR_opencpsportlet_backURL%3D%252Fweb%252Fguest%252Fquan-ly-quy-trinh&_15_WAR_opencpsportlet_processStepId=7&_15_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fprocessmgt%2Fadmin%2Fedit_step.jsp

Em test lại trên con QA nhé, anh kiểm tra thấy không còn lỗi này

**Comment by tragiangdt** [comment]
@Hongnt31 @khoahp 
Test done
