### ISSUE TITLE
Chưa việt hóa tooltip Cbx lọc theo lĩnh vực thủ tục

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#725]
![hinh ch p t 2016-07-29 13-53-03](https://cloud.githubusercontent.com/assets/20554327/17240212/18cc9216-5594-11e6-8d07-301525cd0e0c.png)

**Comment by binhth** [comment]
@Hongnt31

**Comment by Hongnt31** [comment]
test done
