### ISSUE TITLE
Chưa việt hóa tên cbx kính thước trang

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#726]
Ví dụ : 20 Items per Page đổi thành "Kính thước trang 20"
![hinh ch p t 2016-07-29 13-58-46](https://cloud.githubusercontent.com/assets/20554327/17240313/de97dc80-5594-11e6-9aa3-61c37ae9ad1f.png)

**Comment by khoahp** [comment]
@Hongnt31 em title lỗi em viết hoa chữ đầu nhé!

20 Items per Page anh việt hoá thành -> 20 bản ghi trên trang được không? chứ Kính thước trang 20 chưa hiểu là cái gì?

**Comment by Hongnt31** [comment]
Dạ vâng anh để vậy cũng được ạ

**Comment by khoahp** [comment]
@binhth em cập nhật cho anh cái key item-per-page nhé
