### ISSUE TITLE
Lỗi chưa lấy được địa chỉ của doanh nghiệp khi tạo một hồ sơ mới

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#730]
1.Đăng nhâp TK doanh nghiệp
2.Vào Quản lý hồ sơ/Thêm mới hồ sơ
KQ: Chưa lấy được địa chỉ của doanh nghiệp
KQMM: lấy được địa chỉ doanh nghiệp
![hinh ch p t 2016-07-30 10-56-46](https://cloud.githubusercontent.com/assets/20554327/17267991/90a72656-5644-11e6-9eb9-acdec55e7b03.png)

**Comment by khoahp** [comment]
@Hongnt31 test lại phần này nhé

**Comment by Hongnt31** [comment]
Test done

**Comment by khoahp** [comment]
Okie
