### ISSUE TITLE
Thêm chức vụ chưa có thông báo khi nhập tiêu đề trùng với tiêu đề đã có trong DB

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#733]
1.Đăng nhập TK admin
2.Vào quản lý cán bộ/Thêm chức vụ
3.Nhập tiêu đề trùng với tiêu đề đã có trong DB
4.Nhấn Ghi lại
KQ: Không có thông báo gì nhảy luôn về form màn hình thông tin chung
KQMM: Hiển thị thông báo tiêu đề đã tồn tại

**Comment by khoahp** [comment]
@dunglt91 bổ xung các validator còn thiếu nhé.

**Comment by dunglt91** [comment]
@Hongnt31

**Comment by Hongnt31** [comment]
@dunglt91  vẫn còn lỗi này anh nhé

**Comment by Hongnt31** [comment]
@huymq  test done
![Uploading Hình chụp từ 2016-08-24 10-29-12.png…]()

**Comment by Hongnt31** [comment]
@dunglt91  anh ơi hiện tại nó có lỗi là: 
- mình chỉ bắt trùng trong 1 tổ chức thôi còn khác tổ chức vẫn cho phép trùng

**Comment by Hongnt31** [comment]
test done
