### ISSUE TITLE
Mất tab thao tác 

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#736]
1.Đăng nhập TK admin
2.Vào Quản lý quy trình/Quản lý quy trình xử lý thủ tục/Thao tác
KQ: bị mất dữ liệu, không có button thêm thao tác
KQMM: hiển thị đúng như thiết kế .
link thiết kế: https://github.com/VietOpenCPS/doc/wiki/Ph%C3%A2n-t%C3%ADch-qu%E1%BA%A3n-l%C3%BD-quy-tr%C3%ACnh-x%E1%BB%AD-l%C3%BD-h%E1%BB%93-s%C6%A1
![hinh ch p t 2016-07-30 18-49-15](https://cloud.githubusercontent.com/assets/20554327/17270170/b4a9d002-5686-11e6-9da8-d04fbe0eda21.png)

**Comment by khoahp** [comment]
@Hongnt31 a fix rồi nhé

**Comment by Hongnt31** [comment]
Test done
