### ISSUE TITLE
Chưa việt hóa lable tỉnh, huyện, xã của doanh nghiệp

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#737]
1.Đăng nhập TK doanh nghiệp
2.Vào Quản lý hồ sơ/Thêm mới hồ sơ
KQ:chưa việt hóa lable tỉnh, huyện, xã của doanh nghiệp 
KQMM: Việt hóa  lable tỉnh, huyện, xã của doanh nghiệp
![hinh ch p t 2016-08-01 09-56-55](https://cloud.githubusercontent.com/assets/20554327/17282263/5188c638-57ce-11e6-9d1b-3b3bbea20be8.png)

**Comment by khoahp** [comment]
@binhth phần này do đâu bình nhỉ? anh nghĩ cho vào file hook là okie thôi chứ nhỉ

**Comment by binhth** [comment]
@Hongnt31

**Comment by Hongnt31** [comment]
test done
