### ISSUE TITLE
 Màn hình cập nhật thông tin một quy trình 

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#745]
1.Đăng nhập TK admin
2.Vào Quản trị hệ thống/Quản lý quy trình
3.Màn hình cập nhật thông tin một quy trình xuất hiện
KQ: tên tab Hành động đổi thành "Thao tác xử lý " , button Ghi lại đổ thành "Lưu", button Hủy bỏ đổi thành "Quay lại" cho đúng với file phân tích
Link phân tích: https://github.com/VietOpenCPS/doc/wiki/Ph%C3%A2n-t%C3%ADch-qu%E1%BA%A3n-l%C3%BD-quy-tr%C3%ACnh-x%E1%BB%AD-l%C3%BD-h%E1%BB%93-s%C6%A1

**Comment by khoahp** [comment]
@Hongnt31 @tragiangdt phần này anh đề xuất vẫn để lại theo format chung của hệ thống là “Ghi lại” và "Huỷ bỏ". ?

**Comment by tragiangdt** [comment]
@khoahp 
- phần này anh đề xuất vẫn để lại theo format chung của hệ thống là “Ghi lại” và "Huỷ bỏ": Đồng ý với anh
- Vẫn còn lỗi "tên tab Hành động đổi thành "Thao tác xử lý ""

**Comment by khoahp** [comment]
@dunglt91 xử lý nhé

**Comment by tragiangdt** [comment]
@dunglt91 
Vẫn còn lỗi "tên tab Hành động đổi thành "Thao tác xử lý ""

**Comment by Hongnt31** [comment]
Test done 
![hinh ch p t 2016-08-18 17-56-13](https://cloud.githubusercontent.com/assets/20554327/17771432/128f2b6e-656d-11e6-9f12-a4f0d9c4ca6c.png)
