### ISSUE TITLE
Hiển thị sai label khi sửa đổi chức vụ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#748]
Trang cập nhật chức vụ:
![2016-08-01_152224](https://cloud.githubusercontent.com/assets/17695836/17287811/fd48790a-57fb-11e6-8bf5-40ea534b0f17.png)

Link: http://qa.opencps.vn/group/guest/quan-ly-can-bo?p_p_id=2_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_2_WAR_opencpsportlet_workingunitId=701&_2_WAR_opencpsportlet_redirectURL=%2Fgroup%2Fguest%2Fquan-ly-can-bo&_2_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fusermgt%2Fadmin%2Fedit_workingunit.jsp#_2_WAR_opencpsportlet_tab=_2_WAR_opencpsportlet_general_workingunit

Vào sửa đổi dịch vụ công cũng bị lỗi này

**Comment by khoahp** [comment]
@dunglt91 phần này từ submit dũng chuẩn lại trong phần hook là “Gửi”, các phần khác muốn sử dụng cần làm key khác.

**Comment by dunglt91** [comment]
done!

**Comment by khoahp** [comment]
@tragiangdt test cho anh phần này nhé

**Comment by tragiangdt** [comment]
@khoahp  @dunglt91 
trên qa vẫn còn lỗi này ạ

**Comment by tragiangdt** [comment]
@dunglt91 
Nút Ghi lại nào giờ cũng đổi thành "hồ sơ được gửi từ cổng...."

**Comment by khoahp** [comment]
anh em sửa ngay phần này nhé

**Comment by tragiangdt** [comment]
test done
