### ISSUE TITLE
Không hiển thị thông báo danh sách hồ sơ 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#761]
1. Vào tk NLTT
2. Vào menu Thông báo hồ sơ (http://qa.opencps.vn/group/guest/thong-bao-ho-so)
3. Không hiển thị thông báo danh sách hồ sơ 
   ![2016-08-02_092136](https://cloud.githubusercontent.com/assets/17695836/17315005/8c7f9e3c-5892-11e6-980f-afff1a0967c0.png)

**Comment by khoahp** [comment]
@dunglt91  kiểm tra lại portlet này nhé

**Comment by dunglt91** [comment]
@khoahp @tragiangdt fix done!

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại nhé

**Comment by tragiangdt** [comment]
test done
