### ISSUE TITLE
[UIUX] Màn hình thông tin hồ sơ của NLTT chưa sửa theo thiết kế

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#769]
[UIUX] Màn hình thông tin hồ sơ của NLTT chưa sửa theo thiết kế

**Comment by khoahp** [comment]
@tragiangdt fixed

**Comment by tragiangdt** [comment]
Trên qa chưa sửa màn hình thông tin hồ sơ theo thiết kế a

**Comment by khoahp** [comment]
@tragiangdt các lỗi về UIUX anh sẽ đóng vào
