### ISSUE TITLE
[UIUX] Thay text hiển thị "Xin chào ..." bằng icon

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#771]
1. Đăng nhập vào hệ thống
2. Thay text hiển thị tên user "Xin chào CÔNG TY TNHH...." bằng icon và có tooltip "Thông tin tài khoản"
   Click vào icon đó thì ra trang Thông tin tài khoản ứng với từng user đăng nhập
   ![2016-08-02_113614](https://cloud.githubusercontent.com/assets/17695836/17317215/5e77d7c6-58a5-11e6-88b1-7ae392941845.png)

**Comment by huymq** [comment]
@thanhld2901 anh xử lý. @dunglt91 hỗ trợ anh Thanh nhé

**Comment by dunglt91** [comment]
@tragiangdt done!

test trên con dev nhe

**Comment by tragiangdt** [comment]
test done
