### ISSUE TITLE
Thông báo hồ sơ chưa lọc theo user đăng nhập

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#772]
1. Thông báo hồ sơ chưa lọc theo user đăng nhập
2. Tiêu đề STT đổi thành "Số hồ sơ"

**Comment by huymq** [comment]
@d006141 fix nhé. @dunglt91 hỗ trợ Duy

**Comment by tragiangdt** [comment]
Link: http://qa.opencps.vn/group/guest/thong-bao-ho-so

**Comment by tragiangdt** [comment]
1. Đăng nhập vào tài khoản NLTT: doanhnghiep.cpss@gmail.com / congdan.cps@gmail.com
2. Vào menu Thông báo hồ sơ
   Link: http://qa.opencps.vn/group/guest/thong-bao-ho-so
3. Lỗi: Danh sách thông báo hồ sơ chưa lọc theo user tạo hồ sơ

**Comment by dunglt91** [comment]
@tragiangdt done!

**Comment by tragiangdt** [comment]
Đã test ok trên opencps-dev
