### ISSUE TITLE
Cán bộ không xem được form khai đơn trên nội dung hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#778]
1. Đăng nhập tk NLTT
2. Tạo hồ sơ
3. Nhập form khai trực tuyến
4. Nhấn Ghi lại (không nhấn nút Tạo form)
5. Gửi nộp hồ sơ
6. Đăng nhập tài khoản cán bộ, xem chi tiết hồ sơ mới nộp này.
   Lỗi: Trên tab Nội dung hồ sơ, không hiển thị nút Xem biểu mẫu

**Comment by binhth** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test done
