### ISSUE TITLE
Chưa có popup xác nhận khi NLTT gửi/bổ sung hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#779]
Chưa có popup xác nhận khi NLTT gửi/bổ sung hồ sơ

**Comment by khoahp** [comment]
@tragiangdt đây là màn hình confirm trước khi gửi à em?

**Comment by tragiangdt** [comment]
@khoahp 
vaang anh. trước khi gửi hoặc bổ sung hồ sơ thì nên có popup xác nhận doanh nghiệp có gửi hay ko

**Comment by khoahp** [comment]
@huymq xem bổ xung câu từ thế nào rồi cho thêm vào nhé.

**Comment by Hongnt31** [comment]
@khoahp  vẫn Chưa có popup xác nhận khi NLTT gửi/bổ sung hồ sơ

**Comment by khoahp** [comment]
@Hongnt31 @tragiangdt phần này anh đề xuất chuyển lên 1.8

**Comment by nhan0987** [comment]
Đã sửa

**Comment by tragiangdt** [comment]
test done
