### ISSUE TITLE
Lỗi liên tục phải reset lại hệ thống do bị lỗi gửi hồ sơ đi

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#786]
1.Vào TK doanh nghiệp
2.Tạo môt hồ sơ mới
3.Gửi hồ sơ đi
KQ: trạng thái hồ sơ là "Hệ thống"
Phải reset lại hệ thống thường xuyên

**Comment by khoahp** [comment]
@Hongnt31 phần này em mô tả rõ hơn được không? Gửi phân tán hay gửi local? Em test trên con QA hay con nào?

**Comment by Hongnt31** [comment]
@khoahp  hiện tại sáng nay bọn em gửi phân tán và bị lỗi trên con 2780 anh ạ

**Comment by khoahp** [comment]
@huymq

**Comment by huymq** [comment]
@Hongnt31 bug này done rồi em nhé. Anh sẽ close lại theo dõi thêm
