### ISSUE TITLE
[Backend phân tán]Doanh nghiệp gửi hồ sơ từ cổng, doanh nghiệp không nhận được mã tiếp nhận 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#805]
Doanh nghiệp gửi hồ sơ từ cổng, doanh nghiệp không nhận được mã tiếp nhận (bên cán bộ đã nhận được số tiếp nhận)

**Comment by khoahp** [comment]
@tragiangdt xem test lại nhé

**Comment by tragiangdt** [comment]
test done
