### ISSUE TITLE
[Backend phân tán] Đầu doanh nghiệp Gửi hồ sơ từ cổng, đầu cán bộ nhận được hồ sơ nhưng không xem được file đính kèm trong nội dung hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#806]
Doanh nghiệp Gửi hồ sơ từ cổng,  Cán bộ nhận được hồ sơ nhưng không xem được file đính kèm trong nội dung hồ sơ

**Comment by khoahp** [comment]
@tragiangdt test lại issue này rồi close vào nhé

**Comment by tragiangdt** [comment]
test done
