### ISSUE TITLE
[Backend phân tán] Thông tin ghi chú bổ sung chưa hiển thị trên yêu cầu xử lý 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#807]
1. Cán bộ yêu cầu bổ sung hồ sơ (nhập ghi chú bs)
   Hồ sơ bên đầu doanh nghiệp đã chuyển trạng thái Chờ bổ sung
2. Doanh nghiệp vào tab Kết quả 
   Lỗi: Thông tin ghi chú bổ sung chưa hiển thị trên yêu cầu xử lý

**Comment by khoahp** [comment]
@trungnt-ksnb xem giúp cho phần này nhé

**Comment by trungnt-ksnb** [comment]
@tragiangdt done

**Comment by tragiangdt** [comment]
test done
