### ISSUE TITLE
[Backend phân tán] Đầu NLTT không nhận được yêu cầu thanh toán

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#808]
Đầu NLTT không nhận được yêu cầu thanh toán

**Comment by khoahp** [comment]
@tragiangdt phần này đã fix rồi nhé, em test lại trên con phân tán. Anh @huymq trước đã fix lỗi này.

**Comment by tragiangdt** [comment]
@khoahp Hiện tại chưa test được lỗi này ạ

**Comment by tragiangdt** [comment]
test done
