### ISSUE TITLE
Lỗi không xuất được báo cáo khi nhập ký tự enter xuống dòng ở ô thuộc loại textaria trên form trực tuyến 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#815]
Lỗi không xuất được báo cáo khi nhập ký tự enter xuống dòng ở ô thuộc loại textaria trên form trực tuyến

**Comment by huymq** [comment]
@binhth làm xong thì comment để @tragiangdt biết nhé. @tragiangdt em test lại lỗi này nhé

**Comment by tragiangdt** [comment]
test done
