### ISSUE TITLE
Đăng kí tài khoản

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#839]
- Vào trang http://qa.opencps.vn/
- Chọn Đăng kí
  KQ lỗi:
- Chưa đánh dấu \* đỏ cho các trường bắt buộc nhập
- Chưa có dòng text: "Các trường đánh dấu \* là bắt buộc nhập"
- Số điện thoại chỉ cho phép nhập số: hiện tại vẫn nhập được chữ

**Comment by huymq** [comment]
@dunglt91 xử lý nhé

**Comment by huymq** [comment]
Dũng hướng dẫn Phúc @NVP191 nhé

**Comment by nvp191** [comment]
@dunglt91 lúc nào rảnh chỉ t phát nhé

**Comment by dunglt91** [comment]
@Hongnt31 nhỡ số điện thoại nhập kiểu +84.... thì nhập số sao được em?

**Comment by dunglt91** [comment]
@Hongnt31

**Comment by Hongnt31** [comment]
Còn lỗi nhập +84...ít hơn 10 ký tự vẫn chưa cảnh báo

**Comment by Hongnt31** [comment]
Test done
