### ISSUE TITLE
Đăng kí tài khoản công dân

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#840]
1.Vào http://qa.opencps.vn/
2.Chọn đăng kí công dân
3.Nhập đầy đủ đúng nội dung yêu cầu
4.Nhấn Đăng ký
KQ: Đăng ký thành công nhưng chưa có thông báo yêu cầu xác nhận email đăng kí cho người dùng biết
KQMM: Sau khi đăng kí thành công xong thông báo đăng kí thành công kèm yêu cầu xác nhận email đăng kí

**Comment by dunglt91** [comment]
@Hongnt31

**Comment by Hongnt31** [comment]
Vẫn chưa có thông báo
![hinh ch p t 2016-08-18 13-55-38](https://cloud.githubusercontent.com/assets/20554327/17764750/991adede-654b-11e6-8d96-801765388b28.png)

**Comment by Hongnt31** [comment]
Test done
![hinh ch p t 2016-08-18 17-40-20](https://cloud.githubusercontent.com/assets/20554327/17770987/f4ca2ee6-656a-11e6-81b3-1edb0460626b.png)
