### ISSUE TITLE
Lỗi link thông báo xác nhận email đăng kí tài khoản

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#841]
1.Đăng nhập vào email đăng kí
KQ: Please verify your email address for **http://localhost** at http://qa.opencps.vn/opencps-portlet/verify/email?token=b4ed4e84-67e7-4ad5-aa4a-5fa7c337be19&ticketKey=b7813247-7e28-47c4-b132-78d308c909a1&type=CITIZEN&p_l_id=22226.
KQMM: Please verify your email address for **http://qa.opencps.vn** at http://qa.opencps.vn/opencps-portlet/verify/email?token=b4ed4e84-67e7-4ad5-aa4a-5fa7c337be19&ticketKey=b7813247-7e28-47c4-b132-78d308c909a1&type=CITIZEN&p_l_id=22226.
![hinh ch p t 2016-08-11 11-45-22](https://cloud.githubusercontent.com/assets/20554327/17578960/bd289d30-5fb9-11e6-8f71-8e7cbbef315b.png)

**Comment by thanhld2901** [comment]
Anh kiểm tra lại lỗi này không thấy bị như mô tả.
@Hongnt31  xem lại giúp anh nhé

**Comment by Hongnt31** [comment]
Test done
