### ISSUE TITLE
Lỗi khi đăng kí tài khoản đã tồn tại email trong hệ thống

### ISSUE THREAD

**Issue by Hongnt31** [VietOpenCPS/opencps#843]
1.Vào http://qa.opencps.vn/
2.Chọn Đăng kí
3.Nhập đầy đủ thông tin có email trùng với email đã tồn tại
4.Nhấn Đăng ký
**KQ**: thông báo lỗi hệ thống
**KQMM**: cần thông báo email đã tồn tại
![hinh ch p t 2016-08-11 14-05-29](https://cloud.githubusercontent.com/assets/20554327/17580949/b27143fc-5fcc-11e6-887f-da3e57a90c55.png)

**Comment by huymq** [comment]
@Hongnt31 test lại giúp anh nhé

**Comment by Hongnt31** [comment]
test done
