### ISSUE TITLE
Lỗi lưu id loại hình tổ chức của doanh nghiệp vào DB khi sửa thông tin tài khoản

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#885]
Lỗi lưu id loại hình tổ chức của doanh nghiệp vào DB khi sửa thông tin tài khoản, phải lưu code

**Comment by khoahp** [comment]
Lỗi này @dunglt91 sửa rồi, @tragiangdt cho test lại nhé

**Comment by tragiangdt** [comment]
test done
