### ISSUE TITLE
Không sửa đổi được thông tin chi tiết thủ tục hành chính

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#896]
Quản trị không sửa đổi được thông tin chi tiết thủ tục hành chính

**Comment by binhth** [comment]
@tragiangdt bổ sung các thông tin của bugs như sau:
- domain test
- các account đăng nhập để tái hiện lỗi
- URL tới trang có bugs + ảnh chụp màn hình.
- mô tả bugs (đặc thù)

**Comment by tragiangdt** [comment]
1. domain test: qa.opencps.vn (luôn test trên qa)
2. các account đăng nhập để tái hiện lỗi: tài khoản quản trị admin.qa@fds.vn/fds@2016
3. URL tới trang có bugs + ảnh chụp màn hình
   LINK: http://qa.opencps.vn/group/guest/thu-tuc-hanh-chinh2?p_p_id=9_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_9_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fservicemgt%2Fadmin%2Fedit_service-ux.jsp&_9_WAR_opencpsportlet_serviceinfoId=502&_9_WAR_opencpsportlet_backURL=%2Fgroup%2Fguest%2Fthu-tuc-hanh-chinh2
   ![tthc_loi](https://cloud.githubusercontent.com/assets/17695836/17687311/1f376456-639e-11e6-8e6b-2ec72a9ab0a4.png)
4. Lỗi: quản trị sửa thông tin chi tiết thủ tục hành chính, chọn ghi lại, khi mở lại tthc này không thấy cập nhật thông tin vừa thay đổi

**Comment by binhth** [comment]
@tragiangdt 
giải pháp: sửa dữ liệu hiển thị của trường văn bản pháp quy

**Comment by tragiangdt** [comment]
Đã test ok trên opencps-dev
