### ISSUE TITLE
Tách cơ quan thực hiện và cấp quản lý thủ tục hành chính

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#915]
Hiện tại cơ quan thực hiện và cấp quản lý tthc đang dùng chung bộ dữ liệu danh mục

**Comment by tragiangdt** [comment]
Đã tách được cấp quản lý và cơ quan thực hiện
Còn một số chỗ chưa lọc theo Cơ quan thực hiện:
1. Màn hình chuẩn bị hồ sơ 
http://qa.opencps.vn/group/guest/quan-ly-ho-so?p_p_id=13_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_13_WAR_opencpsportlet_isListServiceConfig=true&_13_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fdossiermgt%2Ffrontoffice%2Ffrontofficeservicelist.jsp&_13_WAR_opencpsportlet_backURL=%2Fgroup%2Fguest&_13_WAR_opencpsportlet_backURLFromList=%2Fgroup%2Fguest

**Comment by dunglt91** [comment]
@tragiangdt done!

**Comment by khoahp** [comment]
@tragiangdt phần này done rồi anh close lại nhé

**Comment by tragiangdt** [comment]
test done treen qa
