### ISSUE TITLE
Trạng thái hồ sơ trên danh sách Quản lý hồ sơ hiển thị tên chưa đúng như dữ liệu danh mục (VD: Trạng thái Chờ xử lý, trong danh mục là Chờ bổ sung)

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#919]
Trạng thái hồ sơ trên danh sách Quản lý hồ sơ hiển thị tên chưa đúng như dữ liệu danh mục (VD: Trạng thái Chờ xử lý, trong danh mục là Chờ bổ sung)
1. Vào tài khoản doanhnghiep.cps@gmail.com
2. vào menu danh sách hồ sơ http://qa.opencps.vn/group/guest/quan-ly-ho-so
![2016-08-17_142328](https://cloud.githubusercontent.com/assets/17695836/17727889/5f039c2e-6486-11e6-9eae-8d2140f0925f.png)

**Comment by tragiangdt** [comment]
@huymq

**Comment by khoahp** [comment]
@trungnt-ksnb ông hot-fix lỗi này nhé

**Comment by khoahp** [comment]
@tragiangdt test nhe

**Comment by tragiangdt** [comment]
test done trên qa
