### ISSUE TITLE
Tiện ích sinh mã tiếp nhận thêm được ký tự và ký tự đặc biệt; số tiếp nhận tăng theo thứ tự, chứ không hiển thị random (hiện tại chỉ cấu hình hiển thị số)

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#920]
Tiện ích sinh mã tiếp nhận thêm được ký tự và ký tự đặc biệt; số tiếp nhận tăng theo thứ tự, chứ không hiển thị random (hiện tại chỉ cấu hình số tiếp nhận hiển thị số)
@huymq

**Comment by huymq** [comment]
@khoahp hỗ trợ nhé

**Comment by khoahp** [comment]
@tragiangdt phần này là như nào em, có ký tự đặc biệt thì tự tăng là ntn?

**Comment by khoahp** [comment]
@huymq e đặt lại milestone cho cái này nhé

**Comment by tragiangdt** [comment]
@khoahp 
Là có ký hiệu "/" hoặc "-" hoặc text "ABCXYZ" hoặc "[ ]" hoặc "{}"...
VD: 10001/2016-OT

**Comment by tragiangdt** [comment]
Anh @khoahp: sau khi sửa xong thì anh hướng dẫn em cách cấu hình thế nào anh nhé

**Comment by khoahp** [comment]
@tragiangdt em test lại nhé, anh đã cập nhật lên QA

**Comment by tragiangdt** [comment]
test done
