### ISSUE TITLE
Trên danh sách Quản lý hồ sơ, thêm trường thông tin số hồ sơ (TH cán bộ chưa tiếp nhận hồ sơ, chưa sinh số tiếp nhận thì NLTT ko phân biệt được các hồ sơ với nhau)

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#921]
Trên danh sách Quản lý hồ sơ, thêm trường thông tin số hồ sơ (TH cán bộ chưa tiếp nhận hồ sơ, chưa sinh số tiếp nhận thì NLTT ko phân biệt được các hồ sơ với nhau)
@huymq

**Comment by huymq** [comment]
@khoahp core team hỗ trợ anh nhé

**Comment by khoahp** [comment]
@huymq okie em,

@tanhtanhvn @trungnt-ksnb 
Trong thành phần hồ sơ hiện tại chưa có trường dữ liệu cho số hồ sơ, anh Tuấn Anh xem có bổ xung hoặc sử dụng thông qua trường nào được không ạ?

**Comment by huymq** [comment]
@tanhtanhvn @khoahp Số hồ sơ hiện tại đang dùng luôn là dossierId. Và có cấu hình để hiển thị số hồ sơ trong danh sách hồ sơ. Nếu PA này không vấn đề gì thì hướng dẫn @tragiangdt là done

**Comment by khoahp** [comment]
@huymq phần này cho thêm phương án format hiển thị cho nó đẹp, dạng format ví dụ là số tiếp nhận là 12 số, thêm số 0 ở đầu sử dụng hàm của java String.format("%12d%",number);

**Comment by khoahp** [comment]
@tragiangdt Test laij nhe

**Comment by tragiangdt** [comment]
test done: Đã có số hồ sơ trên qa
