### ISSUE TITLE
Chưa đính kèm được nhiều giấy tờ kết quả ở loại thành phần giấy tờ nhiều kết quả

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#922]
Chưa đính kèm được nhiều giấy tờ kết quả ở loại thành phần giấy tờ nhiều kết quả
@huymq

**Comment by dunglt91** [comment]
@tragiangdt cho to cai man hinh va links

**Comment by tragiangdt** [comment]
link: http://qa.opencps.vn/group/guest/xu-ly-ho-so
![2016-08-19_105522](https://cloud.githubusercontent.com/assets/17695836/17798472/8ef03020-65fb-11e6-86aa-96edbae69df3.png)

**Comment by tragiangdt** [comment]
1. Cấu hình thành phần hồ sơ có loại: Nhiều giấy tờ kết quả
2. trên màn hình xử lý, không hiển thị thành phần này

**Comment by khoahp** [comment]
@huymq phần này chuyển lại đội core nhé

**Comment by tragiangdt** [comment]
Đã test ok trên opencps-dev

**Comment by tragiangdt** [comment]
@khoahp 
Trên qa chưa được. TP loại nhiều giấy tờ kết quả không hiển thị trên danh sách xử lý.
http://qa.opencps.vn/group/guest/xu-ly-ho-so?p_p_id=16_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_16_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fprocessmgt%2Fprocessorder%2Fprocess_order_detail.jsp&_16_WAR_opencpsportlet_processOrderId=11701&_16_WAR_opencpsportlet_backURL=%2Fgroup%2Fguest&_16_WAR_opencpsportlet_isEditDossier=true#_16_WAR_opencpsportlet_tab=_16_WAR_opencpsportlet_process

**Comment by khoahp** [comment]
@trungnt-ksnb xem nhé

**Comment by khoahp** [comment]
@trungnt-ksnb ông xem phần này nhé, hot-fix

**Comment by trungnt-ksnb** [comment]
@khoahp @huymq Phần này @thanhld2901  đã sửa, nhưng còn 1 số chỗ chưa chuẩn. Đã chỉ lại cho bạn ấy để fix luôn rồi

**Comment by tragiangdt** [comment]
Trên qa, phiếu xử lý đang mất thành phần kết quả
![2016-08-31_100903](https://cloud.githubusercontent.com/assets/17695836/18114648/fa512520-6f62-11e6-8d95-332c9bdf520e.png)

**Comment by khoahp** [comment]
@tragiangdt em test lại phần này nhé

**Comment by tragiangdt** [comment]
test done trên qa

**Comment by tragiangdt** [comment]
@khoahp Vẫn còn lỗi chưa xóa được file tải lên

**Comment by khoahp** [comment]
Lỗi xóa file tải lên em test lại nhé

**Comment by khoahp** [comment]
@tragiangdt lỗi xóa file tải lên em test lại nhé

**Comment by tragiangdt** [comment]
@khoahp  Đã xóa được file tải lên với loại thành phần nhiều giấy tờ kết quả. Nhưng phất sinh lỗi, xóa file của thành phần giấy tờ kết quả hoặc giấy nộp vào, khi xóa file thì số phiên bản cũng giảm theo.

**Comment by khoahp** [comment]
@trungnt-ksnb xử lý lỗi phát sinh nhé

**Comment by huymq** [comment]
@tragiangdt 

> Đã xóa được file tải lên với loại thành phần nhiều giấy tờ kết quả. Nhưng phất sinh lỗi, xóa file của thành phần giấy tờ kết quả hoặc giấy nộp vào, khi xóa file thì số phiên bản cũng giảm theo.

Check lại với anh @tanhtanhvn và @hainthl chỗ này nhé. Vì ở phía màn hình nộp hồ sơ của NLTT có nhiều ý kiến trái chiều về số phiên bản này.

**Comment by trungnt-ksnb** [comment]
@tragiangdt @khoahp done

**Comment by tragiangdt** [comment]
Đã đính kèm giấy tờ loại Nhiều giấy tờ kết quả
