### ISSUE TITLE
[Feature]Thêm chức năng lọc theo lĩnh vực hoạt động của doanh nghiệp trên màn hình quản lý tài khoản công dân tổ chức

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#925]
Thêm chức năng lọc theo lĩnh vực hoạt động của doanh nghiệp trên màn hình quản lý tài khoản công dân tổ chức

**Comment by tragiangdt** [comment]
@huymq

**Comment by dunglt91** [comment]
@huymq cái này để em làm luôn nhé

**Comment by khoahp** [comment]
@huymq phần này chưa thấy gán milestone, fix xong chư thấy có test confirm nhé

**Comment by huymq** [comment]
@khoahp bug này mọi người vẫn đang làm :)

**Comment by khoahp** [comment]
https://github.com/d006141/opencps/commit/07ab7001286cf735625afd2ec9e8cb6b3d1a5440 anh thấy có commit này báo issue fix, tưởng okie rồi

**Comment by tragiangdt** [comment]
@dunglt91 Trên qa chưa thấy có chức năng này

**Comment by dunglt91** [comment]
@huymq  anh kiểm tra xem bên qa merge code chưa

**Comment by tragiangdt** [comment]
@dunglt91 link test: http://qa.opencps.vn/group/guest/quan-ly-cong-dan-to-chuc
Còn lỗi:
Khi lọc theo lĩnh vực khai khoáng: kết quả hiển thị 2 Doanh nghiệp
![2016-08-31_095442](https://cloud.githubusercontent.com/assets/17695836/18114402/1cea6490-6f61-11e6-8850-2af7022948db.png)

Khi lọc theo Lĩnh vực Khai khoáng + trạng thái Đăng ký thì hiển thị 3 kq cùng 1 doanh nghiệp:
![2016-08-31_095704](https://cloud.githubusercontent.com/assets/17695836/18114435/4cef3990-6f61-11e6-8fcc-cebd89cfcd8e.png)

Khi lọc theo Lĩnh vực Khai khoáng + trạng thái Hoàn thành thì không hiển thị kq nào:
![2016-08-31_095803](https://cloud.githubusercontent.com/assets/17695836/18114470/82a2a860-6f61-11e6-9efa-faffcff48ffe.png)

**Comment by tragiangdt** [comment]
test ok trên opencps-dev

**Comment by khoahp** [comment]
@tragiangdt done rồi thì close lại nhé

**Comment by tragiangdt** [comment]
test done trên qa
