### ISSUE TITLE
Trên màn hình chuẩn bị hồ sơ của doanh nghiệp thêm nút Gửi hồ sơ, Quay lại màn hình danh sách

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#926]
Trên màn hình chuẩn bị hồ sơ của doanh nghiệp thêm nút Gửi hồ sơ, Quay lại màn hình danh sách
1. vào http://qa.opencps.vn/group/guest/quan-ly-ho-so?p_p_id=13_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_13_WAR_opencpsportlet_isEditDossier=true&_13_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fdossiermgt%2Ffrontoffice%2Fedit_dossier.jsp&_13_WAR_opencpsportlet_backURL=%2Fgroup%2Fguest%2Fquan-ly-ho-so%3Fp_p_id%3D13_WAR_opencpsportlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-1%26p_p_col_count%3D1%26_13_WAR_opencpsportlet_mvcPath%3D%252Fhtml%252Fportlets%252Fdossiermgt%252Ffrontoffice%252Ffrontofficedossierlist.jsp%26_13_WAR_opencpsportlet_tabs1%3Ddossier%26_13_WAR_opencpsportlet_serviceDomainId%3D%26_13_WAR_opencpsportlet_dossierStatus%3Dwaiting&_13_WAR_opencpsportlet_dossierId=13301#_13_WAR_opencpsportlet_tab=_13_WAR_opencpsportlet_dossier_part
2. vào tài khoản doanhnghiep.cps@gmail.com, 
![2016-08-17_144225](https://cloud.githubusercontent.com/assets/17695836/17728399/42d0b32c-6489-11e6-80e4-d09f45a26cce.png)

**Comment by tragiangdt** [comment]
@huymq

**Comment by khoahp** [comment]
@huymq phần này anh chuyển lại cho đội core nhé

**Comment by huymq** [comment]
@khoahp cái này coreteam vẫn làm chứ

**Comment by huymq** [comment]
Phần này @dunglt91 đã làm, nhưng có thể chưa chuẩn theo UI. Phần này làm nhanh được thì anh @trungnt-ksnb support luôn nhé

**Comment by tragiangdt** [comment]
1. Thiếu nút Quay lại danh sách
2. Hiện tại các nút này chưa được chỉnh css:
   ![2016-08-31_103342](https://cloud.githubusercontent.com/assets/17695836/18115062/6c767990-6f66-11e6-8b58-70c0e765588e.png)

**Comment by khoahp** [comment]
@tragiangdt test laij tren QA

**Comment by tragiangdt** [comment]
1. Đã có nút QUay lại danh sách nhưng css của các nút chưa được chỉnh sửa anh @khoahp ạ
2. TH không đính kèm thành phần hồ sơ nào, click nút gửi, hệ thông thông báo "Thành phần hồ sơ yêu cầu bắt buộc phải nhập. " và quay lại màn hình danh sách (Yêu cầu: hệ thống thông báo "Thành phần hồ sơ yêu cầu bắt buộc phải nhập. " và giữ nguyên màn hình chuẩn bị hồ sơ.
   ![2016-09-01_093244](https://cloud.githubusercontent.com/assets/17695836/18153479/de0b6338-7027-11e6-846a-53b5b72f5c1d.png)

**Comment by khoahp** [comment]
@tragiangdt done rồi anh close vào nhé

**Comment by tragiangdt** [comment]
test done trên qa
