### ISSUE TITLE
"Trên danh sách quản lý hồ sơ, doanh nghiệp gửi hồ sơ, hệ thống báo thành công,  lỗi: hệ thống đang hiển thị danh sách hs có trạng thái Tạo mới, không hiển thị tất cả"

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#927]
"Trên danh sách quản lý hồ sơ, doanh nghiệp gửi hồ sơ, hệ thống báo thành công, 
lỗi: hệ thống đang hiển thị danh sách hs có trạng thái Tạo mới, không hiển thị tất cả"
![2016-08-17_144812](https://cloud.githubusercontent.com/assets/17695836/17728487/a84d42d8-6489-11e6-8dca-1d5e9ef74409.png)

**Comment by tragiangdt** [comment]
@huymq

**Comment by khoahp** [comment]
@huymq anh chuyển lại đội core lỗi này nhé

**Comment by trungnt-ksnb** [comment]
@huymq hỏi lại @dunglt91 xem đã xử lý chưa vì hôm qua đã hướng dẫn cho cách xử lý rồi

**Comment by tragiangdt** [comment]
test done trên qa

**Comment by tragiangdt** [comment]
Trên qa lại gặp lỗi này a

**Comment by dunglt91** [comment]
@huymq phần này em chưa thấy được assigned, hôm nay em sửa và PR lên kho fdsservice rồi anh nhé, anh assign bug này cho em.

**Comment by dunglt91** [comment]
@tragiangdt done. Tớ đẩy lên con dev rồi nhé

**Comment by tragiangdt** [comment]
@dunglt91  T vừa test trên con server dev, vẫn lỗi

**Comment by dunglt91** [comment]
@tragiangdt giao diện default ok  rồi cậu nhé.

**Comment by tragiangdt** [comment]
Giao diện default thì ok
Giao diện templates-to-display 20_80 thì gặp lỗi này
@binhth

**Comment by dunglt91** [comment]
@tragiangdt sửa cả 20-80 rồi nhé, cậu test trên Dev trước nhé

**Comment by tragiangdt** [comment]
test done trên server dev

**Comment by tragiangdt** [comment]
test done trên qa
