### ISSUE TITLE
"Cán bộ thực hiện Yêu cầu bổ sung, trên màn hình xác nhận, CB click Ghi lại Lỗi: hệ thông ko quay lại màn hình danh sách, mà vẫn giữ nguyên màn hình xem chi tiết hồ sơ"

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#928]
1. Vào http://qa.opencps.vn/group/guest/xu-ly-ho-so
2. Vào tài khoản cán bộ xử lý
3. Vào chi tiết 1 hồ sơ
   "Cán bộ thực hiện Yêu cầu bổ sung, trên màn hình xác nhận, CB click Ghi lại
   Lỗi: hệ thông ko quay lại màn hình danh sách, mà vẫn giữ nguyên màn hình xem chi tiết hồ sơ"

**Comment by tragiangdt** [comment]
@huymq

**Comment by tragiangdt** [comment]
@dunglt91 
Hình ảnh:
![screenshot from 2016-08-19 09-43-50](https://cloud.githubusercontent.com/assets/17695836/17797604/55742ab0-65f4-11e6-956b-a63260508121.png)

**Comment by khoahp** [comment]
@huymq anh chuyển lại bên core lỗi này nhé

**Comment by trungnt-ksnb** [comment]
@tragiangdt Nhờ  Giang tái hiện lại lỗi này giúp core team

**Comment by tragiangdt** [comment]
Nay em lại gặp lại tình huống này trên qa
1. Đăng nhập tài khoản vanthu1.cps@gmail.com
2. Chọn 1 hồ sơ trên đầu danh sách, click Thao tác
3. Vào tab Xử lý (không xem nội dung file đính kèm gì cả)
4. chọn Hướng dẫn doanh nghiệp bổ sung hồ sơ, sau đó click Ghi lại
5. Xảy ra lỗi luôn, 
![2016-08-31_113917](https://cloud.githubusercontent.com/assets/17695836/18116160/97c40be0-6f6f-11e6-8034-e0a34a71b178.png)

**Comment by khoahp** [comment]
@tragiangdt em kiểm tra lại lỗi này xem, anh test trên 2 hồ sơ phía công dân lúc 13h44' và 13h49' đều không gặp tình trạng như vậy.

Hành động: Văn thư vào xử lý -> Click tiếp nhận -> Chọn hướng dẫn bổ xung hồ sơ 
Kết quả: Popup xử lý tắt -> Quay ra màn hình danh sách hồ sơ

**Comment by tragiangdt** [comment]
Không phải lúc nào cũng xuất hiện lỗi này anh ạ. :s

**Comment by khoahp** [comment]
cho phần theo dõi

**Comment by khoahp** [comment]
đóng lại issue này, khi nào xuất hiện sẽ tạo issue mới
