### ISSUE TITLE
Trên màn hình xử lý hồ sơ của cán bộ, thông tin Thao tác thực hiện đang hiển thị sai

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#929]
Trên màn hình xử lý hồ sơ của cán bộ, thông tin Thao tác thực hiện đang hiển thị sai
1. Vào link http://qa.opencps.vn/group/guest/xu-ly-ho-so?p_p_id=16_WAR_opencpsportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_16_WAR_opencpsportlet_mvcPath=%2Fhtml%2Fportlets%2Fprocessmgt%2Fprocessorder%2Fprocess_order_detail.jsp&_16_WAR_opencpsportlet_processOrderId=11107&_16_WAR_opencpsportlet_backURL=%2Fgroup%2Fguest%2Fxu-ly-ho-so&_16_WAR_opencpsportlet_isEditDossier=true#_16_WAR_opencpsportlet_tab=_16_WAR_opencpsportlet_process
2. Vào tài khoản cán bộ
3. Trên danh sahcs hồ sơ chờ xử lý, vào xử lý 1 hồ sơ
4. Trên tab Xử lý
![2016-08-17_145404](https://cloud.githubusercontent.com/assets/17695836/17728647/819a8aaa-648a-11e6-84a9-3808f8d1f39e.png)

**Comment by tragiangdt** [comment]
@huymq

**Comment by khoahp** [comment]
@tragiangdt  Phần này bên core chịu trách nhiệm nhé

**Comment by trungnt-ksnb** [comment]
@tragiangdt  Làm rõ giúp core team là sai ngữ cảnh, hay sai label

**Comment by tragiangdt** [comment]
@trungnt-ksnb 
Trường Thao tác thực hiện đang hiển thị tên bước xử lý (phải hiển thị tên thao tác)

**Comment by trungnt-ksnb** [comment]
@tragiangdt done nhe

**Comment by tragiangdt** [comment]
test done trên qa
