### ISSUE TITLE
[Feature]Trên danh sách quản lý tài khoản công dân tổ chức có chức năng xuất file excel dữ liệu

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#930]
Trên danh sách quản lý tài khoản công dân tổ chức có chức năng xuất file excel dữ liệu

**Comment by khoahp** [comment]
@tragiangdt 
- Phần này có gấp không em?
- Thông tin biểu mẫu xuất ra là gì nhỉ?

**Comment by tragiangdt** [comment]
@khoahp 
Phần này chưa gấp lắm anh,
Thông tin biểu mẫu xuất ra là tất cả các thông tin mà doanh nghiệp/công dân đăng ký tài khoản ạ.
