### ISSUE TITLE
Cấu hình Thao tác có chọn kích hoạt tự động vẫn hiển thị trên màn hình xử lý

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#931]
1. vào tài khoản quản trị, cấu hình quy trình
2. Vào cập nhật thao tác
3. Trên màn hình cập nhật Thao tác có chọn kích hoạt tự động nhưng trên phiếu xử lý vẫn hiển thị thao tác này trên màn hình xử lý

**Comment by tragiangdt** [comment]
@huymq CNCN

**Comment by khoahp** [comment]
phần này bên core sửa @tragiangdt nhé

**Comment by tragiangdt** [comment]
@khoahp 
Lỗi này anh ưu tiên sửa nhé, lỗi này tồn tại lâu r anh a

**Comment by khoahp** [comment]
@trungnt-ksnb phần này ông kiểm tra điều kiện nếu là kích hoạt tự động không cho hiện trên phiếu xử lý nhé

**Comment by tragiangdt** [comment]
test done tren qa

**Comment by tragiangdt** [comment]
@khoahp @huymq Lỗi này lại lặp lại a. Lỗi này là hot_fix các anh sửa lại gấp a

**Comment by khoahp** [comment]
@tragiangdt lỗi này vẫn còn trên QA à

**Comment by tragiangdt** [comment]
@khoahp 
Trên qa vẫn còn lỗi này anh ạ

**Comment by khoahp** [comment]
@Hongnt31 lỗi này không test à em?

**Comment by Hongnt31** [comment]
@khoahp  cái này tối qua e không rõ nên đợi hỏi c Giang, bây h e hỏi rùi test ạ

**Comment by Hongnt31** [comment]
@khoahp vẫn còn lỗi này. Hiện tại cấu hình Thao tác có chọn kích hoạt tự động nhưng trên phiếu xử lý vẫn hiển thị thao tác này trên màn hình xử lý
![image](https://cloud.githubusercontent.com/assets/20554327/20175173/0dc3e0e0-a774-11e6-9eca-1f60ea0f235e.png)

**Comment by khoahp** [comment]
@Hongnt31 em test lại nhé, anh đã cập nhật

**Comment by Hongnt31** [comment]
@khoahp  Test done
