### ISSUE TITLE
Không thể build được source code từ version 1.5 trở đi vì thiếu class

### ISSUE THREAD

**Issue by nampq309** [VietOpenCPS/opencps#934]
Hi all,

Mình mới biết đến OpenCPS và cũng đang vọc vạch tự build từ source code của OpenCPS trên Github on tag 1.5. Nhưng mình đang bị stuck ở bước không thể đóng gói/compile được source code vì thiếu class.
Ví dụ class org.opencps.dossiermgt.service.base.DossierServiceBaseImpl này đang không tồn tại trên tag 1.5, ngoài ra cả package org.opencps.dossiermgt.service.base.\* cũng không có trên tag 1.5 luôn (Hihi). Và nguyên nhân mình tìm hiểu được là do class đó đang bị đưa vào .gitignore file :).
Mọi người giúp mình giải quyết issue này với vì mình đang hiểu là đã release rồi thì phải đẩy hết source code đầy đủ lên chứ nhỉ :). 
Giúp mình giải đáp thắc mắc này với nhé!

Thanks & best regards!

**Comment by khoahp** [comment]
@nampq309 

Chào anh/bạn,

Bạn đã tiến hành build lại service cho các gói đó chưa? Đó là các class tự sinh khi build service trong OpenCPS nên chúng tôi không tiến hành đẩy các file đó lên.

Chúc bạn thành công.

**Comment by nampq309** [comment]
@khoahp 

Chào bạn,

Mình đã build theo guide trong page này
https://github.com/VietOpenCPS/deploy/wiki/Quy-tr%C3%ACnh-tri%E1%BB%83n-khai-OpenCPS-t%E1%BB%AB-source-code

và đã chạy các câu lệnh build service như bên dưới rồi

` \cp -rf /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/accountmgt/dao/service.xml /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/
 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service

 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service

 \cp -rf /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/datamgt/dao/service.xml /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/
 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service

 \cp -rf /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/processmgt/dao/service.xml /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/
 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service

 \cp -rf /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/paymentmgt/dao/service.xml /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/
 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service

 \cp -rf /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/dossiermgt/dao/service.xml /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/
 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service

 \cp -rf /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/servicemgt/dao/service.xml /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/
 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service

 \cp -rf /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/usermgt/dao/service.xml /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/
 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service`

Nhưng đến bước này

`ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml compile`

thì bị lỗi đó. Không biết mình còn thiếu step nào không.
Thanks bạn mình sẽ thử làm lại từ đầu lần nữa rồi sẽ inform cho bạn kết quả.

Best regards.

**Comment by nampq309** [comment]
Hi @khoahp ,

Bạn cho mình hỏi thêm câu nữa nhé, khi mình quay trở lại version 1.3 (tức tag 1.3) thì build được ok nhưng khi config db (ở lần startup đầu tiên của portal) xong thì mình lại bị lỗi các tables trong db bị miss fields so với class model.

Ví dụ: model DossierImpl tương ứng với table "opencps_dossier" đang ko match 2 fields: oid và displayStatus (model thì có còn table trong db thì ko).

Đây là exception:
`com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not load an entity: [org.opencps.dossiermgt.model.impl.DossierImpl`
...

`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'dossierimp0_.oid' in 'field list'`

mình đã run script để import db như trong bước này hướng dẫn:

`mysql -uroot -p opencps < /opt/opencps/db_script/opencps_portal.sql`

nhưng hình như file script này được update cách đây khá lâu (2 months ago) trên cả tag 1.3 và 1.5 đều giống nhau. 
Bạn cho mình hỏi mình phải lấy script mới nhất nếu cho version 1.5 thì ở đâu nhé (Vì mình nghĩ version mới chắc model đã thay đổi nhiều rồi mà chưa thấy update script).

**Comment by nampq309** [comment]
Chào @khoahp,

Mình đã thử lại với version 1.5 thì mình thấy guide thiếu 1 line build service cho package org.opencps.api bằng command như thế này:

`\cp -rf /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/api/dao/service.xml /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/
 ant -buildfile /opt/opencps/portlets/opencps-portlet/build.xml build-service`

Sau khi build hết các service xong, đến phần compile mình có gặp lỗi này:

`Buildfile: /opt/opencps/portlets/opencps-portlet/build.xml

compile:
    [javac] Warning: org/opencps/api/service/base/ApiServiceLocalServiceBaseImpl.java modified in the future.
    [javac] Compiling 1 source file to /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/classes
    [javac] ----------
    [javac] 1. ERROR in /opt/opencps/portlets/opencps-portlet/docroot/WEB-INF/src/org/opencps/api/service/base/ApiServiceLocalServiceBaseImpl.java (at line 239)
    [javac]     public ApiService getApiService(long apiLogId) {
    [javac]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [javac] The method getApiService(long) of type ApiServiceLocalServiceBaseImpl must override or implement a supertype method
    [javac] ----------
    [javac] 1 problem (1 error)

BUILD FAILED
/opt/opencps/build-common.xml:3071: The following error occurred while executing this line:
: The following error occurred while executing this line:
/opt/opencps/build-common.xml:648: The following error occurred while executing this line:
/opt/opencps/build-common.xml:1083: The following error occurred while executing this line:
/opt/opencps/build-common.xml:956: Compile failed; see the compiler error output for details.
`

Mình không tìm thấy supertype method của nó ở đâu nên đành remove @Override đi để compile được. Không biết có ảnh hưởng gì không :)

Ok, thanks @khoahp đã giúp mình hiểu được problem của mình và giờ mình đã build được bản 1.5 rồi.

Chúc bạn cuối tuần vui vẻ :)

**Comment by khoahp** [comment]
@nampq309 chào anh,

Mọi người đang rà soát các issue để close lại, vấn đề anh hỏi vẫn chưa xử lý được nhưng em xin phép đóng lại và chuyển qua room support.

Anh flow trên telegram theo link này nhé, https://telegram.me/joinchat/CzH51Qfy8RcuCuVYvngZ-A
