### ISSUE TITLE
Xin latest script db của version 1.5

### ISSUE THREAD

**Issue by nampq309** [VietOpenCPS/opencps#935]
Hi all,

Hiện tại mình thấy script import db đang bị out of date so với version 1.5 nên mọi người có thể cho mình xin script mới nhất được không? Thanks!
p/s: path to script "portlets/opencps-portlet/docroot/WEB-INF/sql/opencps_portal.sql"
Tiện thể cho mình xin folder "data" mới nhất nhé.
Cảm ơn nhiều!

**Comment by tanhtanhvn** [comment]
@tuanta: Xem quy trình cho các thread dạng support thế này thì nên đưa vào chỗ nào nhỉ. Đưa vào issue thế này thì có vẻ không ổn cho vấn đề quản lý. Hay là lập một forum để support ban đầu nhể?

**Comment by tuanta** [comment]
Việc cần gửi email (lên mailing list), chat (IRC, Telegram) là được.
Tham khảo: http://lists.opencps.vn/mailman/listinfo/opencps

Đây không phải là issue nên tôi sẽ đóng lại.
