### ISSUE TITLE
Thêm trường nhập địa chỉ nộp hồ sơ trực tuyến (dịch vụ cấp 3, 4) trên màn hình cấu hình dịch vụ công

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#939]
1. Thêm trường nhập địa chỉ nộp hồ sơ trực tuyến (dịch vụ cấp 3, 4) trên màn hình cấu hình dịc vụ công
2. serviceUrl: Địa chỉ nộp hồ sơ trực tuyến (dịch vụ cấp 3, 4) ở site bên ngoài. Địa chỉ này phải để trắng trong trường hợp cờ servicePortal được đánh dấu. 
   Link: http://qa.opencps.vn/group/guest/quan-ly-dich-vu-cong-muc-3
   Màn hình:
   ![cau hinh dvc](https://cloud.githubusercontent.com/assets/17695836/17797844/6e9052ce-65f6-11e6-828b-b23a351c0555.png)
   @huymq

**Comment by khoahp** [comment]
@huymq

**Comment by dunglt91** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
test ok trên opencps-dev

**Comment by khoahp** [comment]
@tragiangdt done rồi anh close lại nhé

**Comment by tragiangdt** [comment]
test done trên qa
