### ISSUE TITLE
Kiểm tra thông tin serviceUrl khi click nút Nộp hồ sơ trực tuyến

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#940]
1. link: http://qa.opencps.vn/tiep-nhan-ho-so-qua-mang
2. Xem Hướng dẫn 1 DVC
3. click nút Nộp hồ sơ trực tuyến
   Khi này phải kiểm tra thông tin serviceUrl trong bảng service_config, nếu trắng thì nộp hồ sơ tại cổng, nếu có link thì lấy luôn link này.
   màn hình:
   ![2016-08-19_104135](https://cloud.githubusercontent.com/assets/17695836/17798214/8acb6cb4-65f9-11e6-8e50-0edc7738b668.png)
   @huymq

**Comment by tragiangdt** [comment]
test done trên opencps-dev
@dunglt91 Khi cấu hình dvc, nếu check cổng tiếp nhận thì trường serviceUrl ko cho nhập

**Comment by dunglt91** [comment]
@tragiangdt theo thiết kế thì khi tick vào cổng tiếp nhận nghĩa là thao tác ngay trên công của mình, vì thế không được nhập links bên ngoài (tự sinh links) nên sẽ validate không cho nhập links từ bên ngoài vào.

**Comment by dunglt91** [comment]
@tragiangdt

**Comment by tragiangdt** [comment]
@dunglt91 Chưa việt hóa TH báo lỗi: org.opencps.dossiermgt.ServiceUrlHasExistedException 
![2016-09-22_144434](https://cloud.githubusercontent.com/assets/17695836/18740292/3578b07e-80d3-11e6-851c-0456cbf31ae3.png)

**Comment by dunglt91** [comment]
@tragiangdt đã việt hóa

**Comment by khoahp** [comment]
@huymq phần nào được e đánh label fixed vào cho TEST dễ xem nhé, nếu không pass thì lại gỡ nhãn fix.

**Comment by khoahp** [comment]
@Hongnt31 phần này chưa test à?

**Comment by Hongnt31** [comment]
@khoahp 
Hiện tại khi vào admin điền service URL và các tích cổng tiếp nhận thì lại nháy đỏ vào không có thông báo gì
![image](https://cloud.githubusercontent.com/assets/20554327/20172138/5da0b2f4-a766-11e6-88b2-c3d90d6cae54.png)

**Comment by Hongnt31** [comment]
@khoahp 
Hiện tại vào admin sửa service URL bằng số thì không hiển thị thông báo lỗi và chỉ nháy đỏ
![image](https://cloud.githubusercontent.com/assets/20554327/20172382/641a7f24-a767-11e6-8a3a-42b87e42c527.png)

**Comment by Hongnt31** [comment]
@khoahp 
Hiện tại kh iadmin điền thông tin vào service URL và Tích Cổng tiếp nhận nhấn đồng ý thì không xuất hiện thông báo 
KQMM: Yêu cầu việt hóa thông báo thành "Chọn Cổng tiếp nhận không được điền thông tin vào service URL" hoặc 
Khi click chọn Tiếp nhận một cửa mới hiển thị textbox điền service URL
![image](https://cloud.githubusercontent.com/assets/20554327/20384215/98baf42e-ace5-11e6-8587-26886ed287cd.png)

**Comment by khoahp** [comment]
@nhan0987 xử lý giúp anh nhé
