### ISSUE TITLE
Chỉ hiển thị những cơ quan thực hiện dvc được gán khi cấu hình DVC

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#941]
1. vào http://qa.opencps.vn/tiep-nhan-ho-so-qua-mang
2. Xem Hướng dẫn 1 dvc
3. trên màn hình hướng dẫn nộp hồ sơ trực tuyến
   Thông tin Lựa chọn cơ quan thực hiện thủ tục để xem hướng dẫn nộp hồ sơ: Chỉ hiển thị những cơ quan thực hiện dvc được gán khi cấu hình DVC
   Hình: 
   ![2016-08-19_104135](https://cloud.githubusercontent.com/assets/17695836/17798263/f6c2b7ec-65f9-11e6-8bb4-637514cdf2a6.png)
   @huymq

**Comment by khoahp** [comment]
@huymq nhé

**Comment by dunglt91** [comment]
@tragiangdt done!

**Comment by Hongnt31** [comment]
@dunglt91  Lỗi không hiển thị cơ quan được gán thực hiện DVC

**Comment by tragiangdt** [comment]
test ok trên opencps-dev

**Comment by khoahp** [comment]
@tragiangdt done rồi anh đóng lại nhé

**Comment by tragiangdt** [comment]
test done trên qa
