### ISSUE TITLE
Lỗi hiển thị danh sách dịch vụ công trên trang tiếp nhận hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#942]
1. vào http://qa.opencps.vn/tiep-nhan-ho-so-qua-mang
2. trên danh sách tiếp nhận hồ sơ qua mạng, chỉ hiển thị danh sách dịch vụ công (hiện tại đang hiển thị tất cả danh sách thủ tục hành chính)
   ![2016-08-19_104709](https://cloud.githubusercontent.com/assets/17695836/17798304/4eb37586-65fa-11e6-9dc4-1a3e971cb928.png)
   @huymq

**Comment by huymq** [comment]
@NVP191

**Comment by dunglt91** [comment]
@huymq cái này nằm trong hướng dẫn nộp hồ sơ qua mạng, đội core nhận rồi anh.

**Comment by khoahp** [comment]
@huymq xử lý nhẹ

**Comment by dunglt91** [comment]
@tanhtanhvn  done!

**Comment by dunglt91** [comment]
@tragiangdt done!

**Comment by tragiangdt** [comment]
test ok trên opencps-dev

**Comment by huymq** [comment]
@tragiangdt liên hệ với coreteam để xem lỗi đã fix trên hệ thống kiểm thử của OpenCPS chưa nhé. Nếu chưa được thì báo @dunglt91 để check lại.

**Comment by khoahp** [comment]
@tragiangdt done rồi anh đóng lại nhé

**Comment by tragiangdt** [comment]
Test done trên qa
