### ISSUE TITLE
Hồ sơ đang ở trạng thái Tạo mới không có nút Ghi lại

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#944]
1. vào http://qa.opencps.vn/group/guest/quan-ly-ho-so
2. Vào tài khoản doanh nghiệp doanhnghiep.cps@gmail.com
3. Vào hồ sơ có trạng thái Tạo mới
   trên màn hình chi tiết không có nút Ghi lại (không sửa được thông tin hồ sơ tại trạng thái Tạo mới)

**Comment by khoahp** [comment]
@tragiangdt done rồi, anh đóng issue này vào nhé

**Comment by tragiangdt** [comment]
test done
