### ISSUE TITLE
Không chuyển trạng thái phiếu thanh toán khi thực hiện thanh toán trực tuyến

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#947]
1. Doanh nghiệp vào http://qa.opencps.vn/group/guest/yeu-cau-thanh-toan
2. Thực hiện thanh toán trực tuyến
3. Nhập thông tin thanh toán trên hệ thống keypay: Visa: tài khoản: 4005550000000001  - Expiry Date: 05/17 - Security code:123
4. Hệ thống keypay báo thanh toán thành công, hệ thống quay về màn hình yêu cầu thanh toán.
   Lỗi: Phiếu thanh toán chưa chuyển sang trạng thái Hòan thành

**Comment by huymq** [comment]
@binhth mô tả công việc đã thực hiện và còn tồn lại nhé

**Comment by binhth** [comment]
@huymq : phần này do cấu hình portlet trên QA bị sai.
@tragiangdt : vào remove portlet yêu cầu thanh toán + kiểm tra lại phần cấu hình sinh returnURL ở portlet chuẩn bị hồ sơ

**Comment by huymq** [comment]
@tragiangdt check cấu hình lại nhé.
@binhth issue làm xong thì em comment hoặc báo @tragiangdt test lại để close đi

**Comment by khoahp** [comment]
@tragiangdt anh close lỗi này vào nhé

**Comment by tragiangdt** [comment]
test done
