### ISSUE TITLE
Địa chỉ NLTT trên màn hình thông tin hồ sơ không thay đổi khi NLTT thực hiện đã sửa đổi địa chỉ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#956]
1. Vào tài khoản NLTT (doanhnghiep.cps@gmail.com/congdan.cps@gmail.com)
2. Vào thông tin tài khoản http://qa.opencps.vn/group/guest/thong-tin-tai-khoan-cd-tc
3. Thay đổi địa doanh nghiệp (địa chỉ/ xã/huyện/tỉnh)
4. Lưu lại thành công
5. NLTT thực hiện nộp hồ sơ (vào quản lý hồ sơ)
6. Lỗi: Màn hình thông tin hồ sơ vẫn hiển thị địa chỉ cũ (trc khi sửa đổi) của NLTT

**Comment by khoahp** [comment]
@trungnt-ksnb xem lỗi này nhé

**Comment by trungnt-ksnb** [comment]
@khoahp done

**Comment by tragiangdt** [comment]
@trungnt-ksnb Địa chỉ chi tiết "Địa chỉ *" thì đã thay đổi nhưng địa chỉ Tỉnh/Thành phố + Huyện/Quận \* + Xã/Phường \*  chưa thay đổi

**Comment by huymq** [comment]
@dunglt91 check lại lỗi này nhé. Anh Trung đã sửa lỗi này rồi, check lại sao lại bị lật lại lỗi nhé

**Comment by dunglt91** [comment]
@tragiangdt cái này anh @trungnt-ksnb đã  khắc phục, tí nữa cậu thử vào qa kiểm tra lại..
@huymq Lỗi trước đây là lỗi không update lại thông tin khi thay đổi thông tin tài khoản công dân, tổ chức, còn nó đồng thời không cập nhật trong lúc tạo mới hồ sơ là phát sinh chứ không phải lật lại lỗi anh ạ.

**Comment by khoahp** [comment]
@tragiangdt em test lại lỗi này nhé

**Comment by tragiangdt** [comment]
@khoahp 
Trên qa vẫn còn lỗi: Địa chỉ chi tiết "Địa chỉ *" thì đã thay đổi nhưng địa chỉ Tỉnh/Thành phố + Huyện/Quận \* + Xã/Phường \* chưa thay đổi

**Comment by Hongnt31** [comment]
@khoahp @tragiangdt  Test done
![image](https://cloud.githubusercontent.com/assets/20554327/20132397/60b5d54a-a695-11e6-96b8-8414055878a5.png)
