### ISSUE TITLE
NLTT tải lên file, hệ thông không tắt popup và thông báo tải thành công

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#957]
1. Vào tài khoản NLTT: doanhnghiep.cps@gmail.com
2. Chuẩn bị nộp hồ sơ trực tuyến
3. Trên tab thành phần hồ sơ thực hiện tải lên file đính kèm,
4. Lỗi: hệ thống ko thông báo đã tải thành công, không tắt popup, phải load lại trang thì mới thấy đã tải thành công

**Comment by huymq** [comment]
Lỗi này được rồi mà nhỉ. @tragiangdt test lại nhé

**Comment by tragiangdt** [comment]
Test done
