### ISSUE TITLE
NLTT chưa nhận được loại giấy tờ nhiều kết quả

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#959]
1. Cấu hình trả về loại nhiều giấy tờ kết quả A
2. Thực hiện xử lý hồ sơ đến bước trả về giấy  A
3. Lỗi: NLTT không nhận được giấy A (loại nhiều giấy tờ kết quả) (trường synstatus=0 trong db)

**Comment by thanhld2901** [comment]
Lỗi này em chưa hiểu luồng để fix. Anh @khoahp xem giúp em với nhé.

**Comment by khoahp** [comment]
@tragiangdt do trùng vs #922 nên đóng lại nhé

**Comment by tragiangdt** [comment]
2 issue khác nhau anh ơi, một lỗi là ko tải được, một lỗi là NLTT ko nhận được loại nhiều giấy tờ kết quả

**Comment by tragiangdt** [comment]
@khoahp 
Đã hiển thị thành phần giấy tờ kết quả trên phiếu xử lý r, nhưng còn lỗi này nữa ạ.
Lỗi: NLTT chưa nhận được loại giấy tờ nhiều kết quả + thông báo yêu cầu xử lý (TH có yêu cầu bổ sung)
![2016-09-05_145722](https://cloud.githubusercontent.com/assets/17695836/18241003/1674b180-7379-11e6-90c0-e9301ab57774.png)
