### ISSUE TITLE
Mất chức năng thêm dịch vụ công trên qa

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#978]
1. Vào tk quản trị trên qa
2. Vào quản lý dịch vụ công cấp 3
3. Vào tab Dịch vụ công
4. Lỗi: Mất chức năng thêm dịch vụ công 
   ![2016-09-05_100326](https://cloud.githubusercontent.com/assets/17695836/18236530/389213de-7351-11e6-863c-5c7fbd0138d6.png)

**Comment by huymq** [comment]
@tragiangdt lỗi này okie rồi em nhé. @dunglt91 deploy bản mới cho @tragiangdt test

**Comment by tragiangdt** [comment]
Đã test ok trên opencps-dev

**Comment by tragiangdt** [comment]
@khoahp Lỗi này trên qa cũng xuất hiện ạ.

**Comment by khoahp** [comment]
@tragiangdt anh đóng lỗi này vào nhé

**Comment by tragiangdt** [comment]
Trên qa đã có nút thêm dịch vụ công
