### ISSUE TITLE
Hồ sơ chuyển trạng thái Hệ thống trên qa

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#980]
1. Vào tài khoản doanh nghiệp
2. Chuẩn bị nộp hồ sơ thủ tục có cấu hình sinh phiếu thanh toán ngay tại bước bắt đầu nhận hồ sơ.
3. Gửi hồ sơ
4. Lỗi: Hồ sơ chuyển trạng thái Hệ thống trên qa (Hồ sơ nào không cấu hình sinh phiếu thanh toán thì không bị chuyển sang trạng thái Hệ thống khi nộp hồ sơ)

**Comment by huymq** [comment]
Lỗi này do trong bảng opencps_payment_file đánh index của keypayGoodCode và keypayTransactionId là unique nên khi Backend addPaymentFile bị lỗi duplicate key.

Cái này chạy lại index là được, nhờ @tuhoanganh chạy lại index của các DB liên quan tới OpenCPS nhé:

`ALTER TABLE opencps_payment_file DROP INDEX IX_F67DC25;`
`ALTER TABLE opencps_payment_file DROP INDEX IX_F67DC25;`
`create index IX_F67DC25 on opencps_payment_file (keypayGoodCode);`
`create index IX_430EEC02 on opencps_payment_file (keypayTransactionId);`

**Comment by tuhoanganh** [comment]
Fixed:
- demo.opencps.vn 
- qa.opencps.vn

**Comment by khoahp** [comment]
@tragiangdt done rồi anh close vào nhé

**Comment by tragiangdt** [comment]
test done
