### ISSUE TITLE
Trạng thái tài khoản hiển thị số 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#981]
1. Đăng nhập tài khoản quản trị
2. Vào menu quản lý tài khoản công dân tổ chức
3. Vào tab Doanh nghiệp/công dân
4. vào xem chi tiết 1 doanh nghiệp/công dân

Lỗi: Trạng thái tài khoản hiển thị số, không hiển thị tên

**Comment by dunglt91** [comment]
@tragiangdt done rồi nhé.

**Comment by tragiangdt** [comment]
test done trên opencps-dev

**Comment by khoahp** [comment]
@tragiangdt done rồi anh close nhé
