### ISSUE TITLE
Sửa lại thứ tự hiển thị trong 2 trang Hồ sơ chờ xử lý và Hồ sơ mới được xử lý như sau: Hồ sơ chờ xử lý thứ tự hiển thị là mới ở dưới, cũ ở trên; Hồ sơ mới được xử lý thứ tự hiển thị ngược lại là mới ở trên, cũ ở dưới

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#983]
Sửa lại thứ tự hiển thị trong 2 trang Hồ sơ chờ xử lý và Hồ sơ mới được xử lý như sau: Hồ sơ chờ xử lý thứ tự hiển thị là mới ở dưới, cũ ở trên; 
Hồ sơ mới được xử lý thứ tự hiển thị ngược lại là mới ở trên, cũ ở dưới

**Comment by huymq** [comment]
@tragiangdt report bug mô tả cụ thể hơn nhé. 
Hiện trạng lỗi: ...
KQMM: ....

**Comment by tragiangdt** [comment]
- Hiện trạng: 
  +Danh sách hồ sơ chờ xử lý: sắp xếp hồ sơ đang theo thứ tự hồ sơ mới đến thì hiển thị đầu danh sách
- KQMM: 
  +Hồ sơ chờ xử lý thứ tự hiển thị là mới ở dưới, cũ ở trên;
  +Hồ sơ mới được xử lý thứ tự hiển thị ngược lại là mới ở trên, cũ ở dưới
  Hình:
  ![2016-09-06_144638](https://cloud.githubusercontent.com/assets/17695836/18265671/1dd64042-7441-11e6-8dee-457c3ed49faa.png)

**Comment by dunglt91** [comment]
@tragiangdt @huymq 
Tạo cấu hình portlet xử lý hồ sơ nhé giang.
- sắp xếp hồ sơ mới : hồ sơ mới lên đầu
- sắp xếp hồ sơ cũ : hồ sơ cũ lên đầu

có 2 selecttext thể hiện cho Tab : Hồ sơ mới xử lý, và Tab : Hồ sơ chờ xử lý nhé.

![buggg](https://cloud.githubusercontent.com/assets/17336343/18272108/2e0c9c62-7460-11e6-9597-936603da094f.png)

**Comment by tragiangdt** [comment]
test done trên opencps-dev

**Comment by huymq** [comment]
@dunglt91 làm lại phần này nhé. 
1. Hàm cũ searchProcessOrder có tham số orderByComparator là chuẩn rồi, em lại xóa đi thay bằng biến boolean là rất ngớ ngẩn (chưa kể có chỗ khác cũng đang sử dụng hàm này, em thay như vậy sẽ làm lỗi)
2. Phần cấu hình làm thay đổi như sau:
- Tab danh sách hồ sơ chờ xử lý: 1 combobox:  sắp sếp theo (orderByColumn) Ngày sửa (modifiedDate), 1 combobox hiển thị (orderByType) tăng dần(asc), giảm dần(desc)
- Tab danh sách hồ sơ mới được xử lý: Tương ứng.
- Với 2 giá trị có được khi cấu hình là orderByColumn=modifiedDate và orderByType, em có được biến orderByComparator = new ProcessOrderModifiedDateComparator(orderByType), từ đấy em truyền vào hàm searchProcessOrder

**Comment by khoahp** [comment]
@tragiangdt xong phần này chưa close phần này vào đi em

**Comment by tragiangdt** [comment]
test done
