### ISSUE TITLE
Trên ds quản lý hồ sơ, ds bước xử lý, trang thông tin hồ sơ bên cán bộ, trạng thái trên tab kết quả+lịch sử không hiển thị được tên trạng thái mới thêm từ danh mục

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#988]
1. Thêm 1 trạng thái hồ sơ mới (Trạng thái A) vào danh mục
2. Cấu hình bước xử lý B gán với trạng thái A
   Khi hồ sơ chuyển đến bước xử lý B,
   lỗi: Trên ds quản lý hồ sơ, ds bước xử lý, trang thông tin hồ sơ bên cán bộ, trạng thái trên tab kết quả +lịch sử không hiển thị được tên trạng thái mới thêm từ danh mục (đều hiển thị trạng thái Mới)
   ![2016-09-06_180905](https://cloud.githubusercontent.com/assets/17695836/18271722/d4aeafcc-745d-11e6-9dad-5e724a017530.png)
   ![2016-09-06_180716](https://cloud.githubusercontent.com/assets/17695836/18271723/d720a92c-745d-11e6-852d-4b74e82d85ef.png)

**Comment by tragiangdt** [comment]
@huymq

**Comment by tragiangdt** [comment]
@dunglt91 
Cả phần lịch sử xử lý của DN nữa nhá, đang hiện trạng thái Mới

**Comment by dunglt91** [comment]
@tragiangdt done nhe

**Comment by dunglt91** [comment]
@tragiangdt Test nhe, t lam xong tren dev roi nhe

**Comment by tragiangdt** [comment]
test done trên server dev

**Comment by khoahp** [comment]
@tragiangdt phần này @tragiangdt test xong rồi anh close vào nhé

**Comment by tragiangdt** [comment]
test done
