### ISSUE TITLE
"Trên danh sách lịch sử xử lý của NLTT không cho hiển thị ghi chú của cán bộ lên, chỉ hiển thị thông tin ghi chú tại bước cuối cùng khi chuyển sang trạng thái hồ sơ mới "

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#989]
"Trên danh sách lịch sử xử lý của NLTT không cho hiển thị ghi chú của cán bộ lên, chỉ hiển thị thông tin ghi chú tại bước cuối cùng khi chuyển sang trạng thái hồ sơ mới
1. Vào http://qa.opencps.vn/
2. Vào tk Doanh nghiệp Thực hiện nộp hồ sơ thủ tục "Xác nhận đăng ký thực hiện khuyến mại theo hình thức mang tính may rủi thực hiện trên địa bàn từ 2 tỉnh, thành phố trực thuộc Trung ương trở lên hoặc theo quy định tại Điều 17 NĐ số 37/2006/NĐ-CP " (trạng thái hồ sơ chuyển thành Tiếp nhận hồ sơ)
3. Vào cán bộ văn thư tiếp nhận hồ sơ mới nộp, nhập thông tin ghi chú (trạng thái hồ sơ chuyển đang xử lý
KQMM: Trên danh sách lịch sử xử lý của NLTT hiển thị thông tin ghi chú của Văn thư nhập

**Comment by huymq** [comment]
Phần thông tin lịch sử xử lý cho NLTT, có thêm cấu hình trong từng bước của quy trình, là bước nào cho phép hiển thị còn bước nào không cho phép hiển thị được không anh @tanhtanhvn . Hoặc anh có giải pháp nào hay hơn không ạ?

**Comment by khoahp** [comment]
@tragiangdt test lại phần này

**Comment by tragiangdt** [comment]
Hiện tại phần quá trình xử lý hồ sơ phía doanh nghiệp vẫn còn lỗi đang list hết các bản ghi ra
![2016-09-19_102656](https://cloud.githubusercontent.com/assets/17695836/18621937/c7b889aa-7e53-11e6-9168-c7e32c71c412.png)

**Comment by khoahp** [comment]
@tragiangdt phần này list ra các lịch sử mà trạng thái không phải là hệ thống.

Em đóng bug này lại anh sẽ tạo một issue về lịch sử xử lý theo thiết kế mới
