### ISSUE TITLE
"Hiển thị thông tin ghi chú của cán bộ nhập lên tab Kết quả (Yêu cầu xử lý) tại bước cuối cùng khi chuyển sang trạng thái hồ sơ mới "

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#990]
Hiển thị thông tin ghi chú của cán bộ nhập lên tab Kết quả (Yêu cầu xử lý) tại bước cuối cùng khi chuyển sang trạng thái hồ sơ mới

**Comment by khoahp** [comment]
@tragiangdt phần này là ntn, chưa rõ lắm
