### ISSUE TITLE
Cán bộ vào xác nhận chuyển bước, click vào nút Ghi lại trên popup, hệ thống báo "this-resource-does-not-exist-or-you-do-not-have-permission-access-to-this-resource Click here to turn back portal"

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#992]
Cán bộ vào xác nhận chuyển bước, click vào nút Ghi lại trên popup, hệ thống báo "this-resource-does-not-exist-or-you-do-not-have-permission-access-to-this-resource Click here to turn back portal"

**Comment by tragiangdt** [comment]
Mô tả:
1. Đăng nhập vào tài khoản canboxuly2.cps@gmail.com
2. thực hiện thủ tục "Xác nhận đăng ký thực hiện khuyến mại theo hình thức mang tính may rủi thực hiện trên địa bàn từ 2 tỉnh, thành phố trực thuộc Trung ương trở lên hoặc theo quy định tại Điều 17 NĐ số 37/2006/NĐ-CP "
CHọn hành động "Thẩm định xong", click Ghi lại
Hệ thống báo "this-resource-does-not-exist-or-you-do-not-have-permission-access-to-this-resource Click here to turn back portal"
Hệ thống xử lý hồ sơ chạy "không ổn định"
KQMM: Quay lại danh sách hồ sơ 
![2016-09-06_151449](https://cloud.githubusercontent.com/assets/17695836/18267279/8ce2fb5e-7448-11e6-9a73-a6231b1dfe3d.png)

**Comment by khoahp** [comment]
@trungnt-ksnb phần phân quyền này chưa làm triệt để các trường hợp, vậy tạm thời @trungnt-ksnb bỏ phần kiểm tra đi nhé.

**Comment by trungnt-ksnb** [comment]
@khoahp Đã bỏ phần check quyền đi

**Comment by tragiangdt** [comment]
Trên qa đã không còn xuất hiện thông báo "this-resource-does-not-exist-or-you-do-not-have-permission-access-to-this-resource Click here to turn back portal"
