### ISSUE TITLE
Không load lại danh sách hồ sơ chờ xử lý khi cán bộ click vào nút Ghi lại trên popup. 

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#993]
1. Vào tài khoản cán bộ
2. Click vào thao tác xử lý
3. Click Ghi lại trên popup, hệ thống báo yêu cầu xử lý thành công
4. Hệ thống quay ra danh sách hồ sơ chờ xử lý nhưng hồ sơ vừa xử lý vẫn còn. phải nhấn F5 lại thì hồ sơ vừa xử lý mới thấy mất

**Comment by huymq** [comment]
issues này @binhth hỏi thêm anh @khoahp xem hồ sơ đang chờ backend xử lý xong thì có dấu hiệu nào để nhận biết không nhé.

**Comment by khoahp** [comment]
@huymq phần này đã trao đổi vs @binhth sau khi xử lý hồ sơ, bổ xung thêm script cho load lại trang. Vì sử dụng redirect bản chất portlet đấy chưa được load lại.

**Comment by tragiangdt** [comment]
@khoahp trên qa vẫn còn lỗi này, em cũng vừa mới gặp

**Comment by tragiangdt** [comment]
trên qa không gặp lỗi này nữa
