### ISSUE TITLE
Chưa tìm kiếm được hồ sơ khi cán bộ tra cứu hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#996]
Mô tả:
- Chưa tìm kiếm được theo mã số tiếp nhận
- Chưa lọc được theo lĩnh vực thủ tục
- Vào http://qa.opencps.vn/group/guest/tra-cuu-ho-so
  tk: canboxuly2.cps@gmail.com
  ![2016-09-09_114948](https://cloud.githubusercontent.com/assets/17695836/18375797/8f5ce060-7683-11e6-8288-ce3989c81330.png)

KQMM: 
- Tìm kiếm được theo mã số tiếp nhận
- Tìm kiếm được theo lĩnh vực thủ tục

**Comment by binhth** [comment]
@huymq 
phần này lỗi thêm lọc theo trạng thái hồ sơ để mặc định bằng "-1" bị sai ko tìm kiếm đc.
sai câu customSQL + hàm xử lý trong finder.
đã fixed.
@tragiangdt : test lại nhá.

**Comment by tragiangdt** [comment]
@khoahp Trên qa chưa tìm kiếm được theo mã tiếp nhận anh ạ, hôm trươc em test trên server dev thì ok r ạ

**Comment by khoahp** [comment]
@tragiangdt test lại phần này nhé, anh mới deploy lên con QA

**Comment by tragiangdt** [comment]
@khoahp 
1. Lọc theo trạng thái hồ sơ chưa hiển thị hết các trạng thái trong danh mục
![2016-09-20_145325](https://cloud.githubusercontent.com/assets/17695836/18662442/9c8f06e0-7f44-11e6-9521-488758517ddb.png)
2. Lọc theo trạng thái hồ sơ không được
3. Tìm kiếm theo mã số tiếp nhận + trạng thái hồ sơ không được

**Comment by tragiangdt** [comment]
@binhth
