### ISSUE TITLE
Không xem được file đính kèm, phiên bản, xem biểu mẫu khai trực tuyến khi cán bộ xem lại hồ sơ ở menu tra cứu hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#997]
1. Vào xem chi tiết một hồ sơ menu tra cứu hồ sơ
   link: http://qa.opencps.vn/group/guest/tra-cuu-ho-so
2. Vào Tab Nội dung hồ sơ.
   Lỗi: 
3. Click vào xem nội dung không xem được file đính kèm
4. Click vào xem phiên bản giấy tờ không được
5. Cilck vào xem biểu mẫu khai trực tuyến không được
   ![2016-09-09_115509](https://cloud.githubusercontent.com/assets/17695836/18375939/c2591b0e-7684-11e6-977a-acd9e2dedb7b.png)

**Comment by binhth** [comment]
@huymq 
phần này thiếu function + script để gọi các màn hình popup
đã bổ sung + đã fixed.
@tragiangdt : test lại nhá.

**Comment by tragiangdt** [comment]
test done trên qa
