### ISSUE TITLE
Chưa lọc được hồ sơ theo tổ chức thực hiện khi bộ đăng nhập ở portlet Tra cứu hồ sơ

### ISSUE THREAD

**Issue by tragiangdt** [VietOpenCPS/opencps#998]
1. Vào tài khoản cán bộ canboxyly2.cps@gmail.com
   link: http://qa.opencps.vn/group/guest/tra-cuu-ho-so
2. vào menu Tra cứu hồ sơ http://qa.opencps.vn/group/guest/tra-cuu-ho-so
   Lỗi: Hiện tại đang hiển thị hồ sơ của tất cả cơ quan thực hiện có trong hệ thống
   KQMM: khi đăng nhập bằng tài khoản cán bộ, hệ thống lọc hồ sơ theo cơ quan thực hiện của cán bộ (không hiển thị tất cả hồ sơ, không hiển thị cả hồ sơ của cơ quan thực hiện khác)
   ![2016-09-09_121006](https://cloud.githubusercontent.com/assets/17695836/18376140/62e94b6a-7686-11e6-8b29-c825cd30d52e.png)

**Comment by huymq** [comment]
Anh @khoahp xem coreteam hỗ trợ giải pháp cho v/đ này với nhé. Nếu chỉ lọc hồ sơ theo cơ quan thực hiện của cán bộ thì @dunglt91 lọc cũng được.

**Comment by tragiangdt** [comment]
Test done trên qa
